### ISSUE TITLE
Multiple definitions of Node

### ISSUE THREAD

**Issue by mpokryva** [TheAlgorithms/Java#105]
The Node class is widely used across many data structures and algorithms. Right now, there are multiple definitions of this class, in basically every single data structure/algorithm that uses it. This introduces a lot of redundancy into the codebase, and also makes bugs more likely to happen. I suggest removing the duplicate declarations of this class where possible, and simply reusing the Node class as defined in Misc.

**Comment by dynamitechetan** [comment]
Cool. Can you help with this issue?

**Comment by mpokryva** [comment]
Sure!
