### ISSUE TITLE
DIRECTORY.MD Link is dead

### ISSUE THREAD

**Issue by Technerder** [TheAlgorithms/Java#1091]
The DIRECTORY.MD link in the README is dead.

**Comment by hv-ojha** [comment]
DIRECTORY.MD doesn't exist in your repository...
Can you please specify what it will contain? if you want I'll create it..

**Comment by Technerder** [comment]
It's linked in the README,
https://github.com/TheAlgorithms/Java/blob/master/README.md#algorithms

**Comment by StepfenShawn** [comment]
The Link is OK now :)
