### ISSUE TITLE
I can't read contribution guidelines.

### ISSUE THREAD

**Issue by SophieYoonseo** [TheAlgorithms/Java#1106]
Contributing.md is dead.
I wanna contribute to this project.
If you are ok, I would like to update the Contributing.md with reference to your project "python".
If not, I want you to fix it.

**Comment by yanglbme** [comment]
Hi @SophieYoonseo, feel free to send a pull request.

**Comment by walter-ind** [comment]
@yanglbme Should I take up this issue?

**Comment by iheb1196** [comment]
switch on the development branch and then you'll find the contribution guide line.good luck
