### ISSUE TITLE
Add license to the repository.

### ISSUE THREAD

**Issue by walter-ind** [TheAlgorithms/Java#1114]
Open source repo(s) should have a valid license which ,if present, officially allows the developers/coders to read and modify it's code.

If you will allow me , I will submit  a PR closing this issue by adding a license to this repository.
Also, suggest me the appropriate license which should be added.

Thanks a lot!

**Comment by yanglbme** [comment]
Hi @walter-ind, you can refer to https://github.com/TheAlgorithms/Python/blob/master/LICENSE.md .

**Comment by walter-ind** [comment]
> Hi @walter-ind, you can refer to https://github.com/TheAlgorithms/Python/blob/master/LICENSE.md .

You want me to add MIT license to this repository?
Am I correct?

**Comment by yanglbme** [comment]
yep @walter-ind
