### ISSUE TITLE
Please merge the pull request of CountWords_easy.java

### ISSUE THREAD

**Issue by UmarGit** [TheAlgorithms/Java#1142]
#1136 please merge this pull request it is the easier version of count words. 
@qckzr  
@AkarshSatija  
@daniel-mueller 
@Egoscio-zz  
@tapaswenipathak

**Comment by UmarGit** [comment]
The Link to CountWords_easy.java
[https://github.com/UmarGit/Java/blob/master/Others/CountWords_easy.java](url)

**Comment by yanglbme** [comment]
https://github.com/TheAlgorithms/Java/blob/master/Others/CountWords.java
