### ISSUE TITLE
find one bug in bubbleSort

### ISSUE THREAD

**Issue by ID-tangrenhui** [TheAlgorithms/Java#1164]
I found one bug in bubble sort. the example unsort array is

> **Integer[] integers = {4, 23, 6, 78, 1, 54, 231, 9, 12}**

**the error function is** 
    public <T extends Comparable<T>> T[] sort(T array[]) {
        for (int i = 0, size = array.length; i < size - 1; ++i) {
            boolean swapped = false;
            for (int j = 0; j < size -1 - i; ++j) {//**Find the smallest one in each cycle**
                swapped = less(array[j], array[j + 1]) && swap(array, j, j + 1);
            }
            if (!swapped) {
                break;  //**there is shouldn't use break to stop cycle**
            }
        }
        return array;
    }
when use given function the result is 

> [78, 231, 54, 23, 12, 9, 6, 4, 1]
break should be replaced by continue

**Comment by Abubakar548** [comment]
i can fix it but can you tell me where is MAIN CLASS so i would run and test it

**Comment by Abubakar548** [comment]
i have fixed the issue can you please tell how can push it?

**Comment by Abubakar548** [comment]
please check this
[BubbleSort.zip](https://github.com/TheAlgorithms/Java/files/3855617/BubbleSort.zip)

**Comment by Abubakar548** [comment]
Kindly Please do check my commit.

**Comment by ID-tangrenhui** [comment]
I ran the code again and got the right results. You fixed the bug. Great




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Abubakar Khawaja"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月17日(星期天) 晚上10:33
收件人:&nbsp;"TheAlgorithms/Java"<Java@noreply.github.com&gt;;
抄送:&nbsp;"小汤"<1220474269@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TheAlgorithms/Java] find one bug in bubbleSort (#1164)




Kindly Please do check my commit.

**Comment by ID-tangrenhui** [comment]
I ran the code again and got the right results. You fixed the bug. Great

**Comment by fuaokai** [comment]
for (int i = 0, size = array.length; i < size - 1; ++i) {
            boolean swapped = false;
            for (int j = 0; j < size - 1 - i; ++j) {
                //判断当前j是否小于j+1元素，如果小于，则进行交换，不断重复，每次将最小的元素放到末尾
                if (swapped) {
                    swapped = less(array[j], array[j + 1]) && swap(array, j, j + 1);
                    swapped = true;
                } else {
                    if (swapped= less(array[j], array[j + 1])){
                        swap(array, j, j + 1);
                    }
                }
            }
            if (!swapped) {
                break;
            }
        }
        return array;

input : [411, 221, 23, 166, 178, 54, 31, 19, 12]
output:  [411, 221, 178, 166, 54, 31, 23, 19, 12]
