### ISSUE TITLE
It seems Fast Fourier Transform is missing for Java

### ISSUE THREAD

**Issue by valerydec17** [TheAlgorithms/Java#1198]

**Comment by faizan2700** [comment]
is someone working on this.

**Comment by faizan2700** [comment]
I will look into it if I can do something.

**Comment by sagnik-chatterjee** [comment]
Hi , can i solve this issue ?

**Comment by valerydec17** [comment]
I am not a person who accepts merges.

**Comment by sagnik-chatterjee** [comment]
If someone could see my pull requests , and could suggest some changes or merge them ..??
