### ISSUE TITLE
Could i add some Memory Management algorithms?

### ISSUE THREAD

**Issue by DekasDimitrios** [TheAlgorithms/Java#1210]
Hello,
          I would like to contribute to the project by adding Memory Management algorithms like Best/Worst Fit etc.

**Comment by stepfencurryxiao** [comment]
Hi, you could fork the repo and pull a request:-)

**Comment by DekasDimitrios** [comment]
Should i create a new folder named "Memory Management" or just add them to the "Others" folder?

**Comment by stepfencurryxiao** [comment]
You'd better add it to "others":-)

**Comment by DekasDimitrios** [comment]
I'll pull request soon, will you be able to review it? :)

**Comment by stepfencurryxiao** [comment]
@DekasDimitrios  Welcome to pull a request! I will review it.
