### ISSUE TITLE
ShellSort Wrong

### ISSUE THREAD

**Issue by XmchxUp** [TheAlgorithms/Java#1224]
I tried your code, find error.
Please check it your code.

I think so this. (My english is bad,Sorry. I'm studying hard.)

          for (int i = gap; i < length; i++) {
                int j;
                T temp = array[i];
                for (j = i; j >= gap && less(temp, array[j - gap]); j -= gap) {
                    array[j] = array[j - gap];
                }
                array[j] = temp;
            }

**Comment by mikegikas** [comment]
it was working before you change it?
if i am correct you change the following lines
T temp = array[i];
array[j] = temp;

**Comment by DarthGrave** [comment]
yeah it work before
