### ISSUE TITLE
Can I add some missing algorithms?

### ISSUE THREAD

**Issue by balogkkinga** [TheAlgorithms/Java#1235]
- Kruskal
- Huffman
- A*
- Bucket sort
- Uniform cost search
- Gale-Shapley

**Comment by Dikshit-Kapoor** [comment]
There are many more algorithms:
1. Soundex Algorithm
2. CAS algorithm
3. Password Encryption using MD5,SHA.
4. Advanced Encryption standard algorithm.
5. Garbage collection algorithm.
