### ISSUE TITLE
Algorithms that should be implemented

### ISSUE THREAD

**Issue by vorosaaa** [TheAlgorithms/Java#1238]
Hi
I would like to add the following algorithms to the code:

- Minimax

- Minimax with alpha-beta pruning

- Topological sort

- DFS

- Sleep sort

**Comment by iheb1196** [comment]
Hi 
I think you could implements whatever algorithms you want , you should provide test cases

**Comment by Ritik2604** [comment]
that algo are quite important ones do it as soon as possible

**Comment by Priya103** [comment]
If non one has started... i will soon PR for this
