### ISSUE TITLE
Packages imports?

### ISSUE THREAD

**Issue by fredz0003** [TheAlgorithms/Java#125]
Sorry if this a dumb question. This is my first time attempting to contribute to get onboard with hacktoberfest. If someone tries to run this it will be errors due to no package import lines. Just looking at Sorts package and only shell sort has the import. Other packages have the same issues and some files are wrongly named for example BinaryTreeSort file and the class name is TreeSort.

By the way I can fix this issues if needed to... Before I start working on my cipher classes.

**Comment by varunu28** [comment]
@fredz0003  Thanks for pointing this out. You can go ahead and do the changes and open a PR. Just make sure you keep a check that there are no conflicts with the master repo

**Comment by fredz0003** [comment]
@varunu28 Got it. It's what I was thinking. I'll fix any file naming issues on the latest master. 

_Sent from my Samsung SM-G955U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
