### ISSUE TITLE
Add linked list

### ISSUE THREAD

**Issue by MohamedBechir** [TheAlgorithms/Java#1286]
Linked lists are powerful data structures which are very useful when you need to do a lot of insertions and removals!

**Comment by shrey6045** [comment]
Correct. Moreover implementing Linked List also tends to increase the efficiency of the code.

**Comment by MohamedBechir** [comment]
@qckzr @AkarshSatija @anirudhmurali  do i start working on it ?

**Comment by MohamedBechir** [comment]
I added the singly linked list and it was merged, thank you
