### ISSUE TITLE
Algorithm for sorting 

### ISSUE THREAD

**Issue by sourav0v0** [TheAlgorithms/Java#1317]
I don't know whether this approach is ever used for sorting or not 
the algo basically works on finding the smallest in the array and arranging it 
[smallestSort.txt](https://github.com/TheAlgorithms/Java/files/4648665/smallestSort.txt)

**Comment by deadshotsb** [comment]
Well I think what you are saying is specifically [Selection Sort](https://github.com/TheAlgorithms/Java/blob/master/Sorts/SelectionSort.java).
