### ISSUE TITLE
Implementing RR Scheduiling using Linked List

### ISSUE THREAD

**Issue by Ritik2604** [TheAlgorithms/Java#1327]
As it is combination of two main topics which make it important 
so anybody want to implement can do that

**Comment by badallogical** [comment]
yes, i am good to go.

**Comment by badallogical** [comment]
i implemented the process queue with ArrayList, but rest of the items like burstTime uses simple array,
is that right or i need to implement all burstTime, ArrivalTime , WaitingTime, TurnAroundTime , CompletionTime with ArrayList ( linklist)

**Comment by gaushikmr** [comment]
@Ritik2604 Can u assign me
