### ISSUE TITLE
Add a LinkedHashSet : ) 

### ISSUE THREAD

**Issue by WaterHashira** [TheAlgorithms/Java#1340]
It is a powerful class which helps in keeping the record of the elements entered in it while at the same time maintaining the insertion order of the entered elements.

Moreover, it uses a hybrid Data Structure ( having features of both Hash Table as well as             Doubly Linked List.

i would love to work on this project, also, as i'm a beginner i may sometimes need a bit of assistance.
: )

**Comment by sanjana1604** [comment]
I am interested to work.

**Comment by sanjana1604** [comment]
@WaterHashira I am interested to work on this.

**Comment by shahabrar7746** [comment]
hey 
this looks a great issue for me to start development.i would like to work on it. might be need some assistance

**Comment by shahabrar7746** [comment]
@WaterHashira could you suggest me some  projects using LinkedHashSet
