### ISSUE TITLE
StringIndexOutOfBoundsException in Java/Maths/ParseInteger.java 

### ISSUE THREAD

**Issue by pointhi** [TheAlgorithms/Java#1345]
The function **parseInt** has a missing size check. This leads to a ```StringIndexOutOfBoundsException``` with the following reproducer:

```java
parseInt("");
```

https://github.com/TheAlgorithms/Java/blob/a60cb58be8b8367d11f14d6f8697b1d612e198e0/Maths/ParseInteger.java#L18-L22

**Comment by deadshotsb** [comment]
@yanglbme Kindly mention the pull request for which the issue was closed.
