### ISSUE TITLE
throw a exception : linkedList cannot be resovled to a type when i try to run it by vscode

### ISSUE THREAD

**Issue by YUbuntu0109** [TheAlgorithms/Java#1356]
![image](https://user-images.githubusercontent.com/43493852/86145550-9ff66600-bb29-11ea-8d7c-21b2fbabc0c5.png)

### hey bro it's throw a exception when I try to run it, please tell me how to fix it , I've never use vscode to run java project before.

**Comment by YUbuntu0109** [comment]
if you add some descrption informations about how to run this project maybe it's will be better all right ?

**Comment by nayanraj210401** [comment]
Hey YUbuntu0109 try to import LinkedList class from java.util package and also make sure to add Java Extension in VScode

**Comment by YUbuntu0109** [comment]
> Hey YUbuntu0109 try to import LinkedList class from java.util package and also make sure to add Java Extension in VScode

ok thanks bro
