### ISSUE TITLE
Coverage Testing

### ISSUE THREAD

**Issue by rjtmahinay** [TheAlgorithms/Java#1368]
In Implementing a new feature/new algorithms, should the coverage testing way beyond 90% or near 100%?

Any feedback would be a great help.

**Comment by pmolchanov2002** [comment]
Coverage testing is a safety net of your application. 

Any changes in the underlining libraries or your own classes should be captured by the unit tests. 

It doesn't make sense to cover getters/setters as their implementation is rarely changed. Not covering getters/setters may significantly low your unit-test coverage. I don't think it's a problem.

**Comment by rjtmahinay** [comment]
@pmolchanov2002 You're right. But the question is the % of the coverage testing since there is none in the repo documentation (README.md) that states how many % must be covered by the coverage testing.
