### ISSUE TITLE
Adding missing algorithms

### ISSUE THREAD

**Issue by ChristinaK97** [TheAlgorithms/Java#1384]
Hey, I would like to add some missing graph algorithms and I was wondering if there are any particular coding style conventions I have to follow for example regarding the comments. Also should I include unit tests or a simple example on the main method of the class is enough?

**Comment by varnaa** [comment]
Refer this [readme](https://github.com/TheAlgorithms/Java/tree/Development#the-algorithms---java-work-in-progress) file.
