### ISSUE TITLE
Add Binary Search Tree DS both Iterative and recursive implementation

### ISSUE THREAD

**Issue by Lakhan-Nad** [TheAlgorithms/Java#1420]
I would like to add Binary Search Tree in Java with following methods:
add element
remove element 
find element
preorder traversal
inorder traversal
postorder traversal

Each of this methods can be implemented both recursively and iteratively.

**Comment by leizhenhao** [comment]
test

**Comment by Lakhan-Nad** [comment]
> test

I will add them. @leizhenhao

**Comment by Lakhan-Nad** [comment]
@leizhenhao I have added the tests and made some doc changes please review.
