### ISSUE TITLE
Is there any implementation for the Rope (Cord) data structure?

### ISSUE THREAD

**Issue by jasonyanwenl** [TheAlgorithms/Java#1447]
Hi, this is my first time come to this great repo. Just would like to ask if you have the implementation for the [Rope/Cord](https://en.wikipedia.org/wiki/Rope_(data_structure)) data structure? I didn't find it in the directory. Thanks!

**Comment by geogiadim** [comment]
Hi, I could start working on it and contribute this algorithm to this repository. Is that okay?

**Comment by jasonyanwenl** [comment]
I am not sure who you are asking. From my side, it’s definitely OK. I would like to see the implementation of the ‘split’ operation especially. I searched various blogs about this but found nothing. Thanks!

**Comment by jasonyanwenl** [comment]
I am not sure who you are asking. From my side, it’s definitely OK. I would like to see the implementation of the ‘split’ operation especially. I searched various blogs about this but found nothing. Thanks!
