### ISSUE TITLE
Java/DataStructures/HashMap/Hashing/HashMap.java.  In line100-108, method delete has some problems.

### ISSUE THREAD

**Issue by xiao1i** [TheAlgorithms/Java#1448]
In method delete(Node,int key),if i set hsize=3,then add 2,5,8,11in the bucket 2.When i want to delete 11,this method doesn't work.I think it should be modified as follows:

private void delete(Node n, int key) {
            if(n.getNext().getKey() == key) {
                if(n.getNext().getNext() == null) {
                    n.setNext(null);
                } else {
                    n.setNext(n.getNext().getNext());
                }
            } else {
                delete(n.next,key);
            }
        }

**Comment by BridBlue** [comment]
Hashmap.Node.getKey() return an Object ，so you should try to use equals()
