### ISSUE TITLE
Contribute a new algorithm

### ISSUE THREAD

**Issue by geogiadim** [TheAlgorithms/Java#1460]
Hello, 
I would like to contribute my implementation for Round Robin algorithm. This is a cpu scheduling algorithm for processes.
I want to push my code in "development" branch as I read in the readme but I don't have the permission.

I will wait for an answer. 
Thank you in advanced.

**Comment by rjtmahinay** [comment]
Hi @geogiadim 
First you must fork the repository and then push your contribution to your forked repository with development branch. After pushing, submit a pull request.

**Comment by geogiadim** [comment]
Hello, thank you for your answer. I ve already done this process.

**Comment by rjtmahinay** [comment]
Hi, I suggest to close this issue. Thanks

**Comment by geogiadim** [comment]
Yes, sure. Sorry I just forget it.
