### ISSUE TITLE
Make changes to Others/PasswordGen.java

### ISSUE THREAD

**Issue by arrnavvv** [TheAlgorithms/Java#1471]
The file: https://github.com/TheAlgorithms/Java/blob/master/Others/PasswordGen.java
The current code doesn't always generate passwords that follow the policy of passwords which are at least 1 lower, 1 upper, 1 number, and 1 special character in your password.
I am attaching an example of one such password generated by the current code.

![Screenshot (1)](https://user-images.githubusercontent.com/61576354/93570440-a40b8480-f9b0-11ea-9ab5-2d0616acac55.png)
This password has no number in this password which violates the rules.

Can I work on solving this issue?

**Comment by rjtmahinay** [comment]
Hi @arrnavvv 
If there is no existing "pull request" that fixed that issue. Then, you may worked on it.
