### ISSUE TITLE
How configure jdk 

### ISSUE THREAD

**Issue by ghost** [TheAlgorithms/Java#1472]
I configure jdk many of the time. I am still failed please help me. When I used textpad my program does not compile even if it is complety correct...

**Comment by rjtmahinay** [comment]
Hi @anwarrahim 
What are you encountering during execution of "javac" in command line?

**Comment by navitkumar03** [comment]
Set bin folder path in system variables for enabling javac and any other java commands

**Comment by jerujor** [comment]
@anwarrahim remove it and then re-install the programme. Sometimes there are such problems.

**Comment by jxgrxn** [comment]
Do you have compatable JDK/IDE?

**Comment by Spardha-hash** [comment]
Firstly download the compatible sdk and then install it and then set the path in environment variables then check it on the cmd

**Comment by yansheng836** [comment]
It might be better to ask the search engines, like <https://google.com>.
