### ISSUE TITLE
Add Conway's Game of Life

### ISSUE THREAD

**Issue by 0Zeta** [TheAlgorithms/Java#1519]
From [Wikipedia](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life):
"The Game of Life, also known simply as Life, is a cellular automaton devised by the British mathematician John Horton Conway in 1970. It is a zero-player game, meaning that its evolution is determined by its initial state, requiring no further input. One interacts with the Game of Life by creating an initial configuration and observing how it evolves."

**Comment by xphlawlessx** [comment]
I would like to add this one , if that's okay?

**Comment by 0Zeta** [comment]
> I would like to add this one , if that's okay? 

Hi, I'm sorry, but I already implemented it and opened a PR.

**Comment by xphlawlessx** [comment]
Oh, no worries. Thanks for replying :)
