### ISSUE TITLE
Hacktoberfest 2020 - Implement Java algorithms or data structures, fix existing ones and more!

### ISSUE THREAD

**Issue by dynamitechetan** [TheAlgorithms/Java#1528]
The annual [Hacktoberfest](https://hacktoberfest.digitalocean.com/) is around the corner! Register on [Hacktoberfest's website](https://hacktoberfest.digitalocean.com/) and open 4 pull requests during October 2020 to receive the swags (if you're the first 70,000 participants)!

In our Java repository, there are currently several open [issues](https://github.com/TheAlgorithms/Java/issues).

What's more, you can also **fix an existing bugs, improve any documentation** and **provide better implementations** for [certain algorithms](https://github.com/TheAlgorithms/Java/blob/master/DIRECTORY.md)! Feel free to inform the community by **filling an issue** and start hacking! If you're new to contributing code, please read our [Contribution Guidelines](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md) for an overall understanding and ask questions on the internet - Google, StackOverflow or our Gitter.

[TheAlgorithms](https://github.com/TheAlgorithms) has repositories in other programming languages, so find your language and start coding there!

### What you can do to participate
1. Read our [Contribution Guidelines](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md)
2. Comment below or open an issue (for big ideas you may want the community to know) on your new implementations, fixes or functionalities
3. Start hacking!
4. Open a pull request for your contribution
5. Label your pull requests with `hacktoberfest`
6. Wait until your pull requests get reviewed or merged! In the meantime, you can review someone else's pull requests too

### Useful links
* Our [Gitter](https://gitter.im/TheAlgorithms) channel
* The [Contribution Guidelines](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md) of TheAlgorithms/Java
* Our [Code of Conduct](https://github.com/TheAlgorithms/.github/blob/master/CODE_OF_CONDUCT.md)
* The [Directory](https://github.com/TheAlgorithms/Java/blob/master/DIRECTORY.md) of TheAlgorithms/Java

### Remarks
* Please observe Hacktoberfest's rules, terms and FAQ. If a pull request is marked `invalid` or `spam` it would not be counted and the person may be disqualified for the swags.
* Hacktoberfest 2020 is an event presented by DigitalOcean, Intel and DEV.

**Comment by jinicode** [comment]
I would also love to add hashing algorithms.

**Comment by MonarchChakri** [comment]
@yanglbme / @dynamitechetan 
Created a PR https://github.com/TheAlgorithms/Java/pull/1582
Please review and merge.

**Comment by NirmalSilwal** [comment]
I look forward to **add new implementation** of [this code on nth fibonacci number](https://github.com/TheAlgorithms/Java/blob/master/DynamicProgramming/Fibonacci.java) using **iterative approach** (without recursion) in **Dynamic programming paradigm.**

Thanks

**Comment by NirmalSilwal** [comment]
Hello @dynamitechetan  I have made PR #1591, please review and do let me know about it.

**Comment by diptinayan** [comment]
I am also interested in adding some of the basic data structures and algorithms.

**Comment by debajitdeb11** [comment]
Hey, @dynamitechetan I want to add a few algorithms with examples based on Quick Sort. Can you please assign me?

**Comment by SHIKHAR-CHANDRA** [comment]
I want to add Huffman coding implementation in Java.

**Comment by varad64** [comment]
Hi @dynamitechetan I'd love to add several algorithms based on bitwise operators.

**Comment by kaunik07** [comment]
@dynamitechetan , please assign me a few Dynamic Programming Algorithm questions .

**Comment by ShimoniSinha2019H1030019G** [comment]
Hello @dynamitechetan  I have created a new java file to implement skip list.  PR #1857   Can you please verify and merge it?

**Comment by NikhilTaneja98** [comment]
I want to do contribution in dynamic programming section. Plz consider it as I am participating in Hacktoberfest 2020
