### ISSUE TITLE
Fenwick (Binary Indexed Tree)

### ISSUE THREAD

**Issue by st235** [TheAlgorithms/Java#1535]
There are no such data structures as Fenwick tree. Fenwick (or Binary Indexed Tree) is a data structure that can efficiently update elements and calculate prefix sums in a table of numbers.

Read more here: https://en.wikipedia.org/wiki/Fenwick_tree

**Comment by Rohanfizz** [comment]
I would like to solve this, can u please assign this to me?
Peace :-)

**Comment by st235** [comment]
@Rohanfizz hi 👋

I have already solved it in this PR - https://github.com/TheAlgorithms/Java/pull/1536 🙂

**Comment by Rohanfizz** [comment]
can you please give me some other issue..I dont know anything in dev in a competetive programmer and i  like problem solving, so im having trouble participating in hackoctober fest :'(

**Comment by st235** [comment]
anybody would like to review this?
