### ISSUE TITLE
Add "Median of two sorted arrays"

### ISSUE THREAD

**Issue by anamkhxn** [TheAlgorithms/Java#1541]
Pl. assign this issue to me.

**Comment by MokshTehlan** [comment]
i would like to contribute in this can you please assign this to me

**Comment by ng29** [comment]
i can take this, solved this on leetcode :)

**Comment by mihirsood** [comment]
I'd love to contribute to this issue. Please assign it to me. Thank you.

**Comment by mshreya9** [comment]
Please assign it to me, I would love to contribute the solution to this problem. Thank you :)

**Comment by Blackwidow2981** [comment]
I would like to contribute to this issue.
