### ISSUE TITLE
Bleak Number 

### ISSUE THREAD

**Issue by parjanyaacoder** [TheAlgorithms/Java#1546]
Want to contribute as a part of Hacktoberfest 2020. 

Algorithm to check if a number is a bleak number or not.  
A number 'n' is called Bleak if it cannot be represented as sum of a positive number x and set bit count in x  is not equal to n for any non-negative number x

**Comment by parjanyaacoder** [comment]
@dynamitechetan Please assign me this issue.

**Comment by Shaishav-Anand** [comment]
Hii @parjanyaacoder i want to contribute to this please assingn it me it will be very gratefull.

**Comment by parjanyaacoder** [comment]
Hi @Shaishav-Anand I am not the project maintainer for this repository. I cannot assign you this issue.
