### ISSUE TITLE
Shortest Path in a Matrix using recursion and backtracking. 

### ISSUE THREAD

**Issue by akshat-fsociety** [TheAlgorithms/Java#1632]
**_For Maze give below the shortest path would be 16 from (0,0) to (8,0)_**

**Test Case 1:**
                                        { 1, 1, 1, 1, 1, 0, 0, 1, 1, 1 },
					{ 0, 1, 1, 1, 1, 1, 0, 1, 0, 1 },
					{ 0, 0, 1, 0, 1, 1, 1, 0, 0, 1 },
					{ 1, 0, 1, 1, 1, 0, 1, 1, 0, 1 },
					{ 0, 0, 0, 1, 0, 0, 0, 1, 0, 1 },
					{ 1, 0, 1, 1, 1, 0, 0, 1, 1, 0 },
					{ 0, 0, 0, 0, 1, 0, 0, 1, 0, 1 },
					{ 0, 1, 1, 1, 1, 1, 1, 1, 0, 0 },
					{ 1, 1, 1, 1, 1, 0, 0, 1, 1, 1 },
					{ 0, 0, 1, 0, 0, 1, 1, 0, 0, 1 },

**_For Maze give below the shortest path would be 5 from (0,0) to (2,3)_**

**Test Case 2:**
                                        {1,1,0,0},
                                        {0,1,1,0},
                                        {0,0,1,1},

**Comment by yashbansal130** [comment]
please assign this to me. I can do this in Java

**Comment by yashbansal130** [comment]
@akshat-fsociety please assign this to me

**Comment by akshat-fsociety** [comment]
@yashbansal130 This issue has been resolved refer PR #1633 . If you feel anything missing drop a message here.
