### ISSUE TITLE
A better implementation to check if two strings are anagrams of each other

### ISSUE THREAD

**Issue by mshreya9** [TheAlgorithms/Java#1640]

**Comment by sj056** [comment]
I have added the PR for the same.

**Comment by anmol193** [comment]
can i do this in java?

**Comment by rbshealy** [comment]
@mshreya9 Could you kindly provide an argument supporting your claim and describe what kind of solution is needed? As of now the existing CheckAnagram.java file seems like it works very well.

**Comment by kshivam953** [comment]
@mshreya9  Please review #2061  and merge the PR and please let me know if any problem occur.
