### ISSUE TITLE
Recursive Hanoi Algo

### ISSUE THREAD

**Issue by shreya10032000** [TheAlgorithms/Java#1650]
Tower of Hanoi is a mathematical puzzle where we have three rods and n disks. The objective of the puzzle is to move the entire stack to another rod, obeying the following simple rules:
1) Only one disk can be moved at a time.
2) Each move consists of taking the upper disk from one of the stacks and placing it on top of another stack i.e. a disk can only be moved if it is the uppermost disk on a stack.
3) No disk may be placed on top of a smaller disk.

**Comment by Blackwidow2981** [comment]
I would like to work on this issue.Please assign this issue to me .

**Comment by pnpninja** [comment]
I would like to work on this issue.Please assign this issue to me .

**Comment by Rohanfizz** [comment]
Can you please assign this to me? I would love to contibute in different languages :-)
Peace:)

**Comment by devanshi1110** [comment]
Can you please assign this to me? I would love to contribute in different languages :-)
Peace:)
