### ISSUE TITLE
Frog Jump Problem.    

### ISSUE THREAD

**Issue by softechnoconrajat** [TheAlgorithms/Java#1653]

**Comment by Shaishav-Anand** [comment]
Hii @softechnoconrajat I Want to contribute to this please assign it to me.

**Comment by softechnoconrajat** [comment]
@Shaishav-Anand As you can see I don't have permission to do that. 
Sorry, but you are on your own.
Please add your contribution and raise PR. 
My intent on raising this issue was to see if this is already resolved.
