### ISSUE TITLE
Wrong Travis-CI badge

### ISSUE THREAD

**Issue by JPDSousa** [TheAlgorithms/Java#167]
The Travis-CI badge points to the wrong repository (TheAlgorithms/Python), which is itself not an active repository according to Travis-CI.

I also don't see a .travis.yml file in this repo so i guess there was some kind of mistake here.

**Comment by MattBizzo** [comment]
@AnupKumarPanwar Is this a reference to #110 ? I'm asking because if it is, we can just modify the reference to https://docs.travis-ci.com/user/languages/java/
