### ISSUE TITLE
Doubly LinkedList Implementation

### ISSUE THREAD

**Issue by Rohanfizz** [TheAlgorithms/Java#1689]
Doubly LinkedList is a data structure which is really helpful and Some Advantages over singly linked list are mentioned below->

1) A DLL can be traversed in both forward and backward direction.
2) The delete operation in DLL is more efficient if pointer to the node to be deleted is given.
3) We can quickly insert a new node before a given node.

**Comment by Rohanfizz** [comment]
#1688 #

**Comment by rbshealy** [comment]
We already have a DoubleLinkedList.java implementation

**Comment by Rohanfizz** [comment]
oh Okay
