### ISSUE TITLE
Add volume formulas

### ISSUE THREAD

**Issue by 0Zeta** [TheAlgorithms/Java#1693]
Implement the formulas to calculate the volumes of important geometrical objects

**Comment by ravidyarev** [comment]
Working on this issue

**Comment by 0Zeta** [comment]
I already implemented it and made a PR, but there are many volume formulas I haven't implemented.

**Comment by ravidyarev** [comment]
Can you let me know the file name and I can implement the rest.

**Comment by 0Zeta** [comment]
@ravidyarev Well, the pull request hasn't been merged yet, but you can find my commit [here](https://github.com/TheAlgorithms/Java/pull/1694/commits/8ce3820183e7847bf23a67d5a031c569024bba8c).

**Comment by ravidyarev** [comment]
Thank you!

**Comment by Mathur777** [comment]
kindly assign me
