### ISSUE TITLE
Dynamic Programmig:- Longest Palindromic Subsequence

### ISSUE THREAD

**Issue by projectelex** [TheAlgorithms/Java#1709]
Longest Palindromic Subsequence is a type of subsequence in which the two strings are considered Eg:-
String 1:- BBABCBCAB
String 2:- BABCBAB

The result i.e. the Longest Palindrimic Subsequence from the above two strings is:
Result 1:- BBBBB
Result 2:-BBCBB

**Comment by matteomessmer** [comment]
I can do this

**Comment by matteomessmer** [comment]
Ok I finished, but the results of my algorithm are different from the two test cases you wrote. 
Are you sure that the LPS of "BBABCBCAB" is "BBBBB"? Shouldn't it be "BABCBAB"? And also "BABCBAB" is a palindrome itself, hence it is already its longest palindromic subsequence. Or maybe I missed something, I'm not 100% sure I understood what you mean with LPS.
Tell me if I shall make a pull request

**Comment by projectelex** [comment]
Yes you are right my also answer came to be a length of 7. It was a mistake from me

**Comment by matteomessmer** [comment]
Ok, thank you. I make the pull request
