### ISSUE TITLE
Longest Common Substring

### ISSUE THREAD

**Issue by Amit-Jaydeepsingh-Thakur** [TheAlgorithms/Java#1718]
The Longest Common Substring is an approach in which we find out the the Longest Common Substring from the two input strings
Eg:-
s1="abbaf"
s2="abcdef"

The result will be 2 as the length of the Longest Common Substring which is "ab" is 2

**Comment by LalwaniSurendra** [comment]
Can I take this?

**Comment by Deepak2417** [comment]
Kindly assign this to me.

**Comment by srajantiwari** [comment]
I'll be happy to contribute code for the problem in Java or C++. Could you assign the problem to me?

**Comment by sgarg5794** [comment]
Can you assign this issue to me , I can contribute and write the code in java.

**Comment by 13snehitha** [comment]
Can you assign this to me.

**Comment by dhairya-parikh** [comment]
Can you please assign this to me?
@projectelex
