### ISSUE TITLE
Unbounded Knapsack (Dynamic Programming)

### ISSUE THREAD

**Issue by shahzaibahmad3** [TheAlgorithms/Java#1728]
Given Input : an array of weights wt[], an array of values val[] containing weights and values for each item and a Weight W of Knapsack.
Output : Maximise the profit. 
here we are allowed to use unlimited number of instances of an item unlike 0-1 Knapsack problem.

Test Case:
input- 	wt={1,2,3,4}
		val={25,35,10,25},  W=8
Output-   200

**Comment by rangira** [comment]
Can I take this

**Comment by sanguvk123** [comment]
can i do this?

**Comment by icoder211** [comment]
I'm taking this up
