### ISSUE TITLE
Sleep sort algo

### ISSUE THREAD

**Issue by sreechand2002** [TheAlgorithms/Java#1750]
sleep sorting makes use of threads to sort the element

**Comment by rbshealy** [comment]
What are the benefits and drawbacks of this algorithm? How is it implemented?

**Comment by sreechand2002** [comment]
In this type of sorting for each value in the array  a thread is created and sleeps for the amount of time as the value of the array element and then wakes up and prints the values which is the array element , the drawback is its not efficient when the difference between numbers are very less

**Comment by sreechand2002** [comment]
The benefits of this algo is that all the sorting is done by threads hence no auxiliary space is required , it more oriented towards OS unlike other algos, the drawback is that , it doesnt work efficiently when difference between the numbers is small(ex 1,2,3,4)
It is implemented using threads , for each value of array a thread is created and made to sleep for so much of time and which ever thread wakes up first , it prints the value for the time it slept which the values of an element in the array

**Comment by dhairya-parikh** [comment]
Can you please assign this to me?
@sreechand2002
