### ISSUE TITLE
[Hacktoberfest] Added Automorphic Number under Maths section

### ISSUE THREAD

**Issue by DeveshBaranwal** [TheAlgorithms/Java#1776]
An automorphic number is a number whose square "ends" in the same digits as the number itself. For example, 5^2 = 25, 6^2 = 36, 76^2 = 5776, and 890625^2 = 793212890625, so 5, 6, 76 and 890625 are all automorphic numbers.

Test Data
Input a number : 76

Output:
Input a number : 76                                                                                           
Automorphic Number.

**Comment by DeveshBaranwal** [comment]
Added Automorphic Number

**Comment by DeveshBaranwal** [comment]
> An automorphic number is a number whose square "ends" in the same digits as the number itself. For example, 5^2 = 25, 6^2 = 36, 76^2 = 5776, and 890625^2 = 793212890625, so 5, 6, 76 and 890625 are all automorphic numbers.
> 
> Test Data
> Input a number : 76
> 
> Output:
> Input a number : 76
> Automorphic Number.

**Comment by Kritimakaushal** [comment]
Please assign it to me. I want to do this in java.

**Comment by Kritimakaushal** [comment]
I submitted my PR for automorphic number. Please review it and please add the label "hacktober-accepted" to it. Please.

**Comment by prashantdoshi28** [comment]
Hey @DeveshBaranwal , why was this issue reopened? Please add proper message when you reopen an issue.

**Comment by prashantdoshi28** [comment]
Hey @ayaankhan98 , please check this issue, I think this issue can be closed as no PRs are linked to it and creator of issue has not provided valid reason for reopening of it. Please do necessary.
