### ISSUE TITLE
Add projecteuler solution for problem 20

### ISSUE THREAD

**Issue by chamil321** [TheAlgorithms/Java#1824]
link: https://projecteuler.net/problem=20

 n! means n × (n − 1) × ... × 3 × 2 × 1

 For example, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,
 and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.

 Find the sum of the digits in the number 100!

**Comment by pratik-2020** [comment]
please assign me this

**Comment by programmer-anvesh** [comment]
Hi, Could you please assign this task to me. My rank on Project Euler on HackerRank is 1482.

**Comment by alokjai** [comment]
please assign me sir
