### ISSUE TITLE
Make StackArray Implementation Generic

### ISSUE THREAD

**Issue by rachitbhalla** [TheAlgorithms/Java#1853]
The StackArray is implemented using integer array and can hold only integer values. However, it can be modified using Generics to hold value of any type.

**Comment by Antwhite420** [comment]
Do you need help with the generic issue? I could give it a try.

**Comment by ayaankhan98** [comment]
> Do you need help with the generic issue? I could give it a try.

That PR is quite old, see if the author respond to that or else you can make a new PR for this.
