### ISSUE TITLE
Decimal to BCD(Binary Coded Decimal)

### ISSUE THREAD

**Issue by BasilVictor** [TheAlgorithms/Java#1861]
# Decimal to BCD(Binary Coded Decimal)
This issue is created so that a Java class can be added to convert decimal numbers to BCD forms.
One such example would be to convert **248** to its _BCD form_, and the result would be **0010 0100 1000**

P.S. Since I am new to this repository, after reading the Contributions file, I still could not understand that should I straight away make this class and submit a pull request or should I wait for a confirmation and then do the pull request.😅

**Comment by shahabrar7746** [comment]
i've created class where  you just to need  type decimal numbers and it will calculate BCD
and i would like contribute on your project
