### ISSUE TITLE
Add an algorithm to transpose a matrix

### ISSUE THREAD

**Issue by VishnuNairP** [TheAlgorithms/Java#1904]

**Comment by jain13tushar** [comment]
Hi @VishnuNairP,
Please assign this issues to me, I want to work on it for hecktoberfest
Regards,
Tushar

**Comment by dhairya-parikh** [comment]
Can you please assign this to me?
@projectelex

**Comment by daminimehra** [comment]
hey, i would like to on this issue.

**Comment by Rishabrp99** [comment]
Hey @VishnuNairP Can you please assign it to me? I would like to work on this .

**Comment by limitless-Sky** [comment]
Hey! @VishnuNairP can I work on this.

**Comment by Priya103** [comment]
If still it is unassigned...... please assign this to me
