### ISSUE TITLE
Need more algorithms about Date & Time calculation

### ISSUE THREAD

**Issue by huynguyez** [TheAlgorithms/Java#1906]
I believe we need a new category for this project about date time computing. Such as calculating number of days between two specified date or such algorithms related to that. I will add some soon. 

Let me know what you guys think?

**Comment by dhairya-parikh** [comment]
Can you please assign this to me?
@VietnameZe

**Comment by VietnameZe** [comment]
> Can you please assign this to me?
> @VietnameZe

Hi I'm not the maintainer of this project
