### ISSUE TITLE
Add BInary Exponentiation in Maths Library

### ISSUE THREAD

**Issue by Lakhan-Nad** [TheAlgorithms/Java#1943]
Binary Exponentiation is one of the most important concepts used in Competetive Programming.
We can add a reference implementation in Maths package.

**Comment by tusharjain88954** [comment]
@Lakhan-Nad Why are you re-open this issue, as there is no error in code. I don't get the error. May you please elaborate it?

**Comment by Lakhan-Nad** [comment]
The error was due to Google-Java-Format and something due to GitHub actions. So I repopened this
