### ISSUE TITLE
No implementations of CircleLinkedLists

### ISSUE THREAD

**Issue by Moro-Code** [TheAlgorithms/Java#20]
I have tried to push implementation onto new branch but it seems you have prevented people from creating new branches.

**Comment by zacharyjones123** [comment]
What files did you try to add? It should have worked

**Comment by Moro-Code** [comment]
Well I tried to add a circle linked list implementation with generics. I tried to create a new branch however it denied me from doing so

**Comment by zacharyjones123** [comment]
What you have to do is fork this original repository. Add in the Circle Linked List files. Then perform a pull Request and wait for the owners to approve your request.

**Comment by Moro-Code** [comment]
ahh I see well I'll try that thank you!

**Comment by zacharyjones123** [comment]
You are welcome! Good luck!
