### ISSUE TITLE
Tim Sort

### ISSUE THREAD

**Issue by hemanth-kotagiri** [TheAlgorithms/Java#2003]
Timsort is a sorting algorithm, derived from merge sort and insertion sort, and is used in Java and Python for the built-in sorting methods.

For more information: [Tim Sort](https://en.wikipedia.org/wiki/Timsort)

**Comment by hemanth-kotagiri** [comment]
I would raise a PR on the same soon.

Thanks!

**Comment by ayaankhan98** [comment]
@hemanth-kotagiri any update over this? just asking.

**Comment by hemanth-kotagiri** [comment]
Hey, @ayaankhan98 . I have the code implemented. I'll raise a PR soon. I've been busy with college lately.

Thanks!

**Comment by ayaankhan98** [comment]
> Hey, @ayaankhan98 . I have the code implemented. I'll raise a PR soon. I've been busy with college lately.
> 
> Thanks!

Okay No problem! 👍

**Comment by Antwhite420** [comment]
Could I help here?

**Comment by ayaankhan98** [comment]
> Could I help here?

sure go ahead, don't ask, just make a PR we will review.
