### ISSUE TITLE
Fix 2D array being passed to Arrays.fill in FloydWarshall

### ISSUE THREAD

**Issue by ChenOst** [TheAlgorithms/Java#2009]
[Here](https://github.com/TheAlgorithms/Java/blob/master/DataStructures/Graphs/FloydWarshall.java#L17) an attempt is being made to pass a 2D array to Arrays.fill().
This is not correct as Arrays.fill() accepts a single dimensional array.

I would like to fix this bug myself if that is ok

Test case describing the bug:
Try to run FloydWarshall.java with legitimate input

Expected behavior:
Succeeds

Actual behavior:
java.lang.ArrayStoreException: java.lang.Integer
	at java.base/java.util.Arrays.fill(Arrays.java:3639)

**Comment by prashantdoshi28** [comment]
Hi @icoder211 and @ChenOst , as far as I know, currently you both have created PRs for fixing same issue. Can you guys collaborate and do required. Thanks :)

**Comment by ChenOst** [comment]
Hey @icoder211 and @prashantdoshi28, I have updated my PR (#2010 ) to eliminate Arrays.fill() entirely,
So we can have a PR that fixes this issue specifically instead of having #2027 handle multiple issues in one PR.

The problem is that I am failing the check for "Prettier" in #2010 , could you advice what the problem may be?

**Comment by icoder211** [comment]
@ChenOst ,I am not sure how to make two separate PR's, it's just committing the changes to the same fork, and when I make the PR, it updates my old PR.
