### ISSUE TITLE
Write code in Java Programming Language using JavaFX (GUI) to compute the area, perimeter, and diagonal of a rectangle.
The user will enter the length and height of the rectangle via textfields in the GUI and the computed answers will also be shown on the GUI.


### ISSUE THREAD

**Issue by moAsmarDx** [TheAlgorithms/Java#2028]
I really need help im trying but i cant do it
![Screenshot_20201113-160623_Word.jpg](https://user-images.githubusercontent.com/71011088/99071222-225c5f80-25cb-11eb-9a33-e741d03ee604.jpg)

**Comment by SundusAdwan** [comment]
do you still need help?

**Comment by Rashika101** [comment]
Hey!! are you willing to accept new contributors? I am interested into contributing to this repository so, if you could explain a bit more this feature request, it would be great.
Thanks
