### ISSUE TITLE
Add a Simple calculator

### ISSUE THREAD

**Issue by tharun9746** [TheAlgorithms/Java#2050]
Almost all the tutorial and courses teaching java finally ends up building a simple calculator. So if we could post the same under Misc. section it would be a great help for beginners learning java (java swings). 
Personally iam a beginner and felt a minimal code for calculator would be a great help for all beginners.
I look forward to do the same and make a pull request.

**Comment by Aadersh-Chaubey** [comment]
I am a beginner in GitHub and looking for some simple stuff to start.
so I will be happy if you allow me to code that calculator

**Comment by Prabhat-kumar-developer** [comment]
I have code for simple  java swing code for calculator.

**Comment by Prabhat-kumar-developer** [comment]
https://aspprabhat2784.blogspot.com/p/calculator-java-program.html

**Comment by Sinha-09** [comment]
May I take this issue?

**Comment by tharun9746** [comment]
Yeah for sure

**Comment by shwhite17** [comment]
i would like to contribute on it !!

**Comment by Rashika101** [comment]
Hey!!
are you willing to accept new contributors? I am interested into contributing to this repository so, if you could explain a bit more this feature request, it would be great.
Thanks

**Comment by tharun9746** [comment]
Yes you may contribute to this project.
Iam looking forward to build a calculator using JAVA Swing package.
It contains numbers from 0-9 and operations +,-,*,/ and clear button (You
may add more scientific operations as per your knowledge).
I almost have a code for simple calculator but its not working with
negative numbers.
So if you could make one you may.

**Comment by Rashika101** [comment]
@tharun9746 
Will You share the code on which You are working?

**Comment by shahabrar7746** [comment]
i've already created simple calculator in eclipse so, if you let me  i'll manage this issue

**Comment by adnanmorsy97** [comment]
Hey, @thakursaurabh1998 is this issue still open ? I would like to take it :)

**Comment by adnanmorsy97** [comment]
Hey, @tharun9746  is this issue still open ? I would like to take it :)

**Comment by Priya7781** [comment]
hey I want to contribute to this issue. is it still avialable?
