### ISSUE TITLE
Would not be "distance" in this line?

### ISSUE THREAD

**Issue by DieKyo** [TheAlgorithms/Java#2055]
https://github.com/TheAlgorithms/Java/blob/c85223bfca0b84966c4df8655f255b9f846c60a4/DataStructures/Graphs/BellmanFord.java#L51

**Comment by yanglbme** [comment]
Hi @DieKyo , you can create a pull request to fix the typo :)

**Comment by DieKyo** [comment]
Ok bro, i have to understand and searching somethings yet, because I'm totally new in programming...

**Comment by sameerahmedk** [comment]
Hey @DieKyo, I'm working on this issue since it still hasn't been corrected.
