### ISSUE TITLE
 Maybe here would be "computation"...? 

### ISSUE THREAD

**Issue by DieKyo** [TheAlgorithms/Java#2056]
https://github.com/TheAlgorithms/Java/blob/c85223bfca0b84966c4df8655f255b9f846c60a4/DataStructures/Graphs/BellmanFord.java#L90

**Comment by ayaankhan98** [comment]
yes a minor typing mistake

**Comment by DieKyo** [comment]
Its not necessary fix this?

**Comment by ayaankhan98** [comment]
> Its not necessary fix this?

these are just comments used for illustration purpose, it will not effect the code in anyway and there is no harm in fixing these things also they are not mandatory to fix because anyone who knows english can easily understand. But it's always better to have things in right place.

**Comment by DieKyo** [comment]
> > Its not necessary fix this?
> 
> these are just comments used for illustration purpose, it will not effect the code in anyway and there is no harm in fixing these things also they are not mandatory to fix because anyone who knows english can easily understand. But it's always better to have things in right place.

Ok, thank you for the explain. :+1:
