### ISSUE TITLE
Contributing to the Documentation link not working ,showing 404 Not Found error

### ISSUE THREAD

**Issue by Jassi10000** [TheAlgorithms/Java#2090]
**Describe the bug**

I wanted to contribute to the repository but when I clicked on to look for " Contributing to the Documentation " to see the Contributing Guidelines once , its showing a 404 error , that its not available

**To Reproduce**

**Expected behavior**

I expected it to open and show me the contributing guidelines

**Screenshots**

![issue1](https://user-images.githubusercontent.com/64856348/105247293-90f50500-5b9a-11eb-841c-75382adeaf59.PNG)

**Device Specification**

**Additional context**

**Comment by PrajwalG22** [comment]
@Jassi10000 
Hello, is anyone working on this issue?
If not can you help me getting started.

**Comment by Jassi10000** [comment]
@PrajwalG22 Actually I think there is some glitch in the link that directs us to the  " Contributing to the Documentation  "
and of course we can't do anything to bring back documentation , its totally the work of Repo Maintainers 
So I think  there will be no gain we both also work on it , its a glitch in the repo only

* Btw You can try other issues , feel free to ask for help

**Comment by PrajwalG22** [comment]
@Jassi10000 Thank You!
