### ISSUE TITLE
Faster algorithms

### ISSUE THREAD

**Issue by donno2048** [TheAlgorithms/Java#2105]
Just to make sure, making the algorithms better but harder to understand is off limit, right?

I mean like changing the isPrime function to:
```java
public static boolean isPrime(int n) {return ((new Factorial().factorial(n - 1) + 1) % n == 0);}
```

**Comment by JesperStroebaek** [comment]
Will not change anything, just looking and learning 👍 I'm just impressed 😄

Sendt fra ProtonMail-mobil

-------- Originalbesked --------
Til 17. feb. 2021 13.48, Elisha Hollander skrev:

**Comment by ayaankhan98** [comment]
@donno2048 you can add this version too in repository but with proper explanation and suitable references for people to learn.
