### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by ayaankhan98** [TheAlgorithms/Java#2116]
### Description
Remove developemt branch instruction form `README.md`. It was earlier decided to wrap the complete repository into a Java Project. But this idea is not suitable, The sole purpose of this organisation is to serve for educational purpose. Therefore, we want each and every file to be independent from other files.

**Comment by akhatami** [comment]
@ayaankhan98 

May I start working on this?

If I'm not mistaken, the first line: _"NOTE: A Development branch is made for this repo where we're trying to migrate the existing project to a Java project structure. You can switch to Development branch for contributions. Please refer this issue for more info."_ should be removed, right?

**Comment by ayaankhan98** [comment]
> @ayaankhan98
> 
> May I start working on this?
> 
> If I'm not mistaken, the first line: _"NOTE: A Development branch is made for this repo where we're trying to migrate the existing project to a Java project structure. You can switch to Development branch for contributions. Please refer this issue for more info."_ should be removed, right?

yes.
