### ISSUE TITLE
Sorting algorithms

### ISSUE THREAD

**Issue by Petraa1999** [TheAlgorithms/Java#2144]
[ ] : 3 way merge sort
[ ] : bubble sort
[ ] : recursive bubble sort
[ ] : radix sort

**Comment by vivek286** [comment]
I want to work on it can you guide me?

**Comment by Jassi10000** [comment]
Can I work on these ?
You can assign me

**Comment by Priya7781** [comment]
hey **I** am new here and I m looking to contribute. You can assign to me
