### ISSUE TITLE
Help on failed test on JUnit5 tests on Ubuntu

### ISSUE THREAD

**Issue by Andreas-White** [TheAlgorithms/Java#2165]
Hello, can someone clarify to me how to handle this issue. I implemented the TimSort algorithm plus the TimSortTest. However, when making the pull request I got a failed test on JUnit5 tests on Ubuntu and JUnit5 tests on Windows and MacOS cancelled. The test class worked fine on my side, also checked the implementation of the other test classes and followed their format. Is there something I could do or something I am missing out.?

**Comment by mk-94** [comment]
Hi, do you have some error-messages?

**Comment by Antwhite420** [comment]
Hello, I present the resulted error messages on the following screenshots
![Screenshot (2)](https://user-images.githubusercontent.com/66181957/114552354-cd4d7400-9c64-11eb-9a28-a306fc8b0270.png)
![Screenshot (3)](https://user-images.githubusercontent.com/66181957/114552380-d5a5af00-9c64-11eb-8824-a128079cbf0f.png)
![Screenshot (4)](https://user-images.githubusercontent.com/66181957/114552394-d9d1cc80-9c64-11eb-8f64-25a1958c6b7a.png)

**Comment by mk-94** [comment]
Branch is ImplTimSort?

**Comment by mk-94** [comment]
First problem is cause of

**Comment by mk-94** [comment]
I fixed the problem and created a pull request to Development-Branch https://github.com/TheAlgorithms/Java/pull/2180

**Comment by Antwhite420** [comment]
Thanks a lot, great help!
