### ISSUE TITLE
Typo In DataStructures/Graphs/BellmanFord.java

### ISSUE THREAD

**Issue by nishantc1527** [TheAlgorithms/Java#2189]
**Is your feature request related to a problem? Please describe.**
Line 7 of [Bellman Ford](https://github.com/TheAlgorithms/Java/blob/master/DataStructures/Graphs/BellmanFord.java#L7) contains a typo where the word vertes should be vertex.

**Describe the solution you'd like**
Change the word vertes to vertex.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/52992695/115127136-fd5c8600-9f88-11eb-9e7f-b5ac0ee18646.png)

**Comment by yanglbme** [comment]
#2190
