### ISSUE TITLE
Add Password Validator

### ISSUE THREAD

**Issue by esparev** [TheAlgorithms/Java#2212]
Validates if the entered password has at least one special character, one number, doesn't have spaces and has more than 5 but less than 20 characters in length.

### Case 1 (Invalid Password):
![image](https://user-images.githubusercontent.com/59494364/119076135-a991f200-b9b7-11eb-819b-66296875d391.png)

### Case 2 (Valid Password):
![image](https://user-images.githubusercontent.com/59494364/119076251-d940fa00-b9b7-11eb-9c5a-122522fcd700.png)

**Comment by anishsaraogi** [comment]
I would like to work on this issue.

**Comment by domonwa1** [comment]
Ok

**Comment by ddiaaz** [comment]
Would these changes be on PasswordGen.java?

**Comment by ddiaaz** [comment]
Would you like these changes on PasswordGen.java?

**Comment by esparev** [comment]
Sure!, why not?

**Comment by ddiaaz** [comment]
@esparev great. For the second case, are we checking if two characters are out of place and correcting it for the user? In other words, does the order of the characters matter?

**Comment by esparev** [comment]
No, the order of the characters don't matter

**Comment by Chprudhvi12** [comment]
Hi @esparev and @ddiaaz ,
Is this issue resolved?
