### ISSUE TITLE
Implimenting Area of Pentagon in Math Pakage 

### ISSUE THREAD

**Issue by SEGRR** [TheAlgorithms/Java#2216]
**Implimenting function to find area of pentagon**

- Function Discription 
 `private static double AreaOfPentagon(double side, double apothem)`

- Parameters 
`double size` - lenght of the side of pentagon
`double apothem` - distance from center of pentagon to any side

- returnns
    `(5/2)*size*apothem`

**Comment by anishsaraogi** [comment]
I will work on it.

**Comment by SEGRR** [comment]
I already did implemented Function
