### ISSUE TITLE
Java Exceptions Issue

### ISSUE THREAD

**Issue by ashishsme14** [TheAlgorithms/Java#2231]
We had given below task, we are not getting what need to be done. Please help us-

![MS 1](https://user-images.githubusercontent.com/61864865/120204083-0c03b180-c246-11eb-9d2c-d5973e2815e1.JPG)
![MS 2](https://user-images.githubusercontent.com/61864865/120204100-10c86580-c246-11eb-938f-f832d89943c5.JPG)
![MS 3](https://user-images.githubusercontent.com/61864865/120204120-1756dd00-c246-11eb-9ae8-c6d08a9e0937.JPG)

import java.util.Scanner;

```
class Validator {
    public static boolean validate(String message) {
        return message.matches("[A-Za-z0-9 ]+");
    }
}

public class Solution {
    private static final Scanner INPUT_READER = new Scanner(System.in);
    
    public static void main(String[] args) {
        String message = INPUT_READER.nextLine();
        
        try {
            String encrypted_message = Encrypter.encryptMessage(message);
            if(! encrypted_message.startsWith("InvalidMessageException"))
                System.out.println(encrypted_message);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
```

**Comment by satyam-sm** [comment]
Hi, Below code will fulfill the requirement kindly check..

//CODE

import java.util.Scanner;

class Validator {
    public static boolean validate(String message) {
        return message.matches("[A-Za-z0-9 ]+");
    }
}
class InvalidMessageException extends Exception {
    String errMsg;
    InvalidMessageException(){ }
    InvalidMessageException(String msg){
        this.errMsg=msg;
    }

    @Override
    public String toString() {
        return "InvalidMessageException: Try again with valid message";
    }
}
class Encryptor {
    public static String encryptMessage(String message) throws InvalidMessageException {
        Validator _v = new Validator();

        if(_v.validate(message)){
            message = message.toLowerCase();
            StringBuilder copyMsg = new StringBuilder(message);
           return copyMsg.reverse().toString();
        }
        throw new InvalidMessageException();

    }
}

public class Solution {
    private static final Scanner INPUT_READER = new Scanner(System.in);

    public static void main(String[] args) {
        String message = INPUT_READER.nextLine();

        try {
            String encrypted_message = Encryptor.encryptMessage(message);
            if(! encrypted_message.startsWith("InvalidMessageException"))
                System.out.println(encrypted_message);
        } catch (InvalidMessageException e) {
            System.out.println(e);
        }
    }
}

**Comment by ashishsme14** [comment]
thanks a lot :-)

can u please help us for 

https://github.com/TheAlgorithms/Java/issues/2230 too
