### ISSUE TITLE
Arithmetic Operations with Matricies

### ISSUE THREAD

**Issue by ddiaaz** [TheAlgorithms/Java#2245]
This program demonstrates arithmetic operations between two matrices. These algorithms are a great tool to learn how multi-dimensional arrays can be used for mathematics. 

![TestCase](https://user-images.githubusercontent.com/76887398/121729784-b4661100-caa3-11eb-989b-5f3510ccb442.PNG)

**Comment by Aayush-Bhatt** [comment]
I want to work on this
