### ISSUE TITLE
看不懂英文

### ISSUE THREAD

**Issue by 11122604** [TheAlgorithms/Java#2261]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by poly000** [comment]
请使用更有意义的issue名

--------------------------------
Please use meaningful issue name

**Comment by xxxolllllllll** [comment]
The guy can not understand English very well.

**Comment by lzw-723** [comment]
It is impolite to force the needs of a small group of people.  As a Chinese, I understand the difficulties of people who are not good at English, but it would be too shameful for Chinese people to leave after leaving a sentence like this.

**Comment by siriak** [comment]
谢谢让我们注意到这个。不幸的是，我们无法将所有内容翻译成中文。
