### ISSUE TITLE
Create Algorithms (BruteForce, DynamicProgramming, Greedy Algorithms) for knapsack problem 

### ISSUE THREAD

**Issue by Johnn222** [TheAlgorithms/Java#2264]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Solving knapsack problem using BruteForce, DynamicProgramming and Greedy Algorithms

**Describe alternatives you've considered**

**Additional context**

**Comment by Rajat-Jain29** [comment]
@Johnn222 I would love to solve this issue . Could you please assign it to me .

**Comment by Rajat-Jain29** [comment]
https://github.com/TheAlgorithms/Java/pull/2281

It has been solved now please merge my PR
