### ISSUE TITLE
Add CheckVowels algorithm into the strings package

### ISSUE THREAD

**Issue by KarChunyip** [TheAlgorithms/Java#2269]
This algorithm should counts how many vowels in one strings.

Strings: "This is a strings"
Result: 4
4 vowels counted.

**Comment by satyam-sm** [comment]
> This algorithm should counts how many vowels in one strings.
> 
> Strings: "This is a strings"
> Result: 4
> 4 vowels counted.

**Very basic approach using JAVA**
```java
public int numberOfVowelsInString(String s){
        int count=0;
        for(int i=0;i<s.length();i++){
            if(s.charAt(i)=='a' ||s.charAt(i)=='e' ||s.charAt(i)=='i' ||s.charAt(i)=='o' ||s.charAt(i)=='u')
                count++;
        }
        return count;
    }
```

**Comment by s0ur4v-d45** [comment]
i have added the algorithm, please check it out
