### ISSUE TITLE
Postfix to Infix using Stack

### ISSUE THREAD

**Issue by KhushiChaudhary744** [TheAlgorithms/Java#2339]
Hey, I am a participant of Hacktoberfest and would like to contribute to this repo.
I already have the solution and need the greenflag to upload it.

**Comment by siriak** [comment]
Hi, the solution to what? Could you share a link to a Wikipedia page about that problem? Thanks

**Comment by ArpitaGupta4086** [comment]
@siriak I'm a Hacktoberfest Participant. I have a good knowledge of Java Programming. Can I please take this up?

**Comment by KhushiChaudhary744** [comment]
Hey so basically I will be converting a postfix expression to infix using stack. Basically the opposite of this https://en.wikipedia.org/wiki/Shunting-yard_algorithm

**Comment by siriak** [comment]
Ok, go ahead!

**Comment by sakshi-tiwari670** [comment]
Input : abc++
Output : (a + (b + c))

Input  : ab*c+
Output : ((a*b)+c)

I have done this problem before .May you plz assign this to me

**Comment by IMPranshu** [comment]
Have you uploaded your code yet?

**Comment by ilaydaozdemir99** [comment]
Hi @siriak if no one did a pr yet can I work on this ?

**Comment by soumya140602** [comment]
hey @siriak shall I do this one.

**Comment by HARDHARSHEYS** [comment]
hey @siriak shall i do this one

**Comment by gauravmali499** [comment]
hey @siriak , the problem is done
if not then can i do it

**Comment by nikslyon19** [comment]
Hi, I'm new to this open source contribution stuff. Thought this would be a nice starting point. If this is still up for grabs, I would like to be assigned this one.

**Comment by aryancharan** [comment]
is this issue is not resolved then then i would like to work  on it
