### ISSUE TITLE
Vertical Traversal of Binary tree

### ISSUE THREAD

**Issue by ishika22** [TheAlgorithms/Java#2344]
**Problem Title**
Printing a Binary Tree in Vertical Order.
**Problem Description**
We will be printing a binary tree in vertical order.
**Sample testcase**
                   
![image](https://user-images.githubusercontent.com/35271444/135576460-b7774bae-d2c1-47b7-83b5-5226d4c27e91.png)

Output: 4,2,1,5,3,6
**Explanation:**
As we can see there are 5 vertical lines which can pass through the tree - 
1st vertical line - 4
2nd vertical line - 2
3rd vertical line - 1,5
4th vertical line - 3
5th vertical line - 6
**Additional Context:**
I have a solution for the above problem. Can this be accepted under the data structure folder!

**Comment by ishika22** [comment]
@siriak can I send a PR for the above problem?

**Comment by siriak** [comment]
Yes, feel free to send it, but I find it difficult to imagine what this would look like. Where could I use your algorithm?
