### ISSUE TITLE
Array Sorting Algorithms in Java

### ISSUE THREAD

**Issue by saloni33** [TheAlgorithms/Java#2348]
I am participating in Hacktoberfest, so I would like to contribute array sorting algorithms under DSA.

**Comment by Shubham56-droid** [comment]
i would like to work o this issue pls assign it to me. I am good with DSA in java

**Comment by Aditya-619** [comment]
hey, can I work on this issue

**Comment by siriak** [comment]
You are free to add new sorting algorithms that are not present here yet (apart from crazy ones like bogo sort)

**Comment by saloni33** [comment]
@siriak  can you tell me to whom you assigned this issue. Kindly assign this issue to me as I created this one.

**Comment by vaishalijain3456** [comment]
Hello,
Will you please assign me this issue as a part of Hacktoberfest?
Thank You!

**Comment by siriak** [comment]
Just write here which algorithm you will implement and that's it. There are many algorithms, so I think all of you can find one for yourself

**Comment by saloni33** [comment]
@siriak  I will give a brief about 5 most used algorithms - 
Merge Sort, Heap Sort, Insertion Sort, Selection Sort, and Bubble Sort.

**Comment by siriak** [comment]
They are all already implemented, see DIRECTORY.md
![image](https://user-images.githubusercontent.com/29201949/135638079-cfd6160d-2014-44b6-ad30-9f350efb3d3d.png)

**Comment by saloni33** [comment]
Okay, so I will work on another issue. Thanks !!
