### ISSUE TITLE
Typo in method name of GenericArrayListQueue

### ISSUE THREAD

**Issue by AbhinandanPadmakarPandey** [TheAlgorithms/Java#2352]
**Description**
1. I think their are some typos in the code file of GenericArrayListQueue in DataStructure. The important one is the name of the method of queue data structure for pulling the elements. It is written as "poll". It should be "pull", I think.
2.  Their are other typos as well in the comments like `<p>` in the first comment of the code. This `<p>` looks like paragraph tag in HTML language which, I think, should not be their.
3. Their should be a full stop just after "(FIFO)" in the first comment.

[Click here](https://github.com/TheAlgorithms/Java/blob/master/DataStructures/Queues/GenericArrayListQueue.java) to see the issues.

**Comment by AbhinandanPadmakarPandey** [comment]
I am happy to resolve this issues.

**Comment by siriak** [comment]
Cool, go ahead!

**Comment by AbhinandanPadmakarPandey** [comment]
Ok

**Comment by AbhinandanPadmakarPandey** [comment]
Done sir, please review my pull request.

**Comment by AbhinandanPadmakarPandey** [comment]
Sorry, by mistake closed this issue.

**Comment by AbhinandanPadmakarPandey** [comment]
Sir, I found another typo in Queues.java file. I will do it to. It is `<p>` tag in comment.
