### ISSUE TITLE
Binary Exponentiation

### ISSUE THREAD

**Issue by PranayChauhan2516** [TheAlgorithms/Java#2355]
**Is your feature request related to a problem? Please describe.**
When dealing with large numbers, we need an efficient algorithm to do exponentiation. As it may take a lot of time to compute large powers.

**Describe the solution you'd like**
Binary exponentiation is based on divide and conquer algorithm.

**Additional context**
Kindly allow me to contribute under DivideAndConquer directory.

**Comment by Samhitha-Jasti** [comment]
I'd like to work on this issue. Kindly assign it to me

**Comment by PranayChauhan2516** [comment]
> I'd like to work on this issue. Kindly assign it to me

Actually I have created the issue so that I can work on it. I need the permission from the owner before I generate a pull request. 
To contribute yourself. First please create your own issue and then wait for it to be assigned to you. Please refer the contribution guidelines.

**Comment by siriak** [comment]
Go ahead and make a PR, @PranayChauhan2516
