### ISSUE TITLE
Reverse a stack [JAVA]

### ISSUE THREAD

**Issue by ishika22** [TheAlgorithms/Java#2364]
**Is your feature request related to a problem? Please describe.**
Reverse a stack without using any extra memory space. 
**Describe the solution you'd like**
Instead of using another stack (additional memory) for reversing, we can use the concept of recursion and achieve the above problem.
**Sample Testcase**
Current stack elements : 1,2,3,4,5
Output: 5,4,3,2,1

**Comment by siriak** [comment]
But using recursion also allocates memory :( Still, feel free to contribute this!

**Comment by ishika22** [comment]
> But using recursion also allocates memory :( Still, feel free to contribute this!

Yes but we will use the in memory stack storage

**Comment by Ayse-Sadioglu** [comment]
I would like to contribute to this issue

**Comment by siriak** [comment]
It's implemented here https://github.com/TheAlgorithms/Java/blob/9fb3364cccc5373c32dbdb661f773c5ee753c77a/src/main/java/com/thealgorithms/others/ReverseStackUsingRecursion.java
