### ISSUE TITLE
Circular queue in java

### ISSUE THREAD

**Issue by KhushiChaudhary744** [TheAlgorithms/Java#2365]
As of now there is no implementation of circular queue. 
I will like to contribute it. 
It will be a simple implementation containing enque, deque etc.

**Comment by prathameshkurunkar7** [comment]
Please assign this issue to me.

**Comment by siriak** [comment]
I think @KhushiChaudhary744 is already working on that. Am I right, @KhushiChaudhary744 ?

**Comment by prathameshkurunkar7** [comment]
Any other issue I can contribute to? Please assign that to me.

**Comment by KhushiChaudhary744** [comment]
Hey, yes I am working on it.
