### ISSUE TITLE
Longest Palindromic Substring in a given string

### ISSUE THREAD

**Issue by sagar-monga** [TheAlgorithms/Java#2376]
Hi,
I have not seen any implementation for the longest palindromic substring in the repo.
I have recently worked on it and would like to share my preceded file.
Could you please assign this issue to me?

**Comment by sagar-monga** [comment]
@siriak I have created a pull request for this issue [here](https://github.com/TheAlgorithms/Java/pull/2379).
Kindly review and merge.

**Comment by sakshi-tiwari670** [comment]
Hello
I have done this question before. May u plz assign this to me  I would like to work on this issue
