### ISSUE TITLE
Check if the string is anagram or not

### ISSUE THREAD

**Issue by AbhinandanPadmakarPandey** [TheAlgorithms/Java#2391]
Hello, I didn't see any program to check if the given string is anagram or not.
Please assign the issue if I am eligible to work on it : ).

**Comment by Sneha421** [comment]
Hello!
I have previously worked on the algorithm for this problem and have coded it using a sliding window, in Python. I have intermediate coding experience in Java and would love to implement the same logic in Java as well. I am very interested in working on this issue!

**Comment by siriak** [comment]
@AbhinandanPadmakarPandey you can implement it

**Comment by AbhinandanPadmakarPandey** [comment]
Roger that :D

**Comment by sakshi-tiwari670** [comment]
@siriak I have done this problem before plz assign this to me sir

**Comment by siddhant2002** [comment]
CanI work under this?.

**Comment by ramdcoder** [comment]
Two strings can be an anagram string if characters of one string contain same characters of another string by regrouping the characters. For example,

String1 = “silent”;
String2 = “listen”;

`
import java.util.Arrays;
public class StringAnagramProgram
{
   public static void main(String[] args)
   {
      String strOne = "Silent";
      String strTwo = "Listen";
      strOne = strOne.toLowerCase();
      strTwo = strTwo.toLowerCase();
      // checking if two strings length are same
      if(strOne.length() == strTwo.length())
      {
         // converting strings to char array
         char[] charOne = strOne.toCharArray();
         char[] charTwo = strTwo.toCharArray();
         // sorting character array
         Arrays.sort(charOne);
         Arrays.sort(charTwo);
         // if sorted character arrays are same then the string is anagram
         boolean output = Arrays.equals(charOne, charTwo);
         if(output)
         {
            System.out.println(strOne + " and " + strTwo + " are anagram.");
         }
         else
         {
            System.out.println(strOne + " and " + strTwo + " are not anagram.");
         }
      }
      else
      {
         System.out.println(strOne + " and " + strTwo + " are not anagram.");
      }
   }
}
`
