### ISSUE TITLE
Number of Triples

### ISSUE THREAD

**Issue by erickcernarequejo** [TheAlgorithms/Java#2405]
Write a program that reads an array of ints and outputs the number of "triples" in the array.

A "triple" is three consecutive ints in increasing order differing by 1 (i.e. ```3,4,5``` is a triple, but ```5,4,3``` and ```2,4,6``` are not).
```
Sample Input:
6
1 2 4 5 6 7

Sample Output:
2

Sample Input:
6
1 4 7 5 4 3

Sample Output:
0
```

**Comment by Mann-tech13** [comment]
Can I work on this issue?

**Comment by Gaurika-Gupta** [comment]
Hello, I am a student and learning Java and want to work on this Issue. Please Assign me this issue.

**Comment by siriak** [comment]
Hi, does this problem have a well-known name and a Wikipedia page? If no, I don't think we'd want to include it

**Comment by Gaurika-Gupta** [comment]
> Hi, does this problem have a well-known name and a Wikipedia page? If no, I don't think we'd want to include it

I don't know.
