### ISSUE TITLE
efficient algorithm that searches for a value in an m x n matrix(sorted in increasing order)

### ISSUE THREAD

**Issue by ojasjain24** [TheAlgorithms/Java#2429]
**Is your feature request related to a problem? Please describe.**
Write an efficient algorithm that searches for a value in an m x n matrix. This matrix has the following properties:
1. Integers in each row are sorted from left to right.
2. The first integer of each row is greater than the last integer of the previous row.

Its a leetcode problem : https://leetcode.com/problems/search-a-2d-matrix/

**Describe the solution you'd like**
My algorithm has time complexity of o(n) and finishes in 0ms. In this algorithm, we will iterate to first element of each row, if the given number is smaller then this element, then our number will be in above row. Then we will iterate in that above row and if number is present then we will return true else false.

**Comment by siriak** [comment]
Hi, a simple binary search with some arithmetics can be used to solve that in the most efficient manner, so I don't think it's worth including this algorithm separately
