### ISSUE TITLE
Swapping array elements without extra variable

### ISSUE THREAD

**Issue by xtreme-uz** [TheAlgorithms/Java#2436]
**Is your feature request related to a problem? Please describe.**
Small optimizations in the algorithm can lead to large results, for example, when sorting an array, the values are changed and additional memory is required. How to get rid of this extra memory? 

**Describe the solution you'd like**
To swap values without additional memory:
a = 4, b = 7
1)  a = a + b  ==>  a = 11, b = 7
2)  b = a - b   ==>  a = 11, b = 4
3)  a = a - b   ==>  a = 7,   b = 4

**Comment by Vaishnavi-Markunde** [comment]
Hello ,I know the solution and  I would like to work on this issue .

**Comment by xtreme-uz** [comment]
Vaishnavi-Markunde:
Ouh sorry man, I am just following Contribution.md, MR already created.

**Comment by sakshi-tiwari670** [comment]
I know the solution for this please assign this to me
