### ISSUE TITLE
 Sort a Linked List

### ISSUE THREAD

**Issue by excellant-luck** [TheAlgorithms/Java#2450]
Given the head of a linked list, return the list after sorting it in ascending order.

Solution:
A divide and conquer algorithm similar to merge sort used in case of arrays. The linked list is recursively broken down to smaller lists and then sorted after which they are merged, thereby sorting the original linked list.

**Comment by irohitsatya** [comment]
Can I please work on this and raise a PR?

**Comment by saketmundra** [comment]
Can I please work on this and raise a PR for hacktoberfest 2021?

**Comment by reyhhan** [comment]
Do I need to be assigned to work on an issue?

**Comment by siriak** [comment]
Not at all, but other people might be working on it too and it's better to work on something else if you know someone is already working here

**Comment by siddhant2002** [comment]
Can I work under this issue??

**Comment by VedantNaik21** [comment]
is this issue still open open or has it been sorted since I see someone used 'fixes' in one of the previous commits. if it is open can I work on it?

**Comment by siddhant2002** [comment]
Actually I'm currently working under it. Thanks.

**Comment by soumya140602** [comment]
can I do on this

**Comment by dave-sh** [comment]
Can I work on this issue?

**Comment by siddhant2002** [comment]
This issue is already merged. Thanks.
