### ISSUE TITLE
Implementation of  detection of Linked list cycle 

### ISSUE THREAD

**Issue by shraddhavp** [TheAlgorithms/Java#2455]
@siriak  can you please assign this issue to me ?

**Comment by unfixedbug** [comment]
do we need to detect cycles or implement a circular likedlist?
@siriak

**Comment by talhaarshad7** [comment]
Hey i can work upon this.

**Comment by siriak** [comment]
@unfixedbug it's up to you, both are useful (if they are not implemented yet)
