### ISSUE TITLE
Check validation of an IP Address.

### ISSUE THREAD

**Issue by Simran1604** [TheAlgorithms/Java#2466]
**Is your feature request related to a problem? Please describe.**
Check if a given string is a valid IP address or not.

**Describe the solution you'd like**
I'd like to use simple and efficient concepts of Strings to solve this problem.

**Describe alternatives you've considered**
I think the above approach would work so I don't have an alternative as of now.

**Example**
Input: 6665..555
Output: Not a valid IP Address.

Input: 333.111.111.111
Output: It is a valid IP Address.

**Please assign me this issue.**

**Comment by siriak** [comment]
333.111.111.111 is not a valid IPv4 address

**Comment by Simran1604** [comment]
Pardon, my bad.
It should have been 222.111.111.111

**Comment by siriak** [comment]
No need for such validation, it's really simple
