### ISSUE TITLE
Three Sum Problem

### ISSUE THREAD

**Issue by Sneha421** [TheAlgorithms/Java#2467]
**Problem Statement**: Given an array and a target sum, find all possible triplets in that array, that add up to the target sum

**Input**: Array and a Target sum
**Output**: List of all possible triplets that add up to the target sum

![image](https://user-images.githubusercontent.com/57147597/135790725-6ab4c26f-ea39-40cb-aaf1-33e7f2d48d35.png)
***The solution must not contain duplicate triplets***

**Comment by Sneha421** [comment]
There are three methods to solve this problem
1. Three for loops --> O(n^3) time | O(1) space
2. HashMap --> O(n^2) time | O(n) space
3. Three-pointers --> O(n^2) time | O(1) space

I have solved this problem with all three algorithms before and would like to take it up again to make a meaningful contribution to this repository.

**Comment by ApoorvaKaushal09** [comment]
I would like to work on this issue, please assign it to me and consider it for Hacktoberfest.

**Comment by sakshi-tiwari670** [comment]
I can do this problem by the help of pair sum problem
