### ISSUE TITLE
Two Sum Problem

### ISSUE THREAD

**Issue by Sneha421** [TheAlgorithms/Java#2469]
**Problem Statement**: Given an array and a target sum, find a pair of numbers from the array that add up to the target sum.
Assume that not more than one such pair exists in the given array.

**Input**: Array and a Target sum
**Output**: The pair that adds up to the target sum

![image](https://user-images.githubusercontent.com/57147597/135793769-76985659-d9e7-425a-8bf7-bd166197120d.png)
_**There is always exactly one solution**_

**Comment by Sneha421** [comment]
This problem has three ways different approaches
1. Two for loops --> O(n^2) time | O(1) space
2. HashMap --> O(n) time | O(n) space
3. Two pointers --> O(n) time | O(1) space

**Comment by Sneha421** [comment]
This problem has three ways different approaches

Two for loops --> O(n^2) time | O(1) space
HashMap --> O(n) time | O(n) space
Two pointers --> O(n) time | O(1) space

I have previously worked on all three approaches and would like to work on them yet again for this repository

**Comment by AshishG97** [comment]
please assign this issue to me

**Comment by susheel-kumar-1998** [comment]
I would like to contribute to this issue using hashmap in java.

**Comment by sakshi-tiwari670** [comment]
I can do this using HashMap as well as Two pointer algorithm. I would love to work on this . Please assign this to me
