### ISSUE TITLE
A Divide and Conquer implementation of finding the Minimum and maximum in an array is missing.

### ISSUE THREAD

**Issue by thecoderenroute** [TheAlgorithms/Java#2481]
Finding the min and max elements in an array is one of the most basic applications of the Divide and Conquer approach, I would like to add that.

**Comment by asiriak** [comment]
I wouldn't use divide & conquer for that, way too complex and inefficient for a task where linear search would suffice, but thanks for suggesting!

**Comment by siriak** [comment]
I wouldn't use divide & conquer for that, way too complex and inefficient for a task where linear search would suffice, but thanks for suggesting!
