### ISSUE TITLE
Reverse a given linked list.

### ISSUE THREAD

**Issue by Simran1604** [TheAlgorithms/Java#2485]
**Is your feature request related to a problem? Please describe.**
I would like to add the code for reversing a given linked list.

**Describe the solution you'd like**
By changing the previous and current pointers pointing at a node, this can be achieved very smoothly.

**Describe alternatives you've considered**
I would provide the algorithm as well as the code with output for better understanding.

**Please assign me this issue and consider it for the Hacktoberfest 2021**
Thank you.

**Comment by siriak** [comment]
That's a simple thing to do, we don't need an example here, thanks!
