### ISSUE TITLE
Find matrix multiplication in optimised way

### ISSUE THREAD

**Issue by harshika18** [TheAlgorithms/Java#2488]
**Is your feature request related to a problem? Please describe.**
As we know the time complexity of multiplication of two n x n square matrices is O(n^3) using brute force method. We can optimise it and do it in better time complexity of O(n^2.80).

For example:
let the first matrix be:
2 3 1 6
4 0 0 2
4 2 0 1
0 3 5 2

let the second matrix be: 
3 0 4 3
1 2 0 2
0 3 1 4
5 1 3 2
 
Output(Multiplication of matrices A and B):
39 15 27 28
22 2 22 16
19 5 19 18
13 23 11 30

**Describe the solution you'd like**
I would like to implement Strassen Algorithm which is based on divide and conquer to reduce the number of recursive calls. 

Can I work on this algorithm, please assign this to me.
Thank you

**Comment by veerbhadrasolanki** [comment]
Hi,  please assign this to me.

**Comment by siriak** [comment]
Done in https://github.com/TheAlgorithms/Java/pull/2490
