### ISSUE TITLE
Binary Tree Maximum Path Sum

### ISSUE THREAD

**Issue by DeeptiShahi** [TheAlgorithms/Java#2497]
**Problem Statement** : Given the `root` of a Binary Tree, return the maximum **_path sum_** of any path. Path Sum is the sum of node values along a path. 

**Input** : Root `Node` Object
**Output** : Integer value
-1000 <= Node.val <= 1000

**Example** 
![Untitled](https://user-images.githubusercontent.com/28200286/136089007-c25795f1-f75b-460c-be76-4d2c4858dff8.png)

`Input : [1, 2, 3, 4]`
`Output : 10`

**Approach** : I have worked on this problem before using **simple recursion** and would like to contribute the same to this repository. Please assign this issue to me!

**Comment by siriak** [comment]
[1, 2, 3, 4] is not a path because there's no edge between 2 and 3

**Comment by siriak** [comment]
![image](https://user-images.githubusercontent.com/29201949/136147343-bf8bff6b-8c47-4e4e-8d36-873ee777e980.png)
![image](https://user-images.githubusercontent.com/29201949/136147354-0203d11b-afae-458b-b3cc-4d053c98e3b3.png)
So what is actually an input? Root node or path?

**Comment by DeeptiShahi** [comment]
Input is Root node, which will be node object with value 1.
I have written the preorder list of this tree in input just to show the tree formed with the root node. Input will not look like this.

**Comment by cypherBeep** [comment]
heya, can you assign this to me?
