### ISSUE TITLE
How many sentences can be created by replacing any word with one of its anagrams

### ISSUE THREAD

**Issue by divyanshutw** [TheAlgorithms/Java#2506]
**Is your feature request related to a problem? Please describe.**
Given an array of words and an array of sentences. Some words are anagrams of each other in the given array of words. Calculate how many sentences can be created by replacing any word with one of its anagrams.

Constraints:
 - 0<n<=10^5                                         //Number of words
 - 1<=length of each word<=20
 - 1<=m<=1000                                     //Number of sentences
 - 3<=words in a sentence<=20

Anagram: Two words are said to be anagrams of each other if one word can be formed by rearranging the letters in the other word.

Example:

Input:
n=4                                             //Number of words
m=1                                            //Number of sentences
words = {"listen","silent","it","is"}
sentences = {"listen it is silent"}

Output: 4

Explanation: 
Anagrams: "listen" and "silent"
The four sentences possible by replacing words with their anagrams are:
 - listen it is silent
 - listen it is listen
 - silent it is listen
 - silent it is silent

So 4 possibilities are there.

**Describe the solution you'd like**

Algorithm:
 - Create a Hashmap and store the no. of anagrams of each word given in words array.
 - For this, run two loops and check that string with all other strings. With some optimization, we can do it in slightly less than O(n^2).
 - Now for each sentence, find all words.
 - For all words, do: count=count*anagrams(word)

Time complexity:
Time for calculating number of anagrams of each word: O(n^2)     where n is the number of words in the words array
Time for calculating number of possibilities for a string: O(k)      where k is the length of a string
Time for calculating number of possibilities for all strings: O(m*k)     where m is the number of sentences inputted
Total time complexity: O(n^2 + m*k)

**Describe alternatives you've considered**
This question can be added in strings section.

**Additional context**
None

Kindly assign me this issue
Thanks

**Comment by siriak** [comment]
Thanks for suggesting that, but it's not a well-known and used algorithm, so I think we shouldn't include it
