### ISSUE TITLE
ShortestCommonSuperSequence Length

### ISSUE THREAD

**Issue by kmadhav907** [TheAlgorithms/Java#2515]
Given two Strings X, Y print the shortest common SuperSequence Length of those Strings
The idea behind is to find the LCS of those strings and returning len(X) + len(Y) - lcs(X, Y)
For eg:
 String X = "AGGTAB";
 String Y = "GXTXAYB";

Function(X , Y) should return 9

#2516 is Pull request

@siriak could you please review it 
Thank you :)

**Comment by siriak** [comment]
Closed by #2516
