### ISSUE TITLE
Implement Swap-Sort algorithm.

### ISSUE THREAD

**Issue by Flonator3000** [TheAlgorithms/Java#2520]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The solution is a complete implementation of the swap-sort algorithm.

**Describe alternatives you've considered**

**Additional context**
Swap-Sort is a sorting algorithm that sorts an array of pairwise different numbers.

**Comment by Flonator3000** [comment]
PR is already created. #2523

**Comment by siriak** [comment]
Implemented
