### ISSUE TITLE
Print the key mappings for old Nokia mobile keys combination

### ISSUE THREAD

**Issue by kushsharma1001** [TheAlgorithms/Java#2535]
### Problem Statement: Print the key mapping permutations for old Nokia mobile keys combination.

Input: 1
Output: abc
Explanation: Key '1' on old Nokia keypad corresponds to abc
<img width="324" alt="nokia keypad" src="https://user-images.githubusercontent.com/22798697/136446832-f04d64e9-1bc7-4da5-946d-ecec72be65eb.png">

Input: 21
Output: da db dc ea eb ec fa fb fc
Explanation: Pressing key '2' and then key '1' on old Nokia keypad gives permutations of da db dc ea eb ec fa fb fc

**Comment by siriak** [comment]
We don't need that, thanks
