### ISSUE TITLE
Design Browser History

### ISSUE THREAD

**Issue by hardikkhanna** [TheAlgorithms/Java#2564]
**Is your feature request related to a problem? Please describe.**
This is a Low Level Design question from Leetcode and the problem is as follows:

You have a browser of one tab where you start on the homepage and you can visit another url, get back in the history number of steps or move forward in the history number of steps.

**Describe the solution you'd like**
Solution here would be to use a DoublyLinkedList and maintain the previous and forward history.

**Additional context**
Implement the BrowserHistory class:

1. BrowserHistory(string homepage) Initializes the object with the homepage of the browser.
2. void visit(string URL) Visits URL from the current page. It clears up all the forward history.
3. string back(int steps) Move steps back in history. If you can only return x steps in the history and steps > x, you will return only x steps. Return the current URL after moving back in history at most steps.
4. string forward(int steps) Move steps forward in history. If you can only forward x steps in the history and steps > x, you will forward only x steps. Return the current URL after forwarding in history at most steps.

I would like to work on the solution, @siriak  Kindly assign me this issue.

Thanks.

**Comment by siriak** [comment]
Hi, we don't add solutions from leetcode because they are just applications of existing algorithms (using doubly linked list)
