### ISSUE TITLE
Unhandled exception EmptyStackException in QueueUsingTwoStacks.java

### ISSUE THREAD

**Issue by aitorfi** [TheAlgorithms/Java#2605]
**Describe the bug**
The program should print "null" to show that the inStack is empty but instead the program crashes when trying to access an element of the empty stack.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/64830228/137192355-6e00fe4e-78a6-4c19-a998-bdf029ca3d41.png)
![imagen](https://user-images.githubusercontent.com/64830228/137192023-20b5a4f2-765b-42b8-a023-5d78a10c9da1.png)
![imagen](https://user-images.githubusercontent.com/64830228/137192145-334e1d7f-9c1a-466e-9598-38d60c1d2c67.png)

**Comment by siriak** [comment]
This is expected behavior because Peek should return the element at the top of the stack, but there isn't any. This is consistent with other implementations like https://docs.oracle.com/javase/7/docs/api/java/util/Stack.html#peek()
