### ISSUE TITLE
Affine Cipher

### ISSUE THREAD

**Issue by kumanoit** [TheAlgorithms/Java#2620]
**Is your feature request related to a problem? Please describe.**
As per wikipedia "The affine cipher is a type of monoalphabetic substitution cipher, where each letter in an alphabet is mapped to its numeric equivalent, encrypted using a simple mathematical function, and converted back to a letter."
This request is to add encryption and decryption algorithm for Affine Cipher.

**Describe the solution you'd like**
It's an implementation of an existing algorithm. So I'll implement as per the documentation.

**Describe alternatives you've considered**
None

**Additional context**
[Wikipedia](https://en.wikipedia.org/wiki/Affine_cipher#:~:text=The%20affine%20cipher%20is%20a,converted%20back%20to%20a%20letter.&text=As%20such%2C%20it%20has%20the%20weaknesses%20of%20all%20substitution%20ciphers.)

**Comment by kumanoit** [comment]
I am interested in this.

**Comment by diallocheikh007** [comment]
I’m interested in this
