### ISSUE TITLE
Sorting Stack Implementation

### ISSUE THREAD

**Issue by skmodi649** [TheAlgorithms/Java#2658]
**Is your feature request related to a problem? Please describe.**
Add an easy and efficient way of sorting a stack such that greatest element is at the top of stack

**Describe the solution you'd like**
The following approach will make use of Recursion to sort the stack of size n.
Problem description , time complexity and Test cases will be provided as comments in the file
As a part of Hacktoberfest 2021, I would love to add this feature in the codebase.
Can you please assign this to me @siriak 

**Additional context**
Here are the test cases screenshots for reference : 

![1](https://user-images.githubusercontent.com/76468931/137613393-e6f8c5aa-aa5c-4785-a69e-296436dbfbbd.png)

![2](https://user-images.githubusercontent.com/76468931/137613396-b4a82c96-d02f-4723-a97c-86019ab584b7.png)

**Comment by skmodi649** [comment]
Please add the Hacktoberfest label

**Comment by siriak** [comment]
Don't need this algorithm, thank you
