### ISSUE TITLE
Add NthGeekOnacciNumber

### ISSUE THREAD

**Issue by skmodi649** [TheAlgorithms/Java#2695]
**Is your feature request related to a problem? Please describe.**
Add an easy and efficient method of finding Nth [Geek Onacci Number](https://world-technews.com/2021/03/02/geek-onacci-number-geeksforgeeks/)

**Describe the solution you'd like**
Code will use the concept of Recursion to find the desirable result. Description , algorithm , test cases with explanation and time complexity will be provided as comments in the file.

**Additional context**
Screenshots of Test Cases for reference :

![2](https://user-images.githubusercontent.com/76468931/138129792-5a080b12-af65-4391-8af2-0b56b532cf0a.png)

![1](https://user-images.githubusercontent.com/76468931/138129813-739c989a-6f35-4144-87e3-eab42501f041.png)

Can you assign me this issue @siriak

**Comment by siriak** [comment]
Hi, we don't need this algorithm since it's almost the same as for Fibonacci numbers and not very popular, thanks!
