### ISSUE TITLE
Rabin-Karp issue

### ISSUE THREAD

**Issue by bmskyline** [TheAlgorithms/Java#2769]
**Describe the bug**
Rabin-Karp return wrong answer

**To Reproduce**
test rabin karp with string : aaaaaaaaaaaa and pattern aaaaaa
it print only index 0

**Expected behavior**
print index : 0,1,2,3,4,5,6

**Comment by siriak** [comment]
There are different versions of this algorithm: one that returns all occurrences and another one that returns only the first occurrence. You are welcome to implement the former version :)
