### ISSUE TITLE
String Compare 

### ISSUE THREAD

**Issue by ersaurabhgarg89** [TheAlgorithms/Java#2820]
I cannot see anything related to String comparison under String folder of this project. Can you please assign this to me?

**Comment by siriak** [comment]
What do you mean by string comparison?

**Comment by siddhant2002** [comment]
Can I work under this topic?

**Comment by siriak** [comment]
@siddhant2002 sure, just explain what you intend to implement

**Comment by siddhant2002** [comment]
@siriak I'll share some java codes relating to different types of compare functions., comparators and comparables.

**Comment by siriak** [comment]
It's still not clear what algorithms you'll contribute, but just make a PR and I'll review it :)

**Comment by siddhant2002** [comment]
ok thanks.

**Comment by ArpitaAnindita** [comment]
Can I work under this issue

**Comment by siriak** [comment]
Close as won't do
