### ISSUE TITLE
Flood fill fills diagonally & errors if edges are to be filled

### ISSUE THREAD

**Issue by appgurueu** [TheAlgorithms/Java#2836]
https://github.com/TheAlgorithms/Java/commit/1f17076571ec929c7fb8475ef1bd671b07d44138
It:
1. Fills diagonally, which isn't how flood fill usually works;
2. Lacks a check for `x < width && y < height`: I assume it crashes if that happens (with an AIOOB Ex.)

**Comment by siriak** [comment]
IMO filling diagonally is fine, it's one of the ways it can be implemented. As for the check, could you fix that and maybe add a test for that?

**Comment by appgurueu** [comment]
What the heck, issues don't resolve themselves. The bot should be disabled.

**Comment by NewPZP** [comment]
I think  the code following is not the right implementation,

https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/datastructures/lists/SinglyLinkedList.java

/**
     * Swaps nodes of two given values a and b.
  *
     */
    public void swapNodes(int a, int b) {
        Node currentNode = head;
        Node temp = null;
        while (currentNode != null) {
            if (currentNode.next.value == a) {
                temp = currentNode.next;
            }
            if (currentNode.next.value == b) {
                currentNode.next = temp;
            }
            currentNode = currentNode.next;
        }
    }

    /**

**Comment by nikslyon19** [comment]
Should this not be categorised as a Backtracking problem, rather than dynamic programming?

**Comment by appgurueu** [comment]
> Should this not be categorised as a Backtracking problem, rather than dynamic programming?

Flood fill is indeed often categorized as backtracing. That's a different issue though: This issue is about a possible crash in the implementation.

**Comment by nikslyon19** [comment]
> Flood fill is indeed often categorized as backtracing. That's a different issue though: This issue is about a possible crash in the implementation.

Agreed. The corner case is not covered for the function going beyond the dimensions of the 2D array.
In the example given in the code, if you were to replace '3' with '1' at any of the right/bottom most position where it is adjacent to '1', you will get index out of bounds exception.

**Comment by nikslyon19** [comment]
> IMO filling diagonally is fine, it's one of the ways it can be implemented. As for the check, could you fix that and maybe add a test for that?

Since this issue is still unresolved for months, would be happy to take over this one.

Would be covering the missing corner case, add a few test cases (asserts I believe?), and if it's okay, would like to move this code under the backtracking directory/category.
