### ISSUE TITLE
Code Implementation links giving "404" error

### ISSUE THREAD

**Issue by Tejas-Teju** [TheAlgorithms/Java#2840]
**Description**
Code implementation links of algorithms when opened are giving 404 error. I observed it for Bubble sort and Binary search not sure  of rest of the algorithms.

**To Reproduce**
1. Go to [https://the-algorithms.com/algorithm/bubble-sort](url)
2. Scroll down to Code Implementation links
3. Click on Java, Go etc

**Expected behavior**
It should direct us to the right file on GitHub.

**Comment by siriak** [comment]
I've opened an issue in relevant repo https://github.com/TheAlgorithms/website/issues/142, please follow up there
