### ISSUE TITLE
Prettify code action failing

### ISSUE THREAD

**Issue by siriak** [TheAlgorithms/Java#2848]
The prettify code action is failing with "Error:  No parser could be inferred for file: src/main/java/com/thealgorithms/audiofilters/IIRFilter.java" error. Could someone look into that?

**Comment by siriak** [comment]
Currently I think of running it daily on master once it's fixed

**Comment by skmodi649** [comment]
Hey @siriak , I want look into this bug, I might be able to resolve this!

**Comment by 22aam** [comment]
can you tell me what is going on with the code

**Comment by siriak** [comment]
This is an open issue since I didn't have time to fix it yet

**Comment by 22aam** [comment]
can i help with the code

**Comment by 22aam** [comment]
what can of code is it

**Comment by siriak** [comment]
It seems that this plugin is no longer supported, so I'm closing this issue
