### ISSUE TITLE
Add select random node in the Linked List

### ISSUE THREAD

**Issue by skmodi649** [TheAlgorithms/Java#2850]
**Is your feature request related to a problem? Please describe.**
Add an easy and efficient code for finding the *Random Node in given linked list*

**Describe the solution you'd like**
Code will be based upon the concept of  *Randomized algorithm* and *Random number generator*. Proper description , algorithm , test cases and time complexity will be provided as comments in the file.

**Additional context**
Screenshots of result for reference :
![pehla](https://user-images.githubusercontent.com/76468931/143777004-5f1841f6-1c8a-4022-a529-b43c03f4e0e4.png)

![doosra](https://user-images.githubusercontent.com/76468931/143777018-882bbdfc-a9e6-46f9-a753-3853d3fca28c.png)

Can you please assign me this issue @siriak

**Comment by yanglbme** [comment]
#2851
