### ISSUE TITLE
Euler’s Totient Function

### ISSUE THREAD

**Issue by itsAkshayDubey** [TheAlgorithms/Java#2855]
Hi,
I have not seen any implementation of [Euler’s Totient Function](https://en.m.wikipedia.org/wiki/Euler%27s_totient_function) in this repo.
Could you please assign this issue to me?

**Comment by siriak** [comment]
It's here https://github.com/TheAlgorithms/Java/blob/9fb3364cccc5373c32dbdb661f773c5ee753c77a/src/main/java/com/thealgorithms/others/EulersFunction.java
