### ISSUE TITLE
Happy Number Implementation

### ISSUE THREAD

**Issue by itsAkshayDubey** [TheAlgorithms/Java#2857]
Hi,
I have not seen any implementation of [Happy Number](https://en.m.wikipedia.org/wiki/Happy_number) in this repo.
Could you please assign this issue to me?

**Comment by siriak** [comment]
They are implemented here https://github.com/TheAlgorithms/Java/blob/e488b7b5bb3f7c48591d084bbd5e12674df362f9/src/main/java/com/thealgorithms/others/HappyNumbersSeq.java
