### ISSUE TITLE
Find a loop in a LinkedList

### ISSUE THREAD

**Issue by shivkushwaha1511** [TheAlgorithms/Java#2861]
There is no code and algo present in repo related to finding loop in a LinkedList, I like to add it, please assign it to me

**Comment by siriak** [comment]
It's here https://github.com/TheAlgorithms/Java/blob/9fb3364cccc5373c32dbdb661f773c5ee753c77a/src/main/java/com/thealgorithms/datastructures/lists/CreateAndDetectLoop.java
