### ISSUE TITLE
Maximum Subarray Sum

### ISSUE THREAD

**Issue by Ayse-Sadioglu** [TheAlgorithms/Java#2862]
Hi,
I have not seen any implementation of Maximum Subarray Sum with divide and conquer algorithm in this repository.
Could you please assign this issue to me?

**Comment by Ayse-Sadioglu** [comment]
I have requested a PR for Maximum Subarray Sum with divide and conquer algorithm

**Comment by siddhant2002** [comment]
Can I work under this issue?

**Comment by siriak** [comment]
Not sure, @Ayse-Sadioglu is probably implementing it at the moment

**Comment by Ayse-Sadioglu** [comment]
I am currently working on it.
