### ISSUE TITLE
Pascal's Triangle

### ISSUE THREAD

**Issue by iamhardikat11** [TheAlgorithms/Java#2864]
I can't find printing the entire Pascal's Triangle (up to Nth Line) in the implementation of Algorithms in the (Java/math Section). Please @siriak Assign this Feature Request to me. Thank You.

**Comment by tamsiuloong** [comment]
我已经收到你的邮件，我尽快给你回复

**Comment by iamhardikat11** [comment]
Sure, Thank You.

**Comment by iamhardikat11** [comment]
Can I make a PR?

**Comment by siriak** [comment]
Could you return it as an array of arrays or something like that? It's better than printing

**Comment by klemanAssassinParts** [comment]
Elevator parts with klemens quality
https://keleman.org/

**Comment by klemanAssassinParts** [comment]
[Buy elevator parts](https://keleman.org/)

**Comment by siddhant2002** [comment]
Can I work under this issue?
