### ISSUE TITLE
project does not compile on mac

### ISSUE THREAD

**Issue by deepansha16** [TheAlgorithms/Java#2870]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Specification**

**Additional context**
<img width="602" alt="Screenshot 2021-12-08 at 7 28 48 PM" src="https://user-images.githubusercontent.com/49023785/145263730-27a2b29a-f30b-48ba-8da6-5ba0b701c940.png">

**Comment by siriak** [comment]
Thanks for reporting, which version of Java are you using? And which compiler?

**Comment by deepansha16** [comment]
I am using java 11 and IntelliJ for compiling the project

**Comment by siriak** [comment]
Have you tried compiling with Java 17? It's the version we use in https://github.com/TheAlgorithms/Java/blob/master/pom.xml and in the CI pipeline.
