### ISSUE TITLE
Swap Case

### ISSUE THREAD

**Issue by s-devran** [TheAlgorithms/Java#2874]
I have seen Lower.java and Upper.java classes in your string directory.

I would like to add a SwapCase class to swap the cases of letters in a given string which means switching the uppercases to lowercases, and lowercases to uppercases.

**Comment by siriak** [comment]
Thanks for suggesting, I've just checked Lower.java and it seems a bit too simple and not really an algorithm in the required sense. We'll probably remove it in the nearest future, so no need to add SwapCase as it's very similar, thanks!
