### ISSUE TITLE
Kaprekar Number

### ISSUE THREAD

**Issue by s-devran** [TheAlgorithms/Java#2878]
KaprekarNumbers class checks whether a given number is Kaprekar Number or not.

**Comment by mgncodes** [comment]
Hi, I'd like to contribute to this issue.

**Comment by s-devran** [comment]
Hello,
I have requested a PR for KaprekarNumbers.

**Comment by s-devran** [comment]
Hello,
I added KaprekarNumbers class and requested a PR.
Could you please check my PR?
