### ISSUE TITLE
Add NewManShanks Algorithm

### ISSUE THREAD

**Issue by uditkhanna112** [TheAlgorithms/Java#2885]

**Comment by Deeeeksha** [comment]
In mathematics, a Newman–Shanks–Williams prime (NSW prime) is a prime number p which can be written in the form: 

{\huge S_{2m+1} = \frac{ {(1+\sqrt{2})^{2m+1} + (1-\sqrt{2})^{2m+1} } }{2} }      

We can implement this approach by DP Approach.
