### ISSUE TITLE
Random Node in Binary tree

### ISSUE THREAD

**Issue by skmodi649** [TheAlgorithms/Java#2893]
**Is your feature request related to a problem? Please describe.**
Add an easy and efficient code for finding the *Random Node in the given Binary Tree*

**Describe the solution you'd like**
Code will be based upon the concept of *Randomized algorithms* , *Random number generator*. Proper description, algorithm, explanation, test cases and time complexity will be provided as comments in the file.

**Additional context**
Screenshots of test cases for reference :
![1](https://user-images.githubusercontent.com/76468931/147970946-8c09a3e5-a9e3-4923-aad4-8f1209a9cd7d.png)

![2](https://user-images.githubusercontent.com/76468931/147970964-d1dc1ac3-afcf-4e0b-a37e-7d0efda0ac5c.png)

Can you please assign me this issue!

**Comment by siriak** [comment]
Is it a well-known algorithm that you want to add? If not, I don't think it's worth doing since I don't see a use case for that

**Comment by skmodi649** [comment]
Its a well known algorithm.
It is used in cryptography , Load balancing , finding shortest paths and minimum spanning trees.

**Comment by Xuewei-Chen** [comment]
Can I work on this as well?

**Comment by skmodi649** [comment]
> Can I work on this as well?

Actually I made the pull request and it got merged as well, so sorry!
