### ISSUE TITLE
Adding vector functions (dot product, cross product, and area/volume of parallelograms, cubes)

### ISSUE THREAD

**Issue by KellerBonnett** [TheAlgorithms/Java#2912]
I am taking an intro to software engineering course in college and need to contribute to a repo on github, I was hoping it would be ok to contribute to and add these vector functions under algorithms.

Test case:
int[] vector1 = new int[]{1,0,1};
int[] vector2 = new int[]{1,1,1};
int [] result = crossProduct(vector1, vector2);
result would store {-1,0,1}

**Comment by siriak** [comment]
Hi, the cross product is already implemented here https://github.com/TheAlgorithms/Java/blob/9fb3364cccc5373c32dbdb661f773c5ee753c77a/src/main/java/com/thealgorithms/maths/VectorCrossProduct.java. Feel free to implements something different though :)
