### ISSUE TITLE
Maximum  subarray in linear time

### ISSUE THREAD

**Issue by subhroblkbox** [TheAlgorithms/Java#2915]
**Is your feature request related to a problem? Please describe.**
Maximum subarray problem can be solved in Linear order of time and space. I would like to add that.

**Describe the solution you'd like**
Basically when we calculate max sum of an subarray we check which is greater `ar[i..j]` or `a[j]`. This can be solved in linear time.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Antonio-Villarreal** [comment]
Hey can I try this issue?

**Comment by siriak** [comment]
This is already implemented here https://github.com/TheAlgorithms/Java/blob/9fb3364cccc5373c32dbdb661f773c5ee753c77a/src/main/java/com/thealgorithms/dynamicprogramming/KadaneAlgorithm.java
