### ISSUE TITLE
LinkedList Cycle detection

### ISSUE THREAD

**Issue by subhroblkbox** [TheAlgorithms/Java#2920]
**Is your feature request related to a problem? Please describe.**
Given a linked list. Determine if the linked list has a cycle in it.

**Describe the solution you'd like**
We can use hare and tortoise algorithm to solve that in linear time

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by alvint5** [comment]
Could I get this issue assigned to me?

**Comment by siriak** [comment]
This algorithm is already implemented here https://github.com/TheAlgorithms/Java/blob/9fb3364cccc5373c32dbdb661f773c5ee753c77a/src/main/java/com/thealgorithms/datastructures/lists/CreateAndDetectLoop.java
