### ISSUE TITLE
Regex section

### ISSUE THREAD

**Issue by subhroblkbox** [TheAlgorithms/Java#2926]
**Is your feature request related to a problem? Please describe.**

we can make this repo better if we have a regex section where like we can document how to use regex, from basic (word detection) to advance (how to create a dfa from regex).
**Describe the solution you'd like**

I am not sure about the implementation so I need some more people to comment on this idea.
**Describe alternatives you've considered**

**Additional context**

**Comment by siriak** [comment]
Well, this repo is focused on algorithms and I'm not sure if regex are somehow related to algorithms. It's a powerful tool for sure, but we're focused on different things here. I'm sure there are plenty of great resources about regex on the internet. Thanks for suggesting anyway!
