### ISSUE TITLE
Combination

### ISSUE THREAD

**Issue by cpiao3** [TheAlgorithms/Java#2934]
**Is your feature request related to a problem? Please describe.**
It returns r length subsequences of elements from the input array. Combinations are emitted in lexicographic sort order. So, if the input array is sorted, the combination list will be produced in sorted order

**Describe the solution you'd like**
Using backtracking and DP.

**Describe alternatives you've considered**
DFS or brutal force

**Comment by siddhant2002** [comment]
Can I work under this issue?

**Comment by siriak** [comment]
Cannot check right now, but I think it's already implemented. I'll verify that later

**Comment by siriak** [comment]
Just checked, already implemented
