### ISSUE TITLE
Variable type writing error

### ISSUE THREAD

**Issue by Boris-Chang** [TheAlgorithms/Java#2941]
**Describe the bug**
Variable type writing error

**To Reproduce**

1. Go to 'Java/src/main/java/com/thealgorithms/datastructures/trees'
2. Click on 'AVLSimple'
3. Scroll down to 'Line 85'

**Expected behavior**
Modify variable “Strings” to “String”

**Screenshots**
![image](https://user-images.githubusercontent.com/61522364/153973300-7eb1b87c-98dc-467b-8121-a2a9e075b59e.png)

**Device Specification**

**Additional context**

**Comment by siriak** [comment]
Thanks for reporting, could you create a PR to fix that?

**Comment by Boris-Chang** [comment]
Created.

Andrii Siriak ***@***.***> 于2022年2月18日周五 04:15写道：

**Comment by Boris-Chang** [comment]
Created fail. I don't understand this error. How to create success?

The image below shows the error

Andrii Siriak ***@***.***> 于2022年2月18日周五 04:15写道：

**Comment by siriak** [comment]
It's a work in progress in #2948
