### ISSUE TITLE
CheckVowels.java hasVowels() method wrong

### ISSUE THREAD

**Issue by aldotele** [TheAlgorithms/Java#2990]
**Describe the bug**
In `strings\CheckVowels.java`, the `hasVowels` method might be wrong

**To Reproduce**

Create a test method and perform the following assertion:
`Assertions.assertTrue(CheckVowels.hasVowels("Hello World"));`
It will fail even if the sentence contains vowels

**Comment by acbin** [comment]
Hi, I will fix the issue
