### ISSUE TITLE
There should be an else clause on delete(Node n, int key) method

### ISSUE THREAD

**Issue by chinmaybadhe** [TheAlgorithms/Java#3007]
There should be an else clause on delete(Node n, int key) method for the case where the n.getNext() node does not have the getKey()==key. 

https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/datastructures/hashmap/hashing/HashMap.java

/**
Linked list class - delete method with the following signature
*/
        private void delete(Node n, int key) {
            if (n.getNext().getKey() == key) {
                if (n.getNext().getNext() == null) {
                    n.setNext(null);
                } else {
                    n.setNext(n.getNext().getNext());
                }
            }
        }

Possible Solution

        private void delete(Node n, int key) {
            if (n.getNext().getKey() == key) {
                if (n.getNext().getNext() == null) {
                    n.setNext(null);
                } else {
                    n.setNext(n.getNext().getNext());
                }
            }
```
else{
          delete(n.getNext(),key);
      }
```
        }

**Comment by siriak** [comment]
Solved
