### ISSUE TITLE
Added Test for the Quicksort Algorithm

### ISSUE THREAD

**Issue by Hambalieu** [TheAlgorithms/Java#3008]
We saw that there was no test writing for the Quicksort Algorithm and We decided to write some test for the quicksort algorithm.Below is the code that we wrote for it.

`package com.thealgorithms.sorts;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * @Author Hambalieu Jallow (https://github.com/Hambalieu)
 * @Author Tony Regalado (https://github.com/Edward-Regalado)
 */

class QuickSortTest {

    @Test
    @DisplayName("Empty Array")
    void quickSortEmptyArray()
    {
        QuickSort sut = new QuickSort();
        Integer[] array = {};
        Integer[] sorted = sut.sort(array);
        Integer[] expected = {};
        assertArrayEquals(expected, sorted);
    }

    @Test
    @DisplayName("Array has a single Value")
    void quickSortSingleValueArray()
    {
        QuickSort sut = new QuickSort();
        Integer[] array = {4};
        Integer[] sorted = sut.sort(array);
        Integer[] expected = {4};
        assertArrayEquals(expected, sorted);
    }

    @Test
    @DisplayName("merge sort array of integers")
    void quickSort()
    {
        QuickSort sut = new QuickSort();
        Integer[] array = {8, 4, 23, 42, 16, 15};
        Integer[] sorted = sut.sort(array);
        Integer[] expected = {4, 8, 15, 16, 23, 42};
        assertArrayEquals(expected, sorted);
    }

    @Test
    @DisplayName("sort array with negative values")
    void quickSortNegativeValue()
    {
        QuickSort sut = new QuickSort();
        Integer[] array = {8, -4, 23, -42, 16, 15};
        Integer[] sorted = sut.sort(array);
        Integer[] expected = {-42, -4, 8, 15, 16, 23};
        assertArrayEquals(expected, sorted);
    }

    @Test
    @DisplayName("array has duplicate values")
    void quickSortDuplicateValues()
    {
        QuickSort sut = new QuickSort();
        Integer[] array = {8, 4, 23, 42, 4, 15};
        Integer[] sorted = sut.sort(array);
        Integer[] expected = {4, 4, 8, 15, 23, 42};
        assertArrayEquals(expected, sorted);
    }

}

`

**Comment by siriak** [comment]
Cool, could you create a PR with this code?

**Comment by Hambalieu** [comment]
Yes I can do that

**Comment by siddhant2002** [comment]
Can I work under this issue?

**Comment by siriak** [comment]
@siddhant2002 sure!

**Comment by itsAkshayDubey** [comment]
@siriak , @Hambalieu  We can close this issue..
