### ISSUE TITLE
Rename CPUalgorithms class to MemoryManagmentAlgorithms 

### ISSUE THREAD

**Issue by pkyriakou23** [TheAlgorithms/Java#3012]
I suggest **renaming** the CPUalgorithms class to MemoryManagmentAlgorithms as this class **implements fit algorithms** that are used in the CPU but when it needs to allocate memory.

**Comment by Rytnix** [comment]
Hi siriak,
Can you assign me this issue, I will rename.

**Comment by Rytnix** [comment]
Thanks for this assignment siriak.
Done with the change.
You can check-out the PR #3071.
