### ISSUE TITLE
Open new Feature (algorithms) under Functions (new) module.

### ISSUE THREAD

**Issue by omarmahamid** [TheAlgorithms/Java#3033]
Tell me if you want to add new feature adding module that called functions and implementing all algorithms in this module.

another thing,, adding new data structure (Cukoo Hashing) under hash ?

adding another algorithm in prime checking (from article that published)

tell me if that fit you 

thanks, 
Omar

**Comment by siriak** [comment]
I didn't get what you meant by `Tell me if you want to add new feature adding module that called functions and implementing all algorithms in this module.`, but everything else would be nice to have
