### ISSUE TITLE
Preorder traversal in RedBlackBST is incorrect

### ISSUE THREAD

**Issue by Golden-Pigeon** [TheAlgorithms/Java#3045]
In the class `com.thealgorithms.datastructures.trees.RedBlackBST`, the preorder traversal is
```java
public void printTreepre(Node node) {
    if (node == nil) {
        return;
    }
    System.out.print(
         ((node.color == R) ? " R " : " B ") + "Key: " + node.key + " Parent: " + node.p.key + "\n");
    printTree(node.left);
    printTree(node.right);
}
```
Should the last two lines call `printTreepre` rather than `printTree`?
`printTree` is an inorder traversal method.

**Comment by Commanderadi** [comment]
Instead of printTreepre use printTree the error occured you assigned the wrong thing

**Comment by siriak** [comment]
I think it should call `printTreepre` at the end of the function

**Comment by Golden-Pigeon** [comment]
> 

Yes, that is what I mean.

**Comment by misgald** [comment]
public void printTreepre(Node node) {
    if (node == nil) {
        return;
    }
    System.out.print(
         ((node.color == R) ? " R " : " B ") + "Key: " + node.key + " Parent: " + node.p.key + "\n");
    return printTreepre(node.left)+ printTreepree(node.right);
   
}

**Comment by siriak** [comment]
@misgald please make a pull request

**Comment by Zohaib-Sathio** [comment]
@misgald return type of method is void so just calling the printTreepre() method with left and right nodes will do the work.

**Comment by AbhishhekMehrarda** [comment]
public void printTreepre(Node node) {
        if (node == nil){

        }
        else
        {
            System.out.print(((node.color == R) ? " R " : " B ") + "Key: " + node.key + " Parent: " + node.p.key + "\n");
            printTreepre(node.left);
            printTreepre(node.right);
        }
    }

**Comment by AbhishhekMehrarda** [comment]
public void printTreepre(Node node) {
        if (node == nil){
        }
        else
        {
            System.out.print(((node.color == R) ? " R " : " B ") + "Key: " + node.key + " Parent: " + node.p.key + "\n");
            printTreepre(node.left);
            printTreepre(node.right);
        }
    }

**Comment by natashasrivastava** [comment]
Hey, Can I work on this?

**Comment by Zohaib-Sathio** [comment]
> Hey, Can I work on this?

@natashasrivastava This has already been solved

**Comment by ababacoglu18** [comment]
public void printTreepre(Node node) {
if (node == nil) {
return;
}
System.out.print(
((node.color == R) ? " R " : " B ") + "Key: " + node.key + " Parent: " + node.p.key + "\n");
printTreepre(node.left);
printTreepre(node.right);
}

**Comment by siriak** [comment]
Closing as solved
