### ISSUE TITLE
Refactor classes to declarative agree 

### ISSUE THREAD

**Issue by Frankynz** [TheAlgorithms/Java#3068]
i suggest to refactor classes to declarative agree for java.

example in BitonicSort.java we have:

    void compAndSwap(int a[], int i, int j, int dir) {
        if ((a[i] > a[j] && dir == 1) || (a[i] < a[j] && dir == 0)) {
            // Swapping elements
            int temp = a[i];
            a[i] = a[j];
            a[j] = temp;
        }
    }

i suggest: (beacuse this is more readable)

    static void compareAndSwap(int[] array, int i, int j, int dir) {
        if ((array[i] > array[j] && dir == 1) || (array[i] < array[j] && dir == 0)) {
            // Swapping elements
            int temp = array[i];
            array[i] = array[j];
            array[j] = temp;
        }
    }
    
    and i suggest to declarative comments to java docs like that 
        /**
     * The parameter dir indicates the sorting direction,
     * ASCENDING or DESCENDING; if (array[i] > array[j]) agrees
     * with the direction, then array[i] and array[j] are
     * interchanged.
     */

**Comment by siriak** [comment]
There is no need to rename the array since the scope of this variable is only 4 lines, but thanks for suggesting it!
