### ISSUE TITLE
Contributing to Documentation

### ISSUE THREAD

**Issue by PRIYANKVAIDYA** [TheAlgorithms/Java#3129]
Hello Everyone, I want to start with open-source with contributing into the documentation. Please share the repo of Documentation and issues.  Repository: [https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md]

**Comment by Ankush263** [comment]
You can find the issue here `https://github.com/TheAlgorithms/Java/issues`

**Comment by siriak** [comment]
We don't have extensive documentation, it's mostly just comments in the source code
