### ISSUE TITLE
Moving DynamicArray implementation to more suitable place

### ISSUE THREAD

**Issue by Boiarshinov** [TheAlgorithms/Java#3145]
Hello! For now implementation of dynamic array data structure is containing in package `thealgorithms/datastructures/dynamicarray`. However _dynamic array_ is an [another name for](https://en.wikipedia.org/wiki/Dynamic_array) _array list_ data structure.
So what do you think about moving `DynamicArray` class to directory with all other lists: `thealgorithms/datastructures/lists`?

**Comment by Boiarshinov** [comment]
If `thealgorithms/datastructures/lists` is for linked lists why it's not named `thealgorithms/datastructures/linkedlists`? 😃

**Comment by siriak** [comment]
We can move `dynamicarray` to `lists/dynamicarray` and linked lists to `lists/linkedlists`. What do you think?

**Comment by Boiarshinov** [comment]
I think it would be great!
