### ISSUE TITLE
CI job cannot setup python

### ISSUE THREAD

**Issue by Boiarshinov** [TheAlgorithms/Java#3155]
`update_directory_md` job always fails because of lack of python in a CI agent with specified version.

Github action failing declaration:
```
Run actions/setup-python@master
  with:
    token: ***
```

Error message:
```
Error: The specified python version file at: /home/runner/work/Java/Java/.python-version does not exist
```

I'm not familiar with github actions, but examples in [setup-python action repository](https://github.com/actions/setup-python) always specify **version** of python in the `.yaml` file, **not the branch**

So i think that problem is in `@master` part of the job declaration.
Can you try to change [this line](https://github.com/TheAlgorithms/Java/blob/22be348c546fe517c12f96575191aa6413952db5/.github/workflows/update_directory.yml#L21) of job declaration to something like snippet below?
```yaml
- uses: actions/setup-python@v3
``` 

Or maybe [release 4.0.0](https://github.com/actions/setup-python/releases/tag/v4.0.0) of that github action could solve our problem, because there is something about python version file in the [release notes](https://github.com/actions/setup-python/releases/tag/v4.0.0)

**Comment by siriak** [comment]
Interesting, could you create a PR with the proposed changes? I would be glad to get it working

**Comment by Boiarshinov** [comment]
It seems to work :D 
https://github.com/TheAlgorithms/Java/pull/3157
