### ISSUE TITLE
Add a hashtable with cuckoo hashing algorithm

### ISSUE THREAD

**Issue by Boiarshinov** [TheAlgorithms/Java#3188]
Add a hashtable with [cuckoo hashing](https://en.wikipedia.org/wiki/Cuckoo_hashing) algorithm.
There is no implementation of that data structure here yet.

Could be a **good first issue**.

**Comment by haeshed** [comment]
Hey, 
Added the implementation for Cuckoo Hashing, using a single (not double) table.
This is my first contribution so hopefully will be according to standards.
Im open for criticism and/or changes.
Thank you.

**Comment by haeshed** [comment]
Finished and merged.
Can close issue.
