### ISSUE TITLE
Combination code in backtracking may be misleading

### ISSUE THREAD

**Issue by cuiHL** [TheAlgorithms/Java#3190]
```
    for (int i = index; i < arr.length; i++) {
        currSet.add(arr[i]);
        backtracking(arr, i + 1, currSet, result);
        currSet.remove(arr[i]);
    }
```
It should be `backtracking(arr, index + 1, currSet, result);`

**Comment by siriak** [comment]
Which file is that code from?

**Comment by cuiHL** [comment]
> Which file is that code from?

[Combination.java](https://github.com/TheAlgorithms/Java/tree/master/src/main/java/com/thealgorithms/backtracking/Combination.java)

**Comment by siriak** [comment]
It seems correct, we're adding an element to the set and backtracking subsets with it, and then removing the element from the set and backtracking subsets without the element.

**Comment by emmygithub** [comment]
Yeah, it seems correct also.
