### ISSUE TITLE
Feature in "Strings" Data Structure

### ISSUE THREAD

**Issue by Mann-tech13** [TheAlgorithms/Java#3236]
An algorithm for checking if strings are isomorphic or not is not there. Kindly assign me this issue to add this feature.

**Comment by Mann-tech13** [comment]
Should I make the new branch before pushing the new feature?

**Comment by siriak** [comment]
Yes, please. And make a PR once it's ready

**Comment by ayushanand308** [comment]
Hey @Mann-tech13 are you still working on the issue? I was hoping I could work on it if you are not.

**Comment by Mann-tech13** [comment]
Yes @ayushanand308

**Comment by parth-verma7** [comment]
Hey @Mann-tech13 cal I work upon this issue? I am new to open source, I think I can do this.

**Comment by aayan14** [comment]
Hi @ siriak
Can I work on this issue if it is still unsolved?

**Comment by siriak** [comment]
It's already implemented https://github.com/TheAlgorithms/Java/blob/e96f567bfc6e980dc5c4c48ccf185d7f7c7108ab/src/main/java/com/thealgorithms/strings/Isomorphic.java
