### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException with BinarySearch

### ISSUE THREAD

**Issue by vie02** [TheAlgorithms/Java#3248]
**Describe the bug**
java.lang.ArrayIndexOutOfBoundsException with BinarySearch

**To Reproduce**
Any case with the key is bigger than the biggest number of the array should reproduce the java.lang.ArrayIndexOutOfBoundsException (while should return -1 instead)
Example: search for 20 in [-10, -4, 2, 5, 9, 15]

**Expected behavior**
java.lang.ArrayIndexOutOfBoundsException was thrown

**Screenshots**
![image](https://user-images.githubusercontent.com/10360205/188318105-3df0ae99-744b-4fab-a879-59af6d825311.png)

**Device Specification**

**Comment by rakhazachrie** [comment]
Hi, can I work on this issue? thanks
