### ISSUE TITLE
Become a member of your community 

### ISSUE THREAD

**Issue by imlakshay08** [TheAlgorithms/Java#3251]
I am a computer science engineering student. I want to join the community TheAlgorithms. I am an open source beginner and full-stack developer. I want to increase my knowledge and experience in open source and programming through connecting with the community, as networking is also a crucial part of one's career. Open source has really been helpful for providing me almost all the resources I required to learn different frameworks, technologies and languages. It would be an honor to be a part of this community. Thank you so much.

**Comment by Yshasya** [comment]
Hi, i have want question, You know how to check emeil 8 code for the open github....bcause i forget emeil and then the email want 8 code for the open github

**Comment by Yshasya** [comment]
For the emeil sasyamania1310@gmail.com....bcause have some people open my emeil

**Comment by siriak** [comment]
@imlakshay08 you can join our Discord https://discord.gg/UEyJXFxkKr or raise a PR at any time!
