### ISSUE TITLE
Computer Networking related algorithms

### ISSUE THREAD

**Issue by MihSawant** [TheAlgorithms/Java#3268]
**Algorithm for error bits correction in network packet**
I would algorithms Like Hamming Distance, Cyclic Redundancy for error bits recognition and correction
at sender and receiver side.

**Comment by MihSawant** [comment]
Like for e.g. if we have bits from SENDER: 10001 and RECEIVER receives 10000
Then here there is 1 bit missed, this is one simple example
Another one is that we can do cyclic check on both sender and receiver side by binary division and verify the bits
or if there is error than we can get to know error bit length.

**Comment by MihSawant** [comment]
I have updated the code and tests for the algorithm, please review

**Comment by elmergustavo** [comment]
Perfect
