### ISSUE TITLE
Fixing the errors in the Directory.md

### ISSUE THREAD

**Issue by kalashjain23** [TheAlgorithms/Java#3271]
![Screenshot from 2022-09-15 23-03-14](https://user-images.githubusercontent.com/97672680/190472466-3e90d7ac-124e-4742-9a9e-14f01233dc1a.png)

There are some minor errors in the structure given in the Directory.md file. I'm proposing some changes in order to change the structure to its correct form.

**Comment by siriak** [comment]
Fixed, thanks!
