### ISSUE TITLE
Fcfs process scheduling algorithm

### ISSUE THREAD

**Issue by MihSawant** [TheAlgorithms/Java#3291]
**Is your feature request related to a problem? Please describe.**
This algorithm is based on FCFS scheduling algorithm

**Describe the solution you'd like**
Implement fcfs scheduling algorithm 

**Additional context**
Fcfs is a simple process scheduling algorithm, in which it takes the process that comes first or the process which has Arrival TIme first
to be taken in execution, execute it till completion and then other and so on.

**Comment by manishtambe** [comment]
If this issue is still open can I contribute to it by giving my program ?

**Comment by smiti-maheshwari** [comment]
Hi Team, 

I have added a [PR](https://github.com/TheAlgorithms/Java/pull/3335) for this.
