### ISSUE TITLE
Twin prime implementation

### ISSUE THREAD

**Issue by itsAkshayDubey** [TheAlgorithms/Java#3293]
Hi,

I have not seen any implementation of [Twin prime](https://en.wikipedia.org/wiki/Twin_prime) in this repo.
Could you please assign this issue to me?

Regards,
Akshay

**Comment by litaniachauke** [comment]
well I wrote my own little twin prime tester program hope it makes it in... Not much error handling

[TwinPrimeTester.zip](https://github.com/TheAlgorithms/Java/files/9678162/TwinPrimeTester.zip)

**Comment by siriak** [comment]
@litaniachauke, please make a PR if you want to contribute your code

**Comment by itsAkshayDubey** [comment]
Closing this issue, since PR #3312 is merged.
