### ISSUE TITLE
Adding N Queens Problem in Backtracking folder

### ISSUE THREAD

**Issue by Radhika403** [TheAlgorithms/Java#3353]
I would like to add a solution to the N queens problem. N is the size of a chess board.
and we are required to place n number of queens in the n * n cells of the board such that no queen can kill another.

I would like to solve the same using backtracking in Java.

Kindly assign this to me under the hacktoberfest.

**Comment by chandraPrakash23** [comment]
I can solve this task in most optimized manner , so you can assign this task to me.

**Comment by siriak** [comment]
Already implemented here https://github.com/TheAlgorithms/Java/blob/e96f567bfc6e980dc5c4c48ccf185d7f7c7108ab/src/main/java/com/thealgorithms/backtracking/NQueens.java
