### ISSUE TITLE
Bubble sort,selection sort (could be added should i work on it)?

### ISSUE THREAD

**Issue by Tridib11** [TheAlgorithms/Java#3365]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by happiestbee** [comment]
I can work on this

**Comment by neeraj3199** [comment]
I CAN DO IT

**Comment by riteshshaw18** [comment]
Hey,can you assign this to me

**Comment by impragya08** [comment]
Hello sir,

I have not seen any implementation of Bubble sort, Selection sort in this repo.
Could you please assign this issue to me?

Regards,
Pragya

**Comment by jgarg8440** [comment]
Hello sir, Can you assign this problem to me. I will work better in this problem and solve this issue.

**Comment by ShivangShandilya** [comment]
Hello Sir, I have mastered Data Structures and Algorithms and I think I would be able to solve this issue perfectly, please assign this to me.
Regards

**Comment by shahabrar7746** [comment]
Hey, This looks perfect Issue for me to start in Open source. Could you please assign this to me

**Comment by siriak** [comment]
It's already implemented https://github.com/TheAlgorithms/Java/blob/e96f567bfc6e980dc5c4c48ccf185d7f7c7108ab/src/main/java/com/thealgorithms/sorts/SelectionSort.java
