### ISSUE TITLE
I want to submit a two sum problem solution

### ISSUE THREAD

**Issue by DroneCodes** [TheAlgorithms/Java#3368]
Hello I would love to submit a solution to the Two-sum problem from leetcode

**Comment by Prakhar1106** [comment]
Please assign this issue to me, I am interested...
Is this repo participating in hacktoberfest??

**Comment by Appy-007** [comment]
Can you give the reference to the problem @DroneCodes

**Comment by DroneCodes** [comment]
@Appy-007  It is the number 1 problem on leetcodes list of question

**Comment by Appy-007** [comment]
@DroneCodes got it ,do you want the code in the same format as given in the problem or you just want the problem to be solved

**Comment by DroneCodes** [comment]
@Appy-007 I wanted to know if I could submit it

**Comment by akshatbajetha** [comment]
Hi! I would like to submit a solution to the Two Sum problem on Leetcode. I have a simple, easy-to-understand, and a beginner friendly solution to this issue!! Thanks!
