### ISSUE TITLE
Want to add Binary Tree Algorithms and some practice problems.

### ISSUE THREAD

**Issue by CoderLovely08** [TheAlgorithms/Java#3371]
I want to contribute Binary tree algorithms such as DFS and BFS and some practice problems which will an individual to better understand the underlying concept.

**Comment by siriak** [comment]
Already implemented https://github.com/TheAlgorithms/Java/blob/e96f567bfc6e980dc5c4c48ccf185d7f7c7108ab/src/main/java/com/thealgorithms/searches/BreadthFirstSearch.java
