### ISSUE TITLE
Path Sum 1, 2, 3, and  4 (Medium - Hard Binary Tree Question)

### ISSUE THREAD

**Issue by Sabyasachi-Seal** [TheAlgorithms/Java#3378]
**Is your feature request related to a problem? Please describe.**
Here are the question links : 
https://leetcode.com/problems/path-sum/
https://leetcode.com/problems/path-sum-ii/
https://leetcode.com/problems/path-sum-iii/
https://leetcode.com/problems/path-sum-iv/

**Describe the solution you'd like**
I would like to add the most optimal solutions to the repository

**Describe alternatives you've considered**

**Additional context**

**Comment by vxhl** [comment]
Hey, assign this to me please.

**Comment by siriak** [comment]
We don't add leetcode problems
