### ISSUE TITLE
Add Double-ended priority queue

### ISSUE THREAD

**Issue by JeonSeongBae** [TheAlgorithms/Java#338]
I want to add new heap.

A double-ended priority queue (DEPQ) or double-ended heap is a data structure similar to a priority queue or heap, but allows for efficient removal of both the maximum and minimum, according to some ordering on the keys (items) stored in the structure. Every element in a DEPQ has a priority or value. In a DEPQ, it is possible to remove the elements in both ascending as well as descending order.

**Comment by kai18** [comment]
If no one else is working on this issue, I'd like to make a contribution.

**Comment by JeonSeongBae** [comment]
Sure. No problem!
