### ISSUE TITLE
Bitwise Operands

### ISSUE THREAD

**Issue by vaibhavpriyatosh** [TheAlgorithms/Java#3399]
**Is your feature request related to a problem? Please describe.**
I want to create a concise folder for helping in understanding of Bitwise Manipulation.

**Describe the solution you'd like**
I would create a folder consisting of different algorithms in context of Bitwise Manipulation starting with some of the algorithms and then completing it with all sort of algorithms alongside with the help of other contributions.

**Comment by Anu-Ra-g** [comment]
Is this repo associated with Hacktoberfest?

**Comment by siriak** [comment]
You can add optimized versions of algorithms next to originals. No need for a separate folder
