### ISSUE TITLE
Error code in Conversions.

### ISSUE THREAD

**Issue by LeeChungWan** [TheAlgorithms/Java#340]
I send a new PR for another error.

PR#339 Updated OctalToDecimal.java
URL : https://github.com/TheAlgorithms/Java/pull/339

Modified error.

1. modified error in return type.

**Comment by LeeChungWan** [comment]
@varunu28 
I sent new PR(#339  ) for issue that mentioned at #336 .

But no respond.

Please check my PR and review.

**Comment by varunu28** [comment]
Merged. Closing the issue
