### ISSUE TITLE
Can i add the following algorithm problems from CODECHEF starters and lunchtime ?? in java ??

### ISSUE THREAD

**Issue by rahulranjan74** [TheAlgorithms/Java#3413]
SUSPENSE STRING - https://www.codechef.com/START59D/problems/SUSSTR
FAR AWAY - https://www.codechef.com/START56D/problems/FARAWAY
STICK BREAK - https://www.codechef.com/LTIME112D/problems/STICKBREAK

**Comment by siriak** [comment]
We don't add problems from competitive programming websites, thanks!
