### ISSUE TITLE
Travelling Salesperson Problem 

### ISSUE THREAD

**Issue by Nishant2209** [TheAlgorithms/Java#3414]
I want to add **Travelling Salesperson Problem** under a new folder **Branch and Bound**. 

The **Traveling Salesman Problem** (also called the **Traveling Salesperson Problem** or **TSP**) asks the following question: "Given a list of cities and the distances between each pair of cities, what is the shortest possible route that visits each city exactly once and returns to the origin city?" It is an NP-hard problem in combinatorial optimization, important in [theoretical computer science and operations research.

![Euler12](https://user-images.githubusercontent.com/71169457/194297860-f992579a-2ed4-41a5-93df-89aa1b8a8f65.png)

For example, consider the graph shown in the figure on the right side. A TSP tour in the graph is 1-2-4-3-1. The cost of the tour is 10+25+30+15 which is 80. The problem is a famous NP-hard problem. There is no polynomial-time know solution for this problem. The following are different solutions for the traveling salesman problem. 

Naive Solution: 

1) Consider city 1 as the starting and ending point.

2) Generate all (n-1)! Permutations of cities. 

3) Calculate the cost of every permutation and keep track of the minimum cost permutation. 

4) Return the permutation with minimum cost. 

Time Complexity: Θ(n!)

**Comment by Nishant2209** [comment]
I want to solve this problem so kindly assign this to me under hacktoberfest.

**Comment by shaswata-karan** [comment]
I want to solve this problem so kindly assign this to me under hacktoberfest.

**Comment by Nishant2209** [comment]
@shaswata-karan I have already solved it dude !!!

**Comment by chandraPrakash23** [comment]
Assign this task to me as I have already solved it.
