### ISSUE TITLE
Views in a Binary Tree

### ISSUE THREAD

**Issue by sujay31** [TheAlgorithms/Java#3429]
**Is your feature request related to a problem? Please describe.**
Different views of a Binary Tree (left view, right view, top view & bottom view)

**Describe the solution you'd like**
Left & Right views can be obtained using level over traversal of the binary tree.
Top & Bottom views can be obtained using level order traversal and horizontal distance with respect to the root node.

**Describe alternatives you've considered**
All the views can be generated using recursion or iteration. Preferring iterative solution to prevent recursion call overhead.

**Additional context**
Not Applicable

@siriak @yanglbme please assign this to me. I have created a pull request implementing this.

Please use the tag "hacktoberfest-accepted".

Pull request #3428 ([link](https://github.com/TheAlgorithms/Java/pull/3428))

**Comment by sanglap-02** [comment]
Hi. I can give the most optimal solution to find the views ( **top view , bottom view , left view and right view **) in a binary tree. please assign this issue to me.

**Comment by drashan14** [comment]
Hello Sir , can you assign this issue to me . I can give you a better solution on this topic to find all types of views in binary tree  include( Top View ,Bottom View, Left View ,Right View).

**Comment by drashan14** [comment]
Hello Sir , Can you assign this issue to me . I will give you a better solution  and   minimum  time complexity for  this issue to  find all types of view in binary tree.

**Comment by Mugdhashrivastava** [comment]
i want to do it

**Comment by HarshitaSingh828** [comment]
Hello Sir, please assign this issue to me
