### ISSUE TITLE
Adding Longest Common Subsequence problem of DP

### ISSUE THREAD

**Issue by Rajat-Sharma1710** [TheAlgorithms/Java#3432]
**LCS Problem Statement** 

 Given two sequences, find the length of longest subsequence present in both of them. A subsequence is a sequence that appears in the same relative order, but not necessarily contiguous. For example, “abc”, “abg”, “bdf”, “aeg”, ‘”acefg”, .. etc are subsequences of “abcdefg”.

**Comment by Rajat-Sharma1710** [comment]
I have added the solution to this problem in best time complexity.

**Comment by Atharva1520** [comment]
Sir,Can You Please Assign this Task to me?

**Comment by Arko27** [comment]
I have doing competitive programming for a long time. So I would be able to solve this dp problem in the most optimized way. please assign this task to me.

**Comment by RishikaKant** [comment]
Hello Sir, please assign this issue to me

**Comment by HarshitaSingh828** [comment]
Hello Sir, please assign this issue to me

**Comment by siriak** [comment]
It's already implemented here https://github.com/TheAlgorithms/Java/blob/e96f567bfc6e980dc5c4c48ccf185d7f7c7108ab/src/main/java/com/thealgorithms/dynamicprogramming/LongestCommonSubsequence.java
