### ISSUE TITLE
LinkedList program containing methods to  add at first, middle, last, count nodes and display nodes.

### ISSUE THREAD

**Issue by aksharma27** [TheAlgorithms/Java#3436]
I want to add a single linkedlist program which is not present in the repo.

The program will consist of addition of nodes at various places like at the first middle and last. And at last to count the nodes and print the nodes methods with proper comments

Can I work on this issue?

**Comment by SmritiV23** [comment]
I would like to solve this problem, please do assign this task to me.

**Comment by JunJul** [comment]
I can work on this, could you assign the task to me?

**Comment by Anshika672** [comment]
i would like to work on this,if you assign it to me..please do

**Comment by drashan14** [comment]
Hello Sir ,I would like to solve this issue could you assign  this issue to me .I will give you a better solution which is solve in minimum time complexity.

**Comment by harman5911** [comment]
I would like to solve this problem, please do assign this task to me.

**Comment by ptiwari6239** [comment]
hi 
if this issue is still open can you assign it to me as i am beginner to open source and wanted to start contributing  
thanks

**Comment by siriak** [comment]
Already implemented here https://github.com/TheAlgorithms/Java/blob/e96f567bfc6e980dc5c4c48ccf185d7f7c7108ab/src/main/java/com/thealgorithms/datastructures/lists/DoublyLinkedList.java
