### ISSUE TITLE
Stack permutation

### ISSUE THREAD

**Issue by iianuragii** [TheAlgorithms/Java#3441]
Can I add a DSA program of Stack permutation means that one array can be created from another array using a stack and stack operations. Using VS Code

**Comment by Tharunkumar001** [comment]
Kindly assign this issue to me @iianuragii

**Comment by SmritiV23** [comment]
I would like to solve this problem, please do assign this task to me.

**Comment by Anshika672** [comment]
i would like to solve this issue

**Comment by drashan14** [comment]
Hello sir !
I would like to do this task could you assign me this task.

**Comment by adithya27082002** [comment]
pls assign me

**Comment by iianuragii** [comment]
> I would like to solve this problem, please do assign this task to me.
 
Ok do it
