### ISSUE TITLE
uppercase string array without using standard library functions, which makes the algorithm faster by few milliseconds-(Java/src/main/java/com/thealgorithms/strings/Upper.java )

### ISSUE THREAD

**Issue by prplmnstr** [TheAlgorithms/Java#3445]
1. In the above mentioned algorithm the author used the library functions to check lowercase letters and to convert it to uppercase. which will be time consuming and makes the algorithm again depend on the external built in functions.  it can be speeded up by using ascci values and independent of standard libraries.` 
2. public static String toUpperCase(String s) {
        if (s == null || "".equals(s)) {
            return s;
        }
        char[] values = s.toCharArray();
        for (int i = 0; i < values.length; ++i) {
            if (    **lHere used the library functions**
                  
                Character.isLetter(values[i]) &&
                Character.isLowerCase(values[i])
   
//these above 2 checks can be reduced  as 

values[i]>='a' &&  values[i]<='z'
            ) {

                  // here used library functions
                values[i] = Character.toUpperCase(values[i]);

this above line can be changed as 

// values[i] = (char) (values[i] - 32);
            }
        }
        return new String(values);
    }`

**Comment by prplmnstr** [comment]
I want to make this code even more simpler and independent of system libraries , so please assign this to me under HACKTOBERFEST

**Comment by JunJul** [comment]
Hi, maintainer could you assign this task to me?

**Comment by debasishbsws** [comment]
Library Functions are there to be used. As an Algorithm repository, this type of change is not needed. Even Library functions made the code more readable. Understanding algorithm readability is more important than a few milliseconds.

**Comment by siriak** [comment]
I agree with @debasishbsws
