### ISSUE TITLE
Steps to clone repo in readme.md file

### ISSUE THREAD

**Issue by ShubhraSuman** [TheAlgorithms/Java#3448]
Can I add necessary steps required to clone the project.

**Comment by ShubhraSuman** [comment]
Can you assign this to me

**Comment by nfarhaan** [comment]
Hello,
Can you assign this issue to me?

**Comment by karthinivashSR** [comment]
Hello @ShubhraSuman, I would like to get assigned to this, so can you assign this issue to me

**Comment by siriak** [comment]
This is not necessary because it's not something specific to this repo and there are GitHub docs about that
