### ISSUE TITLE
Add new algorithms under a new directory 'BranchAndBound'

### ISSUE THREAD

**Issue by prplmnstr** [TheAlgorithms/Java#3449]
There is no directory for Branch and Bound Algorithms.
These are the few algorithms we can add in this folder.

- Travelling salesman problem
- 0/1 Knapsack problem
- Job Assignment problem

**Comment by prplmnstr** [comment]
I can add above mentioned algorithms

**Comment by HaegyeongKim01** [comment]
Hello, I'm undergraduate student.
I have a course of contributing the open source.
May I assign this issue?
