### ISSUE TITLE
Implementation of Math Functions

### ISSUE THREAD

**Issue by rakshitgupta23** [TheAlgorithms/Java#3453]
**Is your feature request related to a problem? Please describe.**

No, its not. I want to add the implementation of all math functions in java.

**Describe the solution you'd like**

My tutorial will help beginners in implementing all the math functions in java.

Example:

 System.out.println(Math.pow(2,3));
Output: 8.0

**Comment by rakshitgupta23** [comment]
@aitorfi Please assign this to me.

**Comment by psrp7** [comment]
plz assign me this

**Comment by SohamPashteSSP** [comment]
Hello, please assign me this

**Comment by SanjeeeV-99** [comment]
Hi Sir, this is the first time i've registered for it. can you pleases assign this to me?

**Comment by Harshita781** [comment]
sir pls assign this feature to me

**Comment by Vivek-04022001** [comment]
Hey, I'm interested in this issue. Can I contribute to it?

**Comment by ayeshadevcs** [comment]
Hey, I have the command on math functions and I want to do this. Kindly assign this issue to me.

**Comment by siriak** [comment]
This is not needed
