### ISSUE TITLE
SJF Scheduling Algoritm

### ISSUE THREAD

**Issue by impragya08** [TheAlgorithms/Java#3467]
Is your feature request related to a problem? Please describe. 
SJF CPU Scheduling Algorithm

Describe the solution you'd like
This solution will implement the SJF CPU Scheduling 

Additional context
SJF Algorithm stands for Shortest Job First. This algorithm will schedule the process according to its bus time with the process having shortest bus time on the first position and so on

**Comment by impragya08** [comment]
Hi,

I have not seen any implementation of SJF Algorithm in this repo.
Could you please assign this issue to me?

Regards,
Pragya

**Comment by Atharva1520** [comment]
Sir,Can You Please Assign this Task to me?

**Comment by yash509** [comment]
Hello Ma'am, Can you please assign this task to me??

**Comment by krunalpabari13** [comment]
Sir, Can you please assign this task to me, I have solved many question of DSA using java

**Comment by riddhitech** [comment]
Please assign me this issue.

**Comment by Meghwantsingh** [comment]
Assign me this issue.

**Comment by trisha217** [comment]
Please assign me this issue sir.

**Comment by siriak** [comment]
Implemented here https://github.com/TheAlgorithms/Java/blob/e96f567bfc6e980dc5c4c48ccf185d7f7c7108ab/src/main/java/com/thealgorithms/others/SJF.java
