### ISSUE TITLE
Check if a binary tree is symmetric or not

### ISSUE THREAD

**Issue by kumanoit** [TheAlgorithms/Java#3471]
**Is your feature request related to a problem? Please describe.**
Check whether a binary tree is symmetric or not.

**Describe the solution you'd like**
 * Recursively check for left and right subtree of root
 * 1. left subtrees root's values should be equal right subtree's root value
 * 2. recursively check with left subtrees' left child VS right subtree's right child AND
 * left subtree's right child VS right subtree left child
Ex.
Below is a symmetric tree
```
                               1
                   /                         \
                 2                           2
         /                \             /             \
      3                    4         4                3
```
Below is not symmetric because values is different in last level
```
                               1
                   /                         \
                 2                           2
         /                \             /             \
      3                    5         4                3
```

**Describe alternatives you've considered**
Suggested optimal solution

**Additional context**

**Comment by randymramli** [comment]
Hi, I would like to handle this issue.

**Comment by kumanoit** [comment]
@randymramli This is already fixed in https://github.com/TheAlgorithms/Java/pull/3472

**Comment by drashan14** [comment]
Hello Sir ,
Could you assign me this task ,I'm interested in this issue to solve.

**Comment by kumanoit** [comment]
@drashan14 As mentioned in above comment, this is already fixed in https://github.com/TheAlgorithms/Java/pull/3472
