### ISSUE TITLE
Climbing stairs dp problem

### ISSUE THREAD

**Issue by 2tanayk** [TheAlgorithms/Java#3474]
**Is your feature request related to a problem? Please describe.**
I would like to add a solution to the [Climbing Stairs](https://leetcode.com/problems/climbing-stairs/) problem in Java

**Comment by tianhaoz12** [comment]
Hi, can I provide a solution?

**Comment by Atharva1520** [comment]
Sir,Can You Please Assign this Task to me?

**Comment by yash509** [comment]
Hello sir, Can you please assign this task to me??

**Comment by Arko27** [comment]
can you please assign this task to me. I have the optimized solutions for various types of the climbing stairs problem.

**Comment by kingslayerkr108** [comment]
Hello sir, Can you please assign this task to me??

**Comment by technoayan7** [comment]
Hello Sir, Iam Competitve Programmer Specialist at Codeforces and 4* at Codechef. Can you assign this task to me. I have solved this in a very optimised way.

**Comment by RishikaKant** [comment]
Hello, please assign this issue to me

**Comment by rishabh0303** [comment]
Hello, can you assign this issue to me?

**Comment by riddhitech** [comment]
Please assign me this issue.

**Comment by HarshitaSingh828** [comment]
Hello Sir, please assign this issue to me

**Comment by dineshlalam15** [comment]
[](https://leetcode.com/problems/climbing-stairs/solutions/2897549/java-solution-using-dp/)
Here's the solution using Dynamic Programming.
