### ISSUE TITLE
Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.

### ISSUE THREAD

**Issue by 2tanayk** [TheAlgorithms/Java#3475]
**Is your feature request related to a problem? Please describe.**
I would like to contribute a solution to the [Min Stack](https://leetcode.com/problems/min-stack/) problem

**Describe the solution you'd like**
I would basically implement a stack using the LinkedList data structure.

**Comment by PawanGupta14** [comment]
hi i would like to do this issues kindly assigned me 
thank you

**Comment by BugsBunny-PG** [comment]
Hello Maintainer,
I want to  solve this problem ,please assign this issue to me.

**Comment by Atharva1520** [comment]
Sir,Can u Please Assign this Task to me?

**Comment by SmritiV23** [comment]
I would like to contribute a solution to this problem, please do assign this task to me.

**Comment by JenilShah0120** [comment]
I  ready to do this so please do assign this task to me

**Comment by rajkumar4you** [comment]
Could you please assign this to me?

**Comment by drashan14** [comment]
Hello Sir,
I'm interested to solve this problem could you assign me this issue ,I will give you a better solution and good time complexity for this issue.

**Comment by apoorvdtu** [comment]
Hello Sir,
Can You assign this issue to me?

**Comment by 5SPriya404** [comment]
hello sir
I want you to assign this issue to me.

**Comment by 26Saksham** [comment]
Hello sir
I want to assign this issue to me,i want to work them try to submit as soon as possible
thank you

**Comment by siriak** [comment]
Doesn't this class implement this? https://github.com/TheAlgorithms/Java/blob/9fb3364cccc5373c32dbdb661f773c5ee753c77a/src/main/java/com/thealgorithms/datastructures/stacks/StackArray.java
