### ISSUE TITLE
To add DFS, BFS and BST using LinkedList codes in datastructure/graphs & trees section in java

### ISSUE THREAD

**Issue by psantosh16** [TheAlgorithms/Java#3495]
**Is your feature request related to a problem? Please describe.**
There's no code for 
1. DFS  
2. BFS
3. BST using Linked List

**Describe the solution you'd like**
To add Codes for DFS and BFS along with LinkedList code for BST in java

**Additional context**
I will be great if you allow me to contribute in this repo , not only it help me to improve my skills but also help beginners who visit this repo to learn more about java and help them to build logic in java.

**Comment by rishi-kai21** [comment]
hi @psantosh16 I would like to work on this issue, can you please assign it to me please :)

**Comment by drashan14** [comment]
Hello sir /mam
I would like to do this job could you assign me this issue.

**Comment by Meghwantsingh** [comment]
I would like to solve this problem assign this to me sir.
