### ISSUE TITLE
To add DP Algorithm for Max Subarray Sum in O(n)

### ISSUE THREAD

**Issue by AnuragKumar007** [TheAlgorithms/Java#3500]
There are many approach for solving **Maximum_Subarray_Sum** but the best optimised approach is -:
**Kadane's Algorithm** with Time Complexity of **O(n)**.

I'm requesting to add this algorithm in your repo.

**Comment by karthinivashSR** [comment]
Hi @AnuragKumar007, I'm interested in solving this, so could you assign me into this?

**Comment by Arko27** [comment]
Could you please assign this task to me?

**Comment by drashan14** [comment]
Hello Sir ,
I'm interested to solve this problem could you assign me this issue.

**Comment by AnuragKumar007** [comment]
> Hi @AnuragKumar007, I'm interested in solving this, so could you assign me into this?

Yeah Why not, give it a try, Solve & add solution file

**Comment by AnuragKumar007** [comment]
> Could you please assign this task to me?

Yeah Why not, give it a try, Solve & add solution file

**Comment by AnuragKumar007** [comment]
> Hello Sir , I'm interested to solve this problem could you assign me this issue.

Yeah Why not, give it a try, Solve & add solution file

**Comment by Sinchan26** [comment]
Hello Sir,I'm an engineering student and really want to solve this problem could you please assign me this isssue?

**Comment by AnuragKumar007** [comment]
> Hello Sir,I'm an engineering student and really want to solve this problem could you please assign me this isssue?

Sure Brother give it a try

**Comment by Arko27** [comment]
sir could you please add hactoberfest level for this issue

**Comment by yashas-gune** [comment]
Hello sir, can I solve this question?

**Comment by RishikaKant** [comment]
Hello Sir, please assign this to me

**Comment by redhairrs** [comment]
For a DP Algo to solve this problem, U has to create a 1-D Array and store the Sum of the previous sub-array in the array, and just if you get a more considerable sum else return the first element.

Please assist me with this work, I am very good with Data-structure can do it easily for you.

**Comment by 11nitis** [comment]
Hey Anurag , can you assign this issue to me.

**Comment by HarshitaSingh828** [comment]
Hello Sir, please assign this issue to me
