### ISSUE TITLE
Implement Trie Data Structure

### ISSUE THREAD

**Issue by NEELAMSINGHH** [TheAlgorithms/Java#3511]
Prgoramme to Implement Trie in Java

**Comment by JagmeetSingh9** [comment]
@NEELAMSINGHHCan you assign me this?

**Comment by artiwari10** [comment]
Hello, I can write a clean program to implement Trie in Java. can you assign me this issue ?

**Comment by Vivek-04022001** [comment]
Hey, I'm interested in this issue. Can I contribute to it?

**Comment by RohtulXel** [comment]
Hello I am interset in this. Has it been already assigned?

**Comment by sanahmathur** [comment]
hello, I'm really interested in this issue, please consider assigning this problem to me!

**Comment by Mehrotra01** [comment]
As we all know tries is one of the very interesting data structure and i would be very glad to contribute in this task
