### ISSUE TITLE
To add Rail fence cipher code

### ISSUE THREAD

**Issue by ramanand-rv** [TheAlgorithms/Java#3522]
**Is your feature request related to a problem? Please describe.**
There's no Rail fence cipher Java code present in this repository.

**Describe the solution you'd like**
Add Railfence cipher Java code.

**Additional context**
Rail fence cipher is one of the very popular cryptographic algorithms taught in schools and colleges. The code for the same algorithm is not present in this repository. Hence I would love to add the Java Code for the same here which will be helpful for the students to refer to and learn.

Attaching the screenshot of the Railfence cipher input and output
![image](https://user-images.githubusercontent.com/80584888/195462439-02500da6-1276-4c04-9cff-3fc501930c4b.png)

**Comment by astitva0011** [comment]
assign this to me
