### ISSUE TITLE
I would like to implement the algorithm to merge K sorted lists under the queue folder. Please assign this to me

### ISSUE THREAD

**Issue by Sumedha4** [TheAlgorithms/Java#3527]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by drashan14** [comment]
Hello Sir/Mam ,
I would like to do this task could you assign me this issue.

**Comment by SmritiSharmaBG** [comment]
Do we need to have an issue assigned before making PR ?

**Comment by RishikaKant** [comment]
Hello, please assign this issue to me

**Comment by redhairrs** [comment]
Sir, I would like to take on this tasking can do it easily for you.
