### ISSUE TITLE
DP on decode ways 

### ISSUE THREAD

**Issue by Aniruddha-Bajpai** [TheAlgorithms/Java#3535]
**Is your feature request related to a problem? Please describe.**
[decode ways](https://leetcode.com/problems/decode-ways/) dp problem  is one such problem that made me frustrated when I had tried it so I would love to contribute on this problem

**Comment by technoayan7** [comment]
Hello Sir, Iam a Competitive programmer Specialist at Codeforces, I have solved this problem in an very easy and understandable way with all necessary commets added in it , Can you assign this task to me.

**Comment by apoorvdtu** [comment]
Hello Sir,
Can You assign this issue to me?

**Comment by Bhavil-Ahuja** [comment]
Please assign this issue to me

**Comment by HarshitaSingh828** [comment]
Hello Sir, please assign this issue to me
