### ISSUE TITLE
Hamming Code in Java

### ISSUE THREAD

**Issue by mv0302** [TheAlgorithms/Java#3539]
Hamming Code is an error detection and correction algorithm.
It is very difficult to find understandable code for 7-bit hamming code algorithm on the internet
 would like to contribute my code here.

**Comment by deepakbhagat7** [comment]
yes i would like to contribute

**Comment by ZohaiAli** [comment]
hello!
I already complete this task so please assign me then I can handover you the code

**Comment by adithya27082002** [comment]
can you pls assign me

**Comment by Akshatmish** [comment]
Please assign it to me
i would like to work
