### ISSUE TITLE
Pitest

### ISSUE THREAD

**Issue by Kevin222004** [TheAlgorithms/Java#3548]
To make sure every line of code and every method is working perfectly we can add mutation testing or you can say Pitest

Refrence :- https://pitest.org/

**Comment by Kevin222004** [comment]
If you are ready to implement it please assign me

**Comment by Kevin222004** [comment]
If anyone is not interested in this idea please let me know

**Comment by siriak** [comment]
That sounds interesting if you could set this up

**Comment by Kevin222004** [comment]
> That sounds interesting if you could set this up

Thanks I have reopen this and start working on this soon please assign me

**Comment by Kevin222004** [comment]
@siriak I know it is been quite long i have not raised pr actually busy with other open source project and currently busy with exam i will make changes soon
