### ISSUE TITLE
DP Solution to Subset Count

### ISSUE THREAD

**Issue by samratpodder** [TheAlgorithms/Java#3553]
**Is your feature request related to a problem? Please describe.**
Count Subsets is an extension to the Subset Sum problem. Given an array `arr[]` of length N and an integer X, the task is to find the number of subsets with a sum equal to X.

**Describe the solution you'd like**
A Dynamic Programming-based solution to the above problem and the original recursion-based solution.

**Additional context**
Testcase: 
Input: `arr[] = {1, 2, 3, 3}`, X = 6 
Output: 3 
All the possible subsets are {1, 2, 3}, 
{1, 2, 3} and {3, 3}

Input: arr[] = `{1, 1, 1, 1}`, X = 1 
Output: 4 

@siriak I am working on this. Kindly, assign this issue to me @samratpodder

**Comment by apoorvdtu** [comment]
Hello Sir,
Can You assign this issue to me?

**Comment by GeeteshMehto** [comment]
Hello sir, please assign this issue to me as i already worked on this kind of project in past and has a great experience.

**Comment by Shashank2104125** [comment]
Hello Sir,
I understand this issue and and also make it's logic clear. So Sir, please try to assign this issue to me.

**Comment by shubhig226** [comment]
Hello sir, please assign this issue to me. I've worked on this kind of project in past and have experience in DP.

**Comment by Meghwantsingh** [comment]
I would like to try this assign this to me.

**Comment by Bhavil-Ahuja** [comment]
Please assign this issue to me

**Comment by samratpodder** [comment]
PR #3580 addresses this issue. Issue can now be closed
