### ISSUE TITLE
Class name and .java file name's mismatch

### ISSUE THREAD

**Issue by LeeChungWan** [TheAlgorithms/Java#356]
When I checked the code in the repository I found a lot of different things in java files and class names.

Can I handle this issue?

**Comment by varunu28** [comment]
@LeeChungWan 
Thanks for pointing this out. You can take up this issue and do the changes where filename and class name are different.

**Comment by LeeChungWan** [comment]
I will change the difference and send PR.

**Comment by varunu28** [comment]
Sure. I am closing this issue
