### ISSUE TITLE
Time and Space Complexity Detailed notes with Examples

### ISSUE THREAD

**Issue by TRohit20** [TheAlgorithms/Java#3567]
**Adding notes for Time and Space complexity is crucial.**
It is crucial to know the time and space complexity any program we write, It allows us to see if there are any better ways to solve or reduce the time and space complexity

**I have compiled a personal notes of mine that has everything one needs to learn about time and space complexity**
By adding this to the repository, people using it can refer to the notes to learn time and space complexity in a simple yet precise manner with multiple approaches.

**Some alternative I have considered are:**
Adding bunch of resource links to YouTube or online material that do a good job of teaching them. We can still do it but notes would just be better as we can use it on the go.
[Time and Space Complexity.pdf](https://github.com/TheAlgorithms/Java/files/9797595/Time.and.Space.Complexity.pdf)

**Comment by TRohit20** [comment]
I have practically added the solution too bro. If they approve it, I'll just make a PR and close this😅

**Comment by harshsingh-io** [comment]
i have the **best notes** for **time and space complexity** of mine. can you please assign me for this??
