### ISSUE TITLE
Add greek translation to readme.md

### ISSUE THREAD

**Issue by ArchontisKostis** [TheAlgorithms/Java#3577]
Hello there! I just found this project through hacktoberfest. I thought it would be nice if there was a translation of the readme file in greek. I am from greece so I can be assigned to do it!

**Comment by ZohaiAli** [comment]
Hi!
I will do this in just a few seconds please assign me this task

**Comment by siriak** [comment]
Thanks for suggesting, but we don't include translations because they quickly become out of date and keeping them up to date is virtually impossible
