### ISSUE TITLE
Árvore N-ária

### ISSUE THREAD

**Issue by MatheusValera** [TheAlgorithms/Java#3578]
Explicando uma árvore N-ária : Uma árvore n-ária é tal que em cada nó da mesma há
um número arbitrário, limitado pela ordem da árvore,
de filhos [7]. Normalmente uma árvore n-ária é entendida como um superconjunto de árvores binárias. É o
caso da árvore n-ária de busca (ANB) [23] como superconjunto da árvore binária de busca (ABB). Pode-se
também citar a árvore B [3] como uma versão, neste formato, bastante utilizada em sistemas de arquivos que,
para ordem N = 2d + 1, sendo d um número natural,
deve ser vazia ou satisfazer as seguintes condições: a
raiz é uma folha ou tem no mínimo dois filhos; cada nó
diferente da raiz e das folhas possui no mínimo d+1 filhos; cada nó tem no máximo 2d+1 filhos. Cada nó em
uma árvore B é chamado de página e pode armazenar
várias chaves (com suas informações ou registros) [19].
É importante salientar que, para este tipo de árvore, a
complexidade computacional é O(log n), no pior caso,
em relação ao número de chaves. Uma redução ainda
maior do número de comparações ou acessos (crítico
em memória secundária), pode ser obtida pelo aumento
do número de chaves por nó.

Referência: http://www2.ic.uff.br/~vanessa/material/ed/03-ArvoresBinarias.pdf

**Comment by MatheusValera** [comment]
@UjjwalAggarwal-1

**Comment by siriak** [comment]
Please use English

**Comment by MatheusValera** [comment]
@siriak 
Explaining an N-ary tree: An n-ary tree is such that at each node of it there are
an arbitrary number, limited by the order of the tree,
of children [7]. Usually an n-ary tree is understood as a superset of binary trees. And the
case of the n-ary search tree (ANB) [23] as a superset of the binary search tree (ABB). you can
also cite the B tree [3] as a version, in this format, widely used in file systems that,
for order N = 2d + 1, where d is a natural number,
must be empty or satisfy the following conditions:
root is a leaf or has at least two children; every node
different from the root and leaves, it has at least d+1 children; each node has at most 2d+1 children. each node in
a B tree is called a page and can store
multiple keys (with your information or records) [19].
It is important to point out that, for this type of tree, the
computational complexity is O(log n), in the worst case,
in relation to the number of keys. A further reduction
greater number of comparisons or hits (critical
in secondary memory), can be obtained by increasing
of the number of keys per node.

**Comment by MatheusValera** [comment]
@UjjwalAggarwal-1

**Comment by UjjwalAggarwal-1** [comment]
I am not sure i understand what you mean.
