### ISSUE TITLE
How about adding Recursion?

### ISSUE THREAD

**Issue by UjjwalAggarwal-1** [TheAlgorithms/Java#3585]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Teuton-Roy** [comment]
Hello sir,
     Can you assign this work to me??

**Comment by Bhavil-Ahuja** [comment]
Please assign this issue to me

**Comment by RajdeepDey010** [comment]
Hello.Can you assign me this task?

**Comment by UjjwalAggarwal-1** [comment]
i think i cannot assign the issue to anyone, but if my PR is merged, you can add to the recursions directory

**Comment by siriak** [comment]
No need to create a separate module for recursion because it's not a method, but rather a technique that's used in other methods (e.g. in dynamic programming)

**Comment by UjjwalAggarwal-1** [comment]
okay.
