### ISSUE TITLE
Add more algorithms on Recursion

### ISSUE THREAD

**Issue by Teuton-Roy** [TheAlgorithms/Java#3591]
**Is your feature request related to a problem? Please describe.**
Yes, this request related on this problem. Here added only two algorithm. There are more algorithm like 1.Rope Putting Problem, 2.Josephus Problem, 3.Fibonacci Series etc.

**Describe the solution you'd like**
 I think, add this code with some understanding comments.

**Comment by RuchikaSuryawanshi7** [comment]
I would love to work on this issue, please assign this to me

**Comment by NileshSinha11** [comment]
Please assign this issue to me i will provide code with explanation

**Comment by Adityagupta200** [comment]
Added Fibonacci series one.

**Comment by Teuton-Roy** [comment]
@RuchikaSuryawanshi7  Please do it...

**Comment by adithya27082002** [comment]
pls assign me

**Comment by atharva20-coder** [comment]
> @RuchikaSuryawanshi7 Please do it...

Please can you specify the path where the algorithm needs to be added

**Comment by redhairrs** [comment]
I would like to work on this issue, 
like we can GCD_LCM, generating subset, tower of Hanoi, phone pad,  Permutation, etc.
I can add them for you...

**Comment by Mehrotra01** [comment]
i Would love to work on these issues, because as being an DSA beginner you solve many problem's like that , so can you please assign this task to me

**Comment by aniket0608** [comment]
Ready to work on that please assign this to me

**Comment by Mugdhashrivastava** [comment]
interested

**Comment by harshsingh-io** [comment]
i know the **optimized** version of **fibonachi series.** can you please assign me for this?

**Comment by trisha217** [comment]
please assign me this issue sir

**Comment by nishus0509** [comment]
i have good understanding of data structures and algorithm please assign this issue to me

**Comment by Niketdeshmukh** [comment]
I would love to work on this issue, can you assign this to me ?
