### ISSUE TITLE
Need test cases for many of the Algorithms.

### ISSUE THREAD

**Issue by debasishbsws** [TheAlgorithms/Java#3594]
There are many algorithm files for which there is no dedicated test file written instead there is a `main()` function that has a demonstration for that.

Write test files for the Algorithms that do not have one. So that any bad changes in that algorithm can be identified.

**Comment by debasishbsws** [comment]
You do not have to be assigned to work on this issue. You can just make a PR. just make sure there is no prior PR for the same test.java file.

**Comment by Teuton-Roy** [comment]
Assign this task to me.

**Comment by debasishbsws** [comment]
> Assign this task to me.

Just do it. No need to be assigned. Make proper changes and made a PR

**Comment by redhairrs** [comment]
You can assign this task to me I have a 1277 Rating on codeforces and can do this task very well for you...

**Comment by debasishbsws** [comment]
@redhairrs it doesn't require code force rating.  But you can try.

**Comment by Mehrotra01** [comment]
I would really like to contribute in these type  of issues can you please assign this task to me

**Comment by debasishbsws** [comment]
@Mehrotra01 go for it. No need to be assigned.  Just check previous PR's

**Comment by debasishbsws** [comment]
@siriak This issue should continue open.

**Comment by debasishbsws** [comment]
There are multiple folks making the algorithm file inside `src/test` and also not using `Junit`. Do they are not understanding what I have said? Should I change my words here?

**Comment by npetronio1** [comment]
@debasishbsws hello, I would like to work on some of the Test algorithms. I will created a PR with the work that I have done.

**Comment by shlokam** [comment]
Hello,
I have added test cases and created a PR for the same.

**Comment by hyeonmin2** [comment]
#3716
