### ISSUE TITLE
Convert GitHub issue templates to issue forms

### ISSUE THREAD

**Issue by siriak** [TheAlgorithms/Java#3637]
An example can be found [here](https://github.com/TheAlgorithms/Go/pull/581#pullrequestreview-1152223321)

**Comment by AlexandreVelloso** [comment]
Can you assign it to me? thanks in advance

**Comment by sasankaweera123** [comment]
Can you assign me to this?

**Comment by Shadow-of-sundered-star** [comment]
Hey , I'm new to open source , the template in the example is same as the template in the current issue so should i just copy paste the code with necessary edits ?
