### ISSUE TITLE
Best Optimised Version Of Fibonacci Series

### ISSUE THREAD

**Issue by harshsingh-io** [TheAlgorithms/Java#3671]
**Is there any optimised verison of Fibonacci Series with Linear Time Complexity O(1)**
There is way to solve Fibonacci Series in **Linear Time Complexity O(1)**.

**Comment by Deepanshu1008** [comment]
please assign met this issue

**Comment by trisha217** [comment]
Please assign this issue to me sir

**Comment by debasishbsws** [comment]
Issue is resolved

**Comment by Aayush2111** [comment]
I have Optimized Fibonacci Series using Binet's Formula
Can anyone review it please?
