### ISSUE TITLE
Sieve of Eratosthenes Algorithm

### ISSUE THREAD

**Issue by prakhar2407** [TheAlgorithms/Java#3723]
I would like to add the Sieve of Eratosthenes algorithm to the repo

**Comment by Niketdeshmukh** [comment]
I can solve this problem can you assign it to me?

**Comment by debasishbsws** [comment]
go for it

**Comment by debasishbsws** [comment]
https://github.com/TheAlgorithms/Java/blob/e96f567bfc6e980dc5c4c48ccf185d7f7c7108ab/src/main/java/com/thealgorithms/others/SieveOfEratosthenes.java
The algorithm is already present. You can Write some Test that is missing for this Algorithm
