### ISSUE TITLE
I would like to add problem "Generate IP Address"

### ISSUE THREAD

**Issue by Dipesh049** [TheAlgorithms/Java#3740]
**Is your feature request related to a problem? Please describe.**
It is a very good problem asked in amazon. and i found it very interesting when i approached it. 

**Describe the solution you'd like**
i would like to add the recursive solution along with explanation.

**Additional context**

**Comment by Gagan1729-droid** [comment]
Please assign this issue to me

**Comment by siriak** [comment]
What is the problem in generating an IP (v4 probably?) address? It's just 4 numbers 0 to 255
