### ISSUE TITLE
 After the merger did not solve the conflict

### ISSUE THREAD

**Issue by jackzhao29** [TheAlgorithms/Java#376]
HashMap.java conflict not resolved

**Comment by varunu28** [comment]
@jackzhao29 Can you please mention the PR # ?

**Comment by jackzhao29** [comment]
of course can

**Comment by jackzhao29** [comment]
@varunu28 of course can

**Comment by varunu28** [comment]
@jackzhao29 Please mention the PR #

**Comment by jackzhao29** [comment]
@varunu28 Has been submitted to the merger
