### ISSUE TITLE
[OTHER] updating sort algorithm parameters to Generic type <T>

### ISSUE THREAD

**Issue by Tabbygray** [TheAlgorithms/Java#3767]
### What would you like to share?

in [sorts] package, algorithms offer .sort() function. 
most of them has input parameter as generic type Comparable<T>, but some of them supports int[ ] only. 

※algorithms that sort int[ ] only = [BinaryInsertionSort, BucketSort, DNFSort, OddEvenSort, PigeonHoleSort, RadixSort]
exception : beadsort (algorithm cannot sort negative int / String sort)

how do you think about updating algorithm's parameter type to Generic type <T>?

**Comment by Regyl** [comment]
@siriak I'd like to do that, could you assign to me?
