### ISSUE TITLE
LFUCache  unexpected result

### ISSUE THREAD

**Issue by supertonyliu** [TheAlgorithms/Java#3781]
### Description

https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/datastructures/caches/LFUCache.java
function:   private void addNodeWithUpdatedFrequency(Node node)
line 104 
I think 104 code line:   
node.previous = temp.previous;  
need change:
 temp.previous = node;

### Excepted behavior

result ok!

**Comment by siriak** [comment]
Thanks for reporting, could you create a PR with the proposed change?

**Comment by siriak** [comment]
Fixed
