### ISSUE TITLE
Adding Word Suggest System

### ISSUE THREAD

**Issue by shivu2002a** [TheAlgorithms/Java#3786]
### What would you like to Propose?

I found out that the Word Suggest System problem is not implemented. I'd like to contribute.

**Word Suggest Problem Statement:**

Given an array of strings _products_ and a string _searchWord_

Design a system that suggests _productNames_ from _products_ after each character of _searchWord _ is typed. 
> Suggested products should have a common prefix with _searchWord_.
> Return a list of lists of the suggested products after each character of _searchWord_ is typed.

### Issue details

**Example:**
_products = {"man", "mango", "manage", "map", "you", "match", "manuscript", "monk"}_
_searchword = "man"_

When _m_ is typed
> man, mango, manage, map, match, manuscript, and monk should be suggested

When _a_ is typed
> man, mango, manage, map, match, and manuscript should be suggested

When _n_ is typed
> man, mango, manage, and manuscript should be suggested

Finally, the 2D list of strings is returned
> {
  {man, mango, manage, map, match, manuscript, monk },
  {man, mango, manage, map, match, manuscript },
  {man, mango, manage, manuscript }
}

This can be solved by making use of Trie data structure.

Thank you.

**Comment by siriak** [comment]
It's already implemented here https://github.com/TheAlgorithms/Java/blob/e96f567bfc6e980dc5c4c48ccf185d7f7c7108ab/src/main/java/com/thealgorithms/others/Implementing_auto_completing_features_using_trie.java
