### ISSUE TITLE
Adding Order Agnostic Binary Search

### ISSUE THREAD

**Issue by ThisIsNishanth** [TheAlgorithms/Java#3790]
### What would you like to Propose?

Order Agnostic Binary Search Algorithm on 1-D Arrays.

### Issue details

Order Agnostic Binary Search algorithm is used when we do not know whether the given array is descending or ascending. 

Example: [5,4,3,2,1] 
I can write clean code to find out whether the array is ascending or descending and apply Binary Search on it.

Please assign this to me as I have worked on this problem before.

**Comment by ThisIsNishanth** [comment]
Hey, I have created a pull request for this idea in which I have 1 commit along with the code.

**Comment by siriak** [comment]
Which PR is that?

**Comment by shahabrar7746** [comment]
hey @siriak  i have added a PR for this issue. https://github.com/TheAlgorithms/Java/pull/3852

**Comment by dineshlalam15** [comment]
!assign

**Comment by HumbleFool830** [comment]
@siriak I have raised a pr on this issue .#3882 and added clean code and test cases also.

**Comment by Swarga-codes** [comment]
Is this issue open? If so, can I work on it?

**Comment by siriak** [comment]
It's done
