### ISSUE TITLE
The user Interface

### ISSUE THREAD

**Issue by Shivaa10** [TheAlgorithms/Java#3802]
### What would you like to share?

The UI of the vs code in the web is very white .The code base and file base is not differenciable at all.

**Comment by siriak** [comment]
What do you mean by `VS Code for web`? It doesn't seem like it has something to do with this project, but rather with your IDE or system configuration

**Comment by Shivaa10** [comment]
Sorry, sir you are right.It is actually the default settings of the color
theme of the vs code ide on the web  i.e gitpod light .Being a 4 yrs old
user of the VS code i could say that the file and folder division of the
gitpod light theme is very annoying .It seems like everything is placed on
a white paper .It could be more User friendly if you could do something to
file & folder  division of the Ide ,something like making it more greyish
that would probably help in distinguishing the code division with the file
& folder division.

**Comment by siriak** [comment]
Closing this issue because it's not about this project, but rather a VS Code configuration issue
