### ISSUE TITLE
[FEATURE REQUEST] Adding Bellman–Ford algorithm

### ISSUE THREAD

**Issue by NicoNovi9** [TheAlgorithms/Java#3804]
### What would you like to Propose?

i would like to add the Bellman–Ford algorithm.

### Issue details

Bellman–Ford algorithm finds shortest paths from a starting node to all nodes of the graph. The code assumes that the graph is stored as an edge list _edges_ that consists of tuples of the form (a,b,w), meaning that there is an edge from node a to node b with weight w.

**Comment by siriak** [comment]
It's already implemented here https://github.com/TheAlgorithms/Java/blob/e96f567bfc6e980dc5c4c48ccf185d7f7c7108ab/src/main/java/com/thealgorithms/datastructures/graphs/BellmanFord.java

**Comment by NicoNovi9** [comment]
sorry, I didn't see it
