### ISSUE TITLE
[FEATURE REQUEST] Frontend website for Repository

### ISSUE THREAD

**Issue by thevinitgupta** [TheAlgorithms/Java#3806]
### What would you like to Propose?

A simple website that displays the various algorithms based on the topic would be great for user experience.

Using something like NextJS or ReactJS with the Github Data API, this can be achieved.
There would be cards based on different folders and the programs list would be shown after clicking on the cards in a different page.

Also, I would love to work on this

### Issue details

Creating a website would provide easier access to algorithms for users

### Additional Information

The Website would look something like this : 
![image](https://user-images.githubusercontent.com/65801700/210969349-cedf1d39-0c04-4b21-a888-a9a4c1173af7.png)

**Comment by siriak** [comment]
The website on your screenshot is **the website**. It is the website of this organization, which also contains algorithms from this repository.

**Comment by thevinitgupta** [comment]
I understand sir
