### ISSUE TITLE
The import java.util.Scanner is never used

### ISSUE THREAD

**Issue by Bahati308** [TheAlgorithms/Java#3808]
### Description

the above method was imported but never used. this can create errors in the code and it is reflected in the code editor(VS Code)

### Steps to reproduce

once the **PowerSum.java** file is opened, the error message pops out

### Excepted behavior

i expected to see the method used

**Comment by Bahati308** [comment]
thanks for this project

**Comment by siriak** [comment]
Thanks for reporting, feel free to make a PR with a fix

**Comment by newbieprogrammer17** [comment]
Hello, I am new to the project. I have done my first commit on above issue. removed the import statement as the scanner class was not in the scope of the problem statement.

**Comment by Bahati308** [comment]
THANKS FOR ALL YOUR EFFORTS ON THIS ISSUE
