### ISSUE TITLE
[BUG] Adding functions for double types in min and max algorithms

### ISSUE THREAD

**Issue by JerseysGet** [TheAlgorithms/Java#3877]
### Description

In the maths algorithms [FindMax.java](https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/maths/FindMax.java), [FindMaxRecursion.java](https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/maths/FindMaxRecursion.java), [FindMin.java](https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/maths/FindMin.java), [FindMinRecursion.java](https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/maths/FindMinRecursion.java) do not contain functions for double types.

### Excepted behavior

FindMax, FindMin, FindMaxRecursion, FindMinRecursion should contain functions to find the maximum and minimum of double types as well, not just for int.

**Comment by JerseysGet** [comment]
I have created a pull request for this [here](https://github.com/TheAlgorithms/Java/pull/3878).

**Comment by siriak** [comment]
Thanks for contributing, but I think they are unnecessary. This project is not intended to be used as a library, and the algorithms can be easily adapted to work with any data type if needed.
