### ISSUE TITLE
Connecting JDBC applications with SSL? 

### ISSUE THREAD

**Issue by SpamhaterAlex** [TheAlgorithms/Java#388]
Hello community, 

I want to ask, if somebody have a hint for me, how to connect jdbc applications with SSL? 
I am using eclipse, and have ca.pem, client.pem, client_key.pem. 
The mysql-server is already configured. 

I just need to make a connection with jdbc using ssl. 
I found this link: 

https://www.ibm.com/support/knowledgecenter/en/SSGU8G_12.1.0/com.ibm.jdbc_pg.doc/ids_jdbc_490.htm 

But I still not understand it :( 

If somebody could help me out, I would be very happy. 
I am using Eclipse as development environment. 

Thank you

**Comment by christianbender** [comment]
@SpamhaterAlex Please ask your question on [stackoverflow](https://stackoverflow.com/)
