### ISSUE TITLE
[BUG] Division by zero in LongDivision

### ISSUE THREAD

**Issue by DavidCed** [TheAlgorithms/Java#3896]
### Description

A test case was written to test the edge case of when the divisor is 0, but the program got stuck in a loop. 

### Issue details
An if-statement checking whether it is a division by zero was added to the divide function and a corresponding test was created in the test class for LongDivision.

### Excepted behavior

When the divide function was run with a division by zero, the program got stuck in a loop. Expected to return a 0 or division by zero exception.

**Comment by siriak** [comment]
Fixed in #3897
