### ISSUE TITLE
[FEATURE REQUEST] String Compression

### ISSUE THREAD

**Issue by Swarga-codes** [TheAlgorithms/Java#3911]
### What would you like to Propose?

I would like to add the string compression algorithm that compresses and returns the size of a string as per the example given below:
Input: 
Here, we take a string of characters,
char[] chars = ["a","a","b","b","c","c","c"]

Output: 6

Explanation: The groups are "aa", "bb", and "ccc". This compresses to "a2b2c3", which has a size of 6. Also, if any character has a single occurence we don't write it as "a1" or "b1" rather we just add that character to the resulting string.

### Issue details

I was going through the strings folder, and didn't find this algorithm and wanted to contribute this algorithm to this repo.

### Additional Information

I was struggling to solve the question based on this on leetcode and finally managed to solve it on my own, that is, a leetcode accepted solution and would love to share this solution and add it to the repo. Thank you!

**Comment by siriak** [comment]
Is it run length encoding? If so, feel free to implement it

**Comment by Swarga-codes** [comment]
My current code returns the encoded length if you want the encoded string I can modify accordingly.

**Comment by siriak** [comment]
Yes, please. The purpose of any encoding is to encode the text.

**Comment by Swarga-codes** [comment]
I modified my algorithm that returns the encoded string and created a pull request for this issue, can you please check?

**Comment by vikash-prem123** [comment]
If this issue has not yet been resolved, could you please allow me to assist?

**Comment by Swarga-codes** [comment]
@siriak I made the necessary changes as u told on the PR, the changes include:
1) Reduce the size of code by dividing the code into smaller functions
2) Removed unnecessary comments
3) Removed the main 
4) Included some Junit test cases for the code which you can access in the tests folder
Can you please check the PR now?

**Comment by Swarga-codes** [comment]
@siriak can you please check, I have made the necessary changes in my PR?
