### ISSUE TITLE
[FEATURE REQUEST] Backtracking algorithms (All combinations)

### ISSUE THREAD

**Issue by TheClerici** [TheAlgorithms/Java#3912]
### What would you like to Propose?

I would like to add the all combinations algorithm!

### Issue details

Although it is already in another repository from the Algorithms group (Python), I was unable to locate it in the folders (Java).

### Additional Information

In this problem, we want to determine all possible combinations of k numbers out of 1 ... n. We use backtracking to solve this problem. 

* Example:
>>> generate_all_combinations(n=4, k=2)
[[1, 2], [1, 3], [1, 4], [2, 3], [2, 4], [3, 4]]

**Comment by siriak** [comment]
I think that's what you are looking for https://github.com/TheAlgorithms/Java/blob/b6563cf37ae7db33e3f3c8ad513acd905353c147/src/main/java/com/thealgorithms/backtracking/Combination.java

**Comment by TheClerici** [comment]
This is the sister repository with the problem I'm talking about, https://github.com/TheAlgorithms/Python/blob/master/backtracking/all_combinations.py lmk to start it!

**Comment by TheClerici** [comment]
Sure, I can do that

**Comment by BamaCharanChhandogi** [comment]
Hey, Please check this PR #4156

**Comment by TheClerici** [comment]
Hello @BamaCharanChhandogi, this PR is already closed as I added a solution for it, I am not a reviewer, I think with that siriak can help out!
