### ISSUE TITLE
[BUG] DIRECTORY.md is not properly formatted.

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Java#3922]
### Description

[`DIRECTORY.md`](../blob/master/DIRECTORY.md) looks really ugly especially at the end.

Perhaps the Python code run in our GitHub Action [directory_workflow.yml](../blob/master/.github/workflows/update_directory.yml#L25) should be replaced by Java code so that contributors to this repo are better able to maintain it.

### Steps to reproduce

1. Click on [`DIRECTORY.md`](../blob/master/DIRECTORY.md) and look.

### Excepted behavior

Users want a readable directory.

**Comment by siriak** [comment]
There are two options:
1. Fix the existing script to format properly
2. Rewrite it in Java so that it formats properly and can be maintained in the future
