### ISSUE TITLE
[BUG] Gitter Link is not Working

### ISSUE THREAD

**Issue by Danish-Belal** [TheAlgorithms/Java#3923]
### Description

While i was trying to get connect with your gitter , the link is not working.

### Excepted behavior

It should redirect me to your gitter

**Comment by siriak** [comment]
Thanks for reporting! We used to have a Gitter chat, but then moved to Discord. You can find the Discord chat badge among the badges at the top of README.md. The paragraph about Gitter is now gone!

**Comment by Danish-Belal** [comment]
Is this repo for GSOC2023 ?

> Thanks for reporting! We used to have a Gitter chat, but then moved to Discord. You can find the Discord chat badge among the badges at the top of README.md. The paragraph about Gitter is now gone!

**Comment by siriak** [comment]
This one is not, you can read more about GSOC23 here https://github.com/TheAlgorithms/Google-Summer-of-Code
