### ISSUE TITLE
[FEATURE REQUEST] Addition of DES to ciphers

### ISSUE THREAD

**Issue by PalAditya** [TheAlgorithms/Java#4167]
### What would you like to Propose?

I feel DES is an important cipher from educational standpoint and thus should be included. Happy to take this up if considered valuable, so please let me know.

### Issue details

Addition of the standard DES Algorithm to Ciphers: https://en.wikipedia.org/wiki/Data_Encryption_Standard

**Comment by siriak** [comment]
Sure, would love to see it!
