### ISSUE TITLE
[FEATURE REQUEST] Round Robin Scheduling

### ISSUE THREAD

**Issue by asifjoardar** [TheAlgorithms/Java#4183]
### What would you like to Propose?

I would like to add the Round Robin Scheduling.

### Issue details

Round Robin Scheduling is a CPU scheduling algorithm in which each process is assigned a fixed time slice or time quantum, and the CPU switches between processes in a circular order. It is called "Round Robin" because of its circular nature.

**Comment by BamaCharanChhandogi** [comment]
I know This algorithm, but how many topics do I calculate? Like I am talking about Waiting Time, TAT, RT, CT!
Thanks
