### ISSUE TITLE
#telusko#navinreddy#10dayschallenge 

### ISSUE THREAD

**Issue by antivirustoai** [TheAlgorithms/Java#4191]
### What would you like to share?

public class Pascalstriangle {
    public static void main(String[] args) {
        int numRows = 5;
        int i,j;
        for(i=0;i<numRows;i++) 
        {
            for(j=0;j<=i;j++) 
            {
                System.out.print(pascal(i,j) + " ");
            }
            System.out.println();
        }
    }
    public static int pascal(int row, int col) 
    {
        if(col==0||col==row) 
        {
            return 1;
        } 
        else 
        {
            return pascal(row-1,col-1)+pascal(row-1,col);
        }
    }
}

**Comment by siriak** [comment]
Please create a pull request with a detailed description of the algorithm instead
