### ISSUE TITLE
[OTHER] Current code style does not look like java code

### ISSUE THREAD

**Issue by oppahansi** [TheAlgorithms/Java#4204]
### What would you like to share?

Hi,

I stumbled on this repository earlier and was exploring its algorithm collection.  
But I was really confused at the beginning. Almost all of the code does not look  
like Java code.  

You introduced this code style with this [merge request](https://github.com/TheAlgorithms/Java/pull/3375).
I was wondering which reasons you had for this?  

Cheers

### Additional information

I would be willing to refactor the code using one of the common code styles, like google code style.

**Comment by siriak** [comment]
Could you explain what specifically doesn't look like standard Java? The PR made a lot of changes, most of which are correcting missing whitespace and enforcing max line length

**Comment by oppahansi** [comment]
I might be a bit biased in this regard due to my preferences.  
Here are some examples I have in mind:  

<details> 
  <summary>Examples code style</summary>
   
KnightsTour.java
```java
if (
	!orphanDetected(count, row, column) &&
	solve(row, column, count + 1)
) {
	return true;
}
```

AES.java
```java
public static BigInteger addRoundKey(
	BigInteger ciphertext,
	BigInteger key
) {
	return ciphertext.xor(key);
}
```

AffineCipher.java
```java
 if (cipher.charAt(i) != ' ') {
                msg =
                    msg +
                    (char) (
                        ((a_inv * ((cipher.charAt(i) + 'A' - b)) % 26)) + 'A'
                    );
```

Fibonacci.java
```java
for (
	int intermediateIndex = 0;
	intermediateIndex < columnsInMatrix1;
	intermediateIndex++
) {
	matrixEntry +=
		matrix1[rowIndex][intermediateIndex] *
		matrix2[intermediateIndex][colIndex];
}

...

int[][] matrixExpResult = matrixMultiplication(
	cachedResult,
	cachedResult
);

... 

return matrixMultiplication(
	Fibonacci.fibMatrix,
	matrixExpResult
);
```

Vigenere.java
```java
result.append(
	(char) (
		(c + key.toUpperCase().charAt(j) - 2 * 'A') %
		26 +
		'A'
	)
);
```

AnyBaseToAnyBase.java
```java
System.out.print(
	"Enter beginning base (between " +
	MINIMUM_BASE +
	" and " +
	MAXIMUM_BASE +
	"): "
);
```
   
</details>

Others:
<details> 
  <summary>Examples others</summary>

Missing whitespaces in for loops  
![Missing whitespaces in for loops](https://i.imgur.com/5rdc5t3.png)  
Missing whitespaces between  
![Missing whitespaces between ){](https://i.imgur.com/MSQtJpq.png)  
C style code blocks  
![C style code blocks](https://i.imgur.com/99OMQe2.png)  
One of many wrongly placed Javadoc comments    
![One of many wrongly placed Javadoc comments](https://i.imgur.com/w8d0yUX.png)

</details>

Apart from these examples, there are also other unconventional "issues":
- order of methods, fields, imports in classes
- no concise use of javadoc / comments through many classes
- variable naming conventions often ignored
- class naming convention sometimes ignored
- urls in javadoc comments not using the html tags
- etc

All of these issues add up at the end.  At least to me. (I am working with java code on a daily basis.)
Does this make sense?

**Comment by siriak** [comment]
I see your point. Unfortunately, we don't have automatic formatting checks like we have in Go repository, that's why it may not be consistent. The PR in question has fixed a lot of issues (empty lines, too long lines, and others), but has also introduced some new that you are pointing out.
Is there a tool that we can run in our CI pipeline to check formatting? If so, could you add it and format the code with it? That'd be ideal.

**Comment by oppahansi** [comment]
AFAIK there are few, I will take a closer look.
