### ISSUE TITLE
[FEATURE REQUEST] DFS and BFS  search algorithms are lack of effective tests and Node class should be decoupled from DFS

### ISSUE THREAD

**Issue by snirt** [TheAlgorithms/Java#4229]
### What would you like to Propose?

- Write DFS and BFS  search algorithms effective tests.
- Write a new Node class in structures  - its should be decoupled from the DFS class.
- Some code refactoring.
-  Support of multiple data types

### Issue details

BreadthFirstSearch.java
- add algorithm tests
- refactor
DepthFirstSearch.java

- write a new test file 
- refactor - mention that this is a recursive solution (in the future add an iterative solution as well)

**Comment by abhisheksharma886** [comment]
Hello, I would like to work on this, can it be assigned to me
