### ISSUE TITLE
[FEATURE REQUEST] Add Sliding Window Problem

### ISSUE THREAD

**Issue by Swarga-codes** [TheAlgorithms/Java#4232]
### What would you like to Propose?

Add a sliding window problem which holds an algorithm that finds the maximum sum of the distinct subarray of a given K size.

### Issue details

You are given an integer array nums and an integer k. Find the maximum subarray sum of all the subarrays of nums that meet the following conditions:

The length of the subarray is k, and
All the elements of the subarray are distinct.
Return the maximum subarray sum of all the subarrays that meet the conditions. If no subarray meets the conditions, return 0.

A subarray is a contiguous non-empty sequence of elements within an array.

### Additional Information

An example following the same would be: 
Input: nums = [1,5,4,2,9,9,9], k = 3
Output: 15
Explanation: The subarrays of nums with length 3 are:
- [1,5,4] which meets the requirements and has a sum of 10.
- [5,4,2] which meets the requirements and has a sum of 11.
- [4,2,9] which meets the requirements and has a sum of 15.
- [2,9,9] which does not meet the requirements because the element 9 is repeated.
- [9,9,9] which does not meet the requirements because the element 9 is repeated.
We return 15 because it is the maximum subarray sum of all the subarrays that meet the conditions

**Comment by mohamedelghaouth** [comment]
Hello, I would like to work on this, can it be assigned to me, please

**Comment by siriak** [comment]
@Swarga-codes would you like to do it yourself? If no, I can assign @mohamedelghaouth

**Comment by Swarga-codes** [comment]
Yes I would love to do it!

**Comment by abhisheksharma886** [comment]
Yes i would like to do it.

**Comment by Swarga-codes** [comment]
@siriak can you check I created the PR about a week ago.

**Comment by Swarga-codes** [comment]
@siriak I was having issues with clang but now I resolved it and removed the merge conflicts as well, can you check my PR #4322?

**Comment by siriak** [comment]
Done
