### ISSUE TITLE
Change the clang linter-formatter configuration to allow line-under-line method chaining

### ISSUE THREAD

**Issue by snirt** [TheAlgorithms/Java#4239]
configure the clang linter-formatter to allow the left-side format in the attached image:
![Screenshot from 2023-07-10 13-32-18](https://github.com/TheAlgorithms/Java/assets/20107490/59f41c05-008e-453f-ba0a-3f99f6f5fecb)
This format helps with readability

_Originally posted by @snirt in https://github.com/TheAlgorithms/Java/issues/4230#issuecomment-1628688602_

**Comment by Prakhar1701** [comment]
I want to work on this issue, please assign it to me.

**Comment by Prakhar1701** [comment]
Seems that this issue "configure the clang linter-formatter to allow the left-side format in the attached image" is already been resolved.

**Comment by siriak** [comment]
Where has this been resolved?
