### ISSUE TITLE
The project structure has different styles

### ISSUE THREAD

**Issue by nikitap492** [TheAlgorithms/Java#426]
The project structure has different styles. For instance, there are 3 data structure folders now (one of them in python style). It will be good to make one style, because it easy for people how understand project. Futhermore, it is not acceptable to create class with uncapitalize name by the java conventions (like in Compression). May be it is just legacy code, but It should be denied in future

**Comment by kezhenxu94** [comment]
Agree! It's very messy, and conflicts are also committed like this: https://github.com/TheAlgorithms/Java/blob/master/DataStructures/HashMap/HashMap.java

**Comment by christianbender** [comment]
@nikitap492 I fixed it. Now we have only one directory for data structures.
