### ISSUE TITLE
RedBlackBST Implementation by Java

### ISSUE THREAD

**Issue by jack870131** [TheAlgorithms/Java#427]
I would like to add the RedBlackBST.

**Comment by RishiPrakash** [comment]
I would like to take this issue, I will write the code for it.

**Comment by Mudra01** [comment]
would like to contribute to this isuue.

**Comment by varunu28** [comment]
@Mudra01 The code has already been added to the repo. [RedBlackBST](https://github.com/TheAlgorithms/Java/blob/master/Data%20Structures/Trees/RedBlackBST.java)
