### ISSUE TITLE
Feat: Add "Remove outermost Paranthesis" question in String Section

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [TheAlgorithms/Java#4289]
### What would you like to Propose?

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

 This Question Should add "Remove outermost Paranthesis" Question.

### Issue details

"Valid Parentheses" question is available but this important question isn't available.

**Example of Remove outermost Paranthesis:**
_Input: s = "(()())(())(()(()))"
Output: "()()()()(())"_

**Comment by siriak** [comment]
This is a coding problem, not a computer science algorithm. We don't usually add such problems.
