### ISSUE TITLE
Feat: add "Middle of the Linked List" question in Linked List. 

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [TheAlgorithms/Java#4290]
### What would you like to Propose?

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

Added "Middle of the Linked List" question.

### Issue details

**### Example of Middle of the Linked List:**
_**Input: head = [1,2,3,4,5,6]
Output: [4,5,6]**_

**Comment by siriak** [comment]
It seems that it's already implemented here https://github.com/TheAlgorithms/Java/blob/1ef5208b75553778c539f54642525b3644c67d4f/src/main/java/com/thealgorithms/datastructures/lists/SinglyLinkedList.java#L62

**Comment by BamaCharanChhandogi** [comment]
oh! Yes

**Comment by BamaCharanChhandogi** [comment]
Hi @siriak, I have a question Why Bit manipulation Section is not available in Java repo?

**Comment by siriak** [comment]
Because no one has implemented anything in this section, so far

**Comment by BamaCharanChhandogi** [comment]
Can I start a Bit manipulation section?
