### ISSUE TITLE
Feat: add "Is Even" in Bit Manipulation Section

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [TheAlgorithms/Java#4297]
### What would you like to Propose?

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### Issue details

**Is Even:** Check any number Odd or Even!

**Comment by shahabrar7746** [comment]
@siriak hey I have raised a PR for this issue, mind if you review it https://github.com/TheAlgorithms/Java/pull/4300

**Comment by shahabrar7746** [comment]
@siriak i have raised a PR for testacases with some changes in main code but some error in jobs. can you please help me
https://github.com/TheAlgorithms/Java/pull/4304
