### ISSUE TITLE
Add "Binary AND Operator" in BIT Manipulation Section

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [TheAlgorithms/Java#4311]
### What would you like to Propose?

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### Issue details

New Algo add **_Binary AND Operator_**

**Comment by siriak** [comment]
What would the algorithm look like? Working with strings is terribly inefficient for this, and using & operator is not an option because there's no algorithm in this case. Do you have any other ideas?

**Comment by siriak** [comment]
There, they just display the result of 'and' as a string. I don't think we need to add it.
