### ISSUE TITLE
Fet: Added " Numbers Different Signs" algo in Bit Manipulation

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [TheAlgorithms/Java#4316]
### What would you like to Propose?

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### Issue details

Numbers with Different Signs: **Return true if any two numbers have opposite signs; otherwise, return false.**

**Comment by siriak** [comment]
Done
