### ISSUE TITLE
[OTHER] is there any one can explain why SinglyLinkedList extends Node?

### ISSUE THREAD

**Issue by doxxx93** [TheAlgorithms/Java#4326]
### What would you like to share?

```java
public class SinglyLinkedList extends Node {
    private Node head;
    private int size;

    class Node {

    int value;
    Node next;
    }
}
```

### Additional information

I think `LinkedList and Node` is `has-a` relation, not `is-a`.

**Comment by BamaCharanChhandogi** [comment]
### **int value:**
This variable holds the actual data or value that you want to store in the node. It can be of any data type, but in your example, it's an integer (int).

### **Node next:** 
This variable is a reference to the next node in the linked list. It creates the link between nodes, hence the term "linked list." The next variable holds the memory address of the next node, allowing you to traverse the list sequentially.

**Comment by lukasb1b** [comment]
The SinglyLinkedList class extends the Node class, which makes it clearer. The README mentions that these implementations are for learning. This could explain the design choice, even if it's not typically necessary.

**Comment by siriak** [comment]
I think it's not necessary to extend Node here. Feel free to open a PR removing this and then we'll see if it works

**Comment by kaligone** [comment]
I think there is no need to extend node class since we can directly create object of it and can built SLL

**Comment by Jalaj2004** [comment]
There is no need to extend the Node class here, instead to make it even easier you can create the node class inside the SinglyLinkedList class (nested class).

**Comment by doxxx93** [comment]
thank you all guys. How do you guys think about keep this issue opened?

**Comment by Jalaj2004** [comment]
I would like to solve this, can you assign it to me

**Comment by kaligone** [comment]
In which code this issue is?

**Comment by doxxx93** [comment]
> In which code this issue is?

In data structures such as SinglyLinkedList

**Comment by kaligone** [comment]
> > In which code this issue is?
> 
> In data structures such as SinglyLinkedList

Can you ping the exact code link?

**Comment by doxxx93** [comment]
> > > In which code this issue is?
> > 
> > 
> > In data structures such as SinglyLinkedList
> 
> Can you ping the exact code link?

https://github.com/TheAlgorithms/Java/pull/4334

ah this pr resolved my issue, I don't know why the pr was not written with resolove this issue

**Comment by doxxx93** [comment]
Resolved by https://github.com/TheAlgorithms/Java/pull/4334
