### ISSUE TITLE
Fet: Rotate a LinkedList

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [TheAlgorithms/Java#4332]
### What would you like to Propose?

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### Issue details

Rotate of a Linked List algo should be added

**Comment by Imbiber** [comment]
Hey I am very new to contributing and need someone help. I see this is the issue , so do I have to provide with an algorithm on how to rotate a linked list . If yes I can do provide with the algorithm. And If I misunderstood the issue section can someone most humbly correct me.

**Comment by siriak** [comment]
This is already implemented here https://github.com/TheAlgorithms/Java/blob/40a051505400ebd1999148da48802caca185de34/src/main/java/com/thealgorithms/datastructures/lists/RotateSinglyLinkedLists.java
