### ISSUE TITLE
[FEATURE REQUEST] Adding geometric mean in math

### ISSUE THREAD

**Issue by lukasb1b** [TheAlgorithms/Java#4338]
### What would you like to Propose?

I did not see a geometric mean function in maths. 
I added a test feature in the attachment I obviuously would change it according to the rules of the repository if assigned to me. 

### Issue details

Missing geometric mean function in maths src/main/java/com/thealgorithms/maths

### Additional Information

public class test {
    public static void main(String[] args) {
        int[] test = {3,4};
        System.out.println(geometric_mean(test));
    }

    public static double geometric_mean(int[] num) {
        int result=0;
        for(int i:num){
            result+=i*i;
        }

        return Math.pow(result,1.0/ num.length);
    }
}

**Comment by punit324** [comment]
Hi @lukasb1b ,
The method you have proposed for geometric mean is seems to be wrong.
Correct formula is,
GM = (x₁ · x₂ · ... · xₙ)1/n
So,
`public static double geometric_mean(int[] num) {
    int result=1;
    for(int i:num){
        result*=i;
    }

    return Math.pow(result,1.0/ num.length);
}`

**Comment by lukasb1b** [comment]
Yeah your right @punit324  i need to multiply. 
Your solution is wrong too you need multiply it by i^2 so its:
public static double geometric_mean(int[] num) {
    int result=1;
    for(int i:num){
        result*=i*i;
    }
    return Math.pow(result,1.0/ num.length);
}

**Comment by lukasb1b** [comment]
Yeah your right @punit324

**Comment by punit324** [comment]
@lukasb1b
Changes are merged into master. You can now close this issue as done.

**Comment by raisahab9125** [comment]
For the code you have to apply the formula in a right manner the appering
code showing the syntax error.
Check out the formula of arithmetic mean.

**Comment by raisahab9125** [comment]
public static void main(String[] args) {
int[] test = {3,4};
System.out.println(geometric_mean(test));
}

public static double geometric_mean(int[] num0) {
    int result=0;
    for(int i*num0){
        result+=i*i;
    }

    return Math.pow(result,1.1/ num0.length);
}
}







The code is ready to move.

**Comment by lukasb1b** [comment]
We already discussed this issue and its fixed and the right algorithm is merged

**Comment by punit324** [comment]
@raisahab9125 I've used formulas from wiki.
Here's the links.
[Arithmetic Mean](https://en.wikipedia.org/wiki/Arithmetic_mean)
[Geometric Mean](https://en.wikipedia.org/wiki/Geometric_mean)
[Harmonic Mean](https://en.wikipedia.org/wiki/Harmonic_mean)
