### ISSUE TITLE
Fet: Add Single Bit Manipulation Operations

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [TheAlgorithms/Java#4350]
### What would you like to Propose?

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### Issue details

Single Bit Manipulation Operations:
want to add 3 functionalities **GetBit, SetBit, and ClearBit.**

**Comment by peeplika** [comment]
hey i want to work on this , can it be assigned to me ?

**Comment by BamaCharanChhandogi** [comment]
Hi, @lukasb1b,
All functions should be included in one file named 'Single Bit Manipulation,' like this. That would be better.

**Comment by vil02** [comment]
I would rather suggest to create a class `BitArray` (with length passed in the constructor). The underlying data type should be `int[]` or `char[]` (maybe the `BitArray` should be a _generic type_?) - I am not sure what is better. Some benchmark should be performed.

Such class should have methods like `SetBit`, `ClearBit`, `FlipBit` etc.

Honestly that would be a quite fun task - I can support you here.

The interesting thing: this will not be an _utility class_!

**Comment by BamaCharanChhandogi** [comment]
That's a really great idea.
I will also support. Go on.
