### ISSUE TITLE
CircleLinkList has a problem,i think

### ISSUE THREAD

**Issue by picturetxl** [TheAlgorithms/Java#436]
public void display()
    {
        Node<E> current=head;
        for (int i = 1; i <= size; i++) {
            System.out.println(current.next.value);
            current=current.next;
        }
    }

    public static void main(String[] args)
    {
        CircleLinkList<String> cl= new CircleLinkList<>();
        cl.append("hello");
        cl.append("world");
        cl.append("and");
        cl.append("java");

        cl.display();
        // System.out.println("hello java");
    }

/**OutPut:   Is it wrong? i have no idea 
java
null
java
null
*/

**Comment by Skhwan** [comment]
would you mind to let me work on this?

**Comment by Skhwan** [comment]
I agree that there's something wrong with this one. And I also found that the remove method doesn't work properly, it doesn't decrease the link size.

would you mind if I work on this one?
