### ISSUE TITLE
Fet: Missing Postfix Evaluation In Stack section

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [TheAlgorithms/Java#4360]
### What would you like to Propose?

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### Issue details

 Move **Stack Postfix Notation** algo into the Stack section.

**Comment by siriak** [comment]
Is this what you wanted? https://github.com/TheAlgorithms/Java/blob/c54b8cddf38dec124a4b23b4512ea363286d8570/src/main/java/com/thealgorithms/others/StackPostfixNotation.java

**Comment by BamaCharanChhandogi** [comment]
Yes, this file I wanted. 
However, why is this file located in the **Others** section? It should be in the **Stack** section.
I saw many files are located in different sections.

**Comment by siriak** [comment]
Hmm, I guess you could move it to Stack section, this makes sense

**Comment by beradeep** [comment]
I think this issue can be closed now
