### ISSUE TITLE
[OTHER] Missing ciphers on Website

### ISSUE THREAD

**Issue by lukasb1b** [TheAlgorithms/Java#4362]
### What would you like to share?

I visited your website and saw that the ciphers implemented in java are not shown on your website. For example the Vigenere cipher there is no java implementation.

### Additional information

Example:
Website: https://the-algorithms.com/de/algorithm/vigenere-cipher
existing Code in java: https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/ciphers/Vigenere.java

**Comment by siriak** [comment]
That's odd. Vigenere is present in DIRECTORY.md
@maltejur could you help with that, maybe you know how website parsing works?
@lukasb1b I suggest you also open this as a bug in the website repository and link to this one
