### ISSUE TITLE
Fet: add "Two Sum Problem" 

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [TheAlgorithms/Java#4363]
### What would you like to Propose?

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### Issue details

Two Sum: `Input:` nums = [2,7,11,15], target = 9  
`Output:` [0,1]

Three sum is available, but two sum is missing. The algorithm should have a time complexity of O(n).

**Comment by Manan-09** [comment]
Hi @BamaCharanChhandogi , I would like to contribute solution for this problem
