### ISSUE TITLE
Fet : Enhance UniquePaths problem in DP

### ISSUE THREAD

**Issue by Manan-09** [TheAlgorithms/Java#4369]
### What would you like to Propose?
Regarding [Uniquepaths](https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/dynamicprogramming/UniquePaths.java)
We should generalised the implementation, instead of checking if answer is correct or not , it should return the correct answer. We can write testcases separately to check if program is working correctly or not.

Time complexity mentioned in comments for first approach is wrong  , its mentioned O(n) but it will be O(n*m)

Instead of directly making DP of n , we can create DP of size n or m , whatever is smaller

### Issue details

Current implementation checks if DP table finds the answer correctly or not, I think it should be generalised implementation which just gives answer rather checking the answer.

Time complexity mentioned in comments for first approach is wrong  , its mentioned O(n) but it will be O(n*m)

**Comment by siriak** [comment]
Done
