### ISSUE TITLE
[FEATURE REQUEST] <Binary Search On Answer>

### ISSUE THREAD

**Issue by Atreya-112** [TheAlgorithms/Java#4370]
### What would you like to Propose?

Some problems require a technique called "binary search on answer" to produce correct value without exceding time limit.
I have some sample problems . I think we should add a repository related to binary search problems and I could help with that. 
If you think a repository should be added please allow me to fix this issue.

### Issue details

For example take this problem for instance : https://leetcode.com/problems/koko-eating-bananas/description/ 
This could be solved by binary search on answer in optimal time and in O(n^2) time by brute.

**Comment by Atreya-112** [comment]
I could also be added in the searches module. Please assign me this issue.

**Comment by siriak** [comment]
Hi, we do not add leetcode problems
