### ISSUE TITLE
Feat: add "4-Sum Problem" 

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [TheAlgorithms/Java#4374]
### What would you like to Propose?

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

### Issue details

Two sum Problem, Three sum Problem is done. Four sum Problem is missing.
Input: nums = [1,0,-1,0,-2,2], target = 0
Output: [[-2,-1,1,2],[-2,0,0,2],[-1,0,0,1]]

**Comment by ankity26** [comment]
#4377

**Comment by a-kamshishi** [comment]
I want to be assigned this problem I can provide effecient solutions for it

**Comment by mouss3abbb** [comment]
I want to be assigned this problem I can provide effecient solutions for it

**Comment by BamaCharanChhandogi** [comment]
Free feel to raise PR. 
We will check.

**Comment by HimanshuMahto** [comment]
I made a PR for this please check it @BamaCharanChhandogi

**Comment by mouss3abbb** [comment]
@BamaCharanChhandogi I raised a PR. Feel free to review it

**Comment by vil02** [comment]
There are currently 5 pull-requests regarding this issue:
- #4375,
- #4377,
- #4383,
- #4408,
- #4411.

**Comment by HimanshuMahto** [comment]
So which one is going to be merged with the main repo @vil02

**Comment by shaktimaan00** [comment]
Hi @BamaCharanChhandogi please assign me this problem.

**Comment by shreyanshR7** [comment]
please assign me this issue I can provide the better version of code.

**Comment by BamaCharanChhandogi** [comment]
Hello everyone,
We already have 1/2 good PR. 
We have to work on those PR.Your suggestions for these PR would be greatly appreciated.
Thank you.

**Comment by AshBakchod** [comment]
Assign me this problem if no one is working on it

**Comment by Monachaudhary** [comment]
Kindly assign this issue to me. I will solve it in best time and space complexity.

**Comment by md-shamim-ahmad** [comment]
> Kindly assign this issue to me. I will solve it in best time and space complexity.
@Monachaudhary, @AshBakchod, @shaktimaan00 and @shreyanshR7 
You can add your solution code to this [repository](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution)

**Comment by mouss3abbb** [comment]
@BamaCharanChhandogi Feel free to check the last commits

**Comment by abhichauhan824** [comment]
@BamaCharanChhandogi Give me a chance, i will provide you more efficient and readable code

**Comment by md-shamim-ahmad** [comment]
> @BamaCharanChhandogi Give me a chance, i will provide you more efficient and readable code

You can add your solution code to this [repository](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution)

**Comment by abhichauhan824** [comment]
Thanks MD Shamim Ahmad for giving me a chance
.

**Comment by VedantArora18** [comment]
I would like to work on this issue, please assign this to me.

**Comment by debnath003** [comment]
I would like to work on this issue, please assign this to me. It's my first time contributing so please give me a chance @BamaCharanChhandogi

**Comment by BamaCharanChhandogi** [comment]
Hello everyone! This problem has already good PR.
