### ISSUE TITLE
[FEATURE REQUEST] Make `MedianOfRunningArray` generic

### ISSUE THREAD

**Issue by vil02** [TheAlgorithms/Java#4390]
### What would you like to Propose?

I find it a bit odd that the [`MedianOfRunningArray`](https://github.com/TheAlgorithms/Java/blob/fbe348b105a06258a81538023698117e2bb116cb/src/main/java/com/thealgorithms/misc/MedianOfRunningArray.java) only works with integers and returns double as the median. I suggest to make `MedianOfRunningArray` generic accepting any [`Number`](https://docs.oracle.com/javase/8/docs/api/java/lang/Number.html) class.

### Issue details

I suggest to define `MedianOfRunningArray` as

```java
public class MedianOfRunningArray<T extends Number> {
    //...
}
```

and to change the method `insert` to accept objects of `T` and `median` to return `T`.

### Additional Information

Please make sure to include the following test (_rounding down to the integer_):

```Java
var stream = new MedianOfRunningArray<Integer>();
stream.insert(1);
stream.insert(2);
assertEquals(1, stream.median());
```

**Comment by vil02** [comment]
@govardhanshah456 please have a look.

**Comment by govardhanshah456** [comment]
yeah sure!

**Comment by govardhanshah456** [comment]
So the median would be generic too?

**Comment by vil02** [comment]
> So the median would be generic too?

No. I if enough to define it as
```java
public T median() {
    //...
}
```

By the way, `T` is a _bad name_. I would suggest `Value`.
