### ISSUE TITLE
[FEATURE REQUEST] <Optimizing Power (base^exponent)%mod using Binary Exponentiation Algorithm>

### ISSUE THREAD

**Issue by razat-thapar** [TheAlgorithms/Java#4423]
### New Algorithm under https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/maths/
**File Name:** PowerUsingBinaryExponentiation.java
**What ?**  
To calculate **long pow(int base, int exponent, int mod)**  , where mod is a prime number to avoid long overflow issues. 
**Why ?**   
Brute-force approach proposed in /maths/PowerUsingRecursion.java takes Time complexity : O(exponent) time. 
Binary Exponentiation algorithm takes Time Complexity : O(log(exponent)) time  , Aux-Space Complexity: O(log(exponent))

### Link for Algorithm: 
https://en.wikipedia.org/wiki/Exponentiation_by_squaring
**How ?** 
_Recursive Approach:_ 
TC: O(log(exponent))  SC: O(log(exponent)) 
```
public long pow(int base, int exponent, int mod){
        //assumption : given base, exponent, mod, return base^exponent %mod. 
        if(exponent==0){
            return 1%mod;
        }
        //store power
        long p = pow(base,exponent/2,mod);
        if(exponent%2==0){
            //even exponent
            return (p*p)%C;
        }else{
            //odd exponent 
            if(base<0){
                //handle -ve remainder in java due to -ve base.
                return ( ((p*p)%mod) * (mod+ (base%mod)))%mod;
            }else{
                return (((p*p)%mod) * (base%mod))%mod;
            }
        }
    }
```

**Comment by razat-thapar** [comment]
I want to work on this ! Please don't assign it to someone else!

**Comment by SkSadaf** [comment]
I've added `PowerUsingBinaryExponentiation.java` to my pull request titled "Introducing Binary Exponentiation Algorithm #4428. Your feedback is greatly appreciated. Please review it. Thanks!

**Comment by razat-thapar** [comment]
> I've added `PowerUsingBinaryExponentiation.java` to my pull request titled "Introducing Binary Exponentiation Algorithm #4428. Your feedback is greatly appreciated. Please review it. Thanks!

I pointed this out and proposed my algorithm to the maintainers. 
I think I should only do it.

**Comment by SkSadaf** [comment]
I'm new to open-source contributions, and I didn't fully understand the process. Sorry about that.

**Comment by sigma390** [comment]
is it solved or not?
