### ISSUE TITLE
[FEATURE REQUEST]<Spiral Matrix II>

### ISSUE THREAD

**Issue by kirti1211c** [TheAlgorithms/Java#4429]
### What would you like to Propose?

We can add the Spiral Matrix II in other section.
Problem Statement - Given a positive integer n, generate an n x n matrix filled with elements from 1 to n^2 in spiral order.
Example:
Input: n=3
Output: [[1,2,3],[8,9,4],[7,6,5]]
Explanation: 
![image](https://github.com/TheAlgorithms/Java/assets/91460755/26ddeb3c-b5d0-4f59-b210-fb4e94318c82)

### Issue details

The algorithm will fill the matrix in spiral order and store the answer in an array of array and hence, return the same array.

**Comment by ssom01-github** [comment]
@kirti1211c, Hello, I want to be assigned to this, and I can provide you with the best time and space complexity. Kindly assign this to me.

**Comment by zaidiyazdan** [comment]
Hii ,@kirti1211c  I want to work on this issue Will provide the best solution with proper explanation.

**Comment by Monachaudhary** [comment]
Hello, I would like to work on this issue. I can solve it in best time and space complexity. Kindly assign to me.

**Comment by VarshaEkka** [comment]
@kirti1211c Hi, I would like to work on this issue. I can provide the solution to this with the best possible explanation.

**Comment by Ananyasiingh** [comment]
I'd appreciate working on this issue. Kindly assign it to me. I will provide the solution with explanation.

**Comment by Parth152004** [comment]
I can solve this problem in very little time and space complexity. can you assign this problem to me?

**Comment by abhichauhan824** [comment]
Hello @kirti1211c give me a chance, i will provide you more efficient and readable code

**Comment by Akash2866** [comment]
Hii @kirti1211c can you please assign me to this issue. I am looking to contribute in this since last 2 days, thanks.

**Comment by madm234** [comment]
I have already solved this problem in a simplistic manner which is very easy to understand. I can contribute to this .

**Comment by md-shamim-ahmad** [comment]
@madm234 @kirti1211c @Akash2866 @Parth152004 @abhichauhan824 @ssom01-github @Ananyasiingh @VarshaEkka 

You can also add your solution code into this [repository](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution)

**Comment by Akash2866** [comment]
@kirti1211c  I have created a pull request regarding this issue, please look into it,thanks. #4455
