### ISSUE TITLE
[FEATURE REQUEST] <Zigzag Conversion>

### ISSUE THREAD

**Issue by md-shamim-ahmad** [TheAlgorithms/Java#4449]
### What would you like to Propose?

We can add the Zigzag Conversion in misc section.
Problem Statement - Write the code that will take a string and make this conversion given a number of rows in a zigzag pattern.

Input: s = "PAYPALISHIRING", numRows = 4
Output: "PINALSIGYAHRPI"
Explanation:
```
P     I    N
A   L S  I G
Y A   H R
P     I
```

### Issue details

The algorithm wukk convert the given string ```s``` in a  zigzag pattern and store the ans into a string and hence, return the string.

* ```1 <= s.length <= 1000```
* ```s``` consists of English letters (lower-case and upper-case), ```','``` and ```'.'```
* ```1 <= numRows <= 1000```

**Comment by nejim3h** [comment]
Sounds good! I have the Java code for this problem.

**Comment by btshreyas** [comment]
Hi I can contribute to this !!!!

**Comment by jeniljain2811** [comment]
I'd like to formally request assignment to this issue. I believe my java skills align well with the task requirements and can provide a valuable contribution.

**Comment by madm234** [comment]
I would like to contribute to this problem with the most easiest and simplistic approach so that it becomes very easy to understand.

**Comment by md-shamim-ahmad** [comment]
Free feel to raise PR

**Comment by md-shamim-ahmad** [comment]
@nejim3h @madm234 @btshreyas @jeniljain2811 
You can also add your solution code into this [repository](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution)

**Comment by jeniljain2811** [comment]
@md-shamim-ahmad The solution to this problem already exists in the [repository](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution) you mentioned . So shall I make a new file and add my solution there ?

**Comment by md-shamim-ahmad** [comment]
@jeniljain2811 
If your proposed solution is better than the existing solution in terms of **```code size```** or **```time or space complexity ```**, then you can create a PR.

**Comment by TanuSharma0802** [comment]
Hello Sir
Please assign this issue to me. I have good knowledge of java programming language and data structures and algorithms.

**Comment by Monachaudhary** [comment]
Allow me the privilege to tackle this challenge head-on! As an active participant in Hacktoberfest, I am eager to take on the assigned issue. I bring with me a commitment to optimizing solutions with the finest space and time complexities. Rest assured, your task is in capable hands.
