### ISSUE TITLE
[FEATURE REQUEST] <Recursive Binary Search>

### ISSUE THREAD

**Issue by Kstrella** [TheAlgorithms/Java#4457]
### What would you like to Propose?

New Algorithm under
https://github.com/TheAlgorithms/Java/tree/master/src/main/java/com/thealgorithms/searches

File Name Proposed: RecursiveBinarySearch.java

What?
An implementation of Binary search using recursion. 

Why?
Approaching a binary search using recursion helps students better understand how recursion works.

### Issue details

Link for Algorithm:
https://www.geeksforgeeks.org/binary-search/

Best Case: O(1)
Average Case: O(log N)
Worst Case: O(log N)
Space Complexity: O(logN)

**Comment by Kstrella** [comment]
I would like to work on this request

**Comment by abdulmoizsheraz** [comment]
I would like to work on this Feature (notes +code + explanation)

**Comment by aspiringgarv** [comment]
Hye could you plz assign it to me.

**Comment by Lahu19** [comment]
I have solved the issue and PR also raised. Please look ones [FEATURE REQUEST] <Recursive Binary Search> #4457.

**Comment by debnath003** [comment]
I want to work on this issue, could you please assign this to me? @Kstrella

**Comment by VedantArora18** [comment]
I would like to work on this issue, please assign this to me?

**Comment by debnath003** [comment]
Ok @VedantArora18 assigned

**Comment by Kstrella** [comment]
I posted this feature and submitted a PR not long after. Awaiting review.

**Comment by Kstrella** [comment]
https://github.com/TheAlgorithms/Java/pull/4460
