### ISSUE TITLE
[FEATURE REQUEST] <title> Implementation of merge sort using java

### ISSUE THREAD

**Issue by saurabhsingh720** [TheAlgorithms/Java#4466]
### What would you like to Propose?

I want to implement the algorithm of merge sort

### Issue details

![java](https://github.com/TheAlgorithms/Java/assets/106748434/456fbee6-ee3c-474a-873e-0d087f5ad3fe)

**Comment by suyogschavan** [comment]
I would like to work on this issue please assign me this.

**Comment by Manav39** [comment]
I would like to work on this issue as I have recently coded merge sort with recursion and with optimised time and space complexity

**Comment by VedantArora18** [comment]
I would like to work on this issue, please assign this to me.

**Comment by amitaryansingh** [comment]
would you please assign this to me

**Comment by Viraj121** [comment]
I would like to work on this issue, please assign this to me.

**Comment by Pranjal1701** [comment]
i would like to work on this issue as i have recently done this.

**Comment by Ananya01Agrawal** [comment]
I would like to work on this issue please assign this issue to me, i would explain the merge in a more detailed way

**Comment by pawaspy** [comment]
I would like to work on this issue . I have approach to solve this : -To implement the merge sort algorithm, I can follow a divide-and-conquer approach. This involves repeatedly dividing the array into two halves until I reach subarrays with a single element, and then merging these subarrays back together in sorted order.
Please assign me this.

**Comment by TanuSharma0802** [comment]
Hello Sir
Please assign this issue to me. I am good knowledge of java programming language and data structures and algorithms.

**Comment by aipalak** [comment]
I would like to work on this issue, please assign me this . I have a good background in solving problems in Java.

**Comment by Monachaudhary** [comment]
Allow me the privilege to tackle this challenge head-on! As an active participant in Hacktoberfest, I am eager to take on the assigned issue. I bring with me a commitment to optimizing solutions with the finest space and time complexities. Rest assured, your task is in capable hands

**Comment by Shobhit0603** [comment]
As an active participant in Hacktoberfest, I am eager to take on the assigned issue. I bring with me a commitment to optimizing solutions with the finest space and time complexities. Rest assured, your task is in capable hands. Please assign this issue to me.

**Comment by satvikydv** [comment]
I want to work on this issue, please assign me this.

**Comment by md-shamim-ahmad** [comment]
If anyone has plans to create a PR for ```Hacktoberfest 2023```, then there have  [awesome leetcode problem list](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/issues/50)
You can create a pull request of your solution for specific problems in this list.

**Comment by ruchikayadav1408** [comment]
I would like to contribute to this project.Please assign me this project.I will complete this project in just one day by using comments,appropriate variable names and in most efficient way.Greatly looking ahead to work with you.

**Comment by WilliamNian** [comment]
I would like to contribute to this issue.Can you assign this issue to me?

**Comment by Tanishaclippy** [comment]
Can I work on this issue ????

**Comment by SarthakChaudhary46** [comment]
Is it still open? Shall I work on it?
