### ISSUE TITLE
[FEATURE REQUEST] <title>Prim's Algorithm

### ISSUE THREAD

**Issue by Shanukumar2929** [TheAlgorithms/Java#4474]
### What would you like to Propose?

Algorithm to find the Minimum Spanning Tree of  a graph using Prim's algorithm.
The working of Prim’s algorithm can be described by using the following steps:

Step 1: Determine an arbitrary vertex as the starting vertex of the MST.
Step 2: Follow steps 3 to 5 till there are vertices that are not included in the MST (known as fringe vertex).
Step 3: Find edges connecting any tree vertex with the fringe vertices.
Step 4: Find the minimum among these edges.
Step 5: Add the chosen edge to the MST if it does not form any cycle.
Step 6: Return the MST and exit.

I want to implement these steps in Java

### Issue details

Algorithm to find the Minimum Spanning Tree of  a graph using Prim's algorithm.
The working of Prim’s algorithm can be described by using the following steps:

Step 1: Determine an arbitrary vertex as the starting vertex of the MST.
Step 2: Follow steps 3 to 5 till there are vertices that are not included in the MST (known as fringe vertex).
Step 3: Find edges connecting any tree vertex with the fringe vertices.
Step 4: Find the minimum among these edges.
Step 5: Add the chosen edge to the MST if it does not form any cycle.
Step 6: Return the MST and exit.

I want to implement these steps in Java

**Comment by Shanukumar2929** [comment]
I want to work on these issue.Please assign these issue to me under hacktoberfest.

**Comment by Ananya01Agrawal** [comment]
I will like to work on this issue please assign this issue to me, and i would explain with the help of images

**Comment by PRONOBITA** [comment]
@Shanukumar2929 Please assign me this issue.I will complete this project in one day by using comments and appropriate variable names and in most efficient way.Looking ahead to work with you.

**Comment by TanuSharma0802** [comment]
Hello Sir
Please assign this issue to me. I am good knowledge of java programming language and data structures and algorithms.

**Comment by Monachaudhary** [comment]
Allow me the privilege to tackle this challenge head-on! As an active participant in Hacktoberfest, I am eager to take on the assigned issue. I bring with me a commitment to optimizing solutions with the finest space and time complexities. Rest assured, your task is in capable hands

**Comment by KunjMaheshwari** [comment]
Please ALLOW me to work on this issue. I checked it and WORKING Fine in my Laptop.

**Comment by ruchikayadav1408** [comment]
I would like to contribute to this project.Please assign me this project.I will complete this project in just one day by using comments,appropriate variable names and in most efficient way.Greatly looking ahead to work with you.
