### ISSUE TITLE
[FEATURE REQUEST] <title>KRUSKAL'S ALGORITHM

### ISSUE THREAD

**Issue by Mrigendra1-Singh** [TheAlgorithms/Java#4476]
### What would you like to Propose?

I want to propose Kruskal's Algorithm.
Kruskal's Algorithm is used to find the minimum spanning tree for a connected weighted graph. The main target of the algorithm is to find the subset of edges by using which we can traverse every vertex of the graph. It follows the greedy approach that finds an optimum solution at every stage instead of focusing on a global optimum.

### Issue details

I want to propose Kruskal's Algorithm.
Kruskal's Algorithm is used to find the minimum spanning tree for a connected weighted graph. The main target of the algorithm is to find the subset of edges by using which we can traverse every vertex of the graph. It follows the greedy approach that finds an optimum solution at every stage instead of focusing on a global optimum.

**Comment by Mrigendra1-Singh** [comment]
Hi , Please assign me this Issue

**Comment by Mrigendra1-Singh** [comment]
Hi , Please assign me this Issue

**Comment by PRONOBITA** [comment]
@Mrigendra1-Singh Please assign me this issue.I will complete this issue in one day by using comments and appropriate varaible names and in most efficient way.Looking ahead to work with you.

**Comment by TanuSharma0802** [comment]
Hello Sir
Please assign this issue to me. I am good knowledge of java programming language and data structures and algorithms.

**Comment by TanuSharma0802** [comment]
Hello Sir
Please assign this issue to me. I have good knowledge of java programming language and data structures and algorithms.

**Comment by Monachaudhary** [comment]
Grant me this Hacktoberfest task; I assure swift and efficient resolution with optimal space-time complexity!

**Comment by krupalitandel1** [comment]
hello, I would like to contribute to this project please assign me this issue

**Comment by ruchikayadav1408** [comment]
I would like to contribute to this project.Please assign me this project.I will complete this project in just one day by using comments,appropriate variable names and in most efficient way.Greatly looking ahead to work with you.
