### ISSUE TITLE
[FEATURE REQUEST] Vernam Cipher

### ISSUE THREAD

**Issue by amansheoran15** [TheAlgorithms/Java#4478]
### What would you like to Propose?

I'd like to implement vernam cipher for cipher folder.

### Issue details

Currently vernam cipher is missing in ciphers folder, I'd like to implement it.

**Comment by krupalitandel1** [comment]
Hey there I would like to contribute to this project, please assign me this issue

**Comment by Rohxn16** [comment]
I want to work on this issue

**Comment by vil02** [comment]
@amansheoran15 are you working on this? I could not find your PR. If not, please inform us. It seems that @krupalitandel1 and @Rohxn16 want do do it.

**Comment by amansheoran15** [comment]
I was waiting for approval to do this , I'll do this

**Comment by vil02** [comment]
> I was waiting for approval to do this , I'll do this

@amansheoran15 great! When you will be ready, please mention me in the PR. Please make sure to add tests of your implementation (and do not add the `main` method to your class). Some good PR to look at:
- #4456,
- #4465.

**Comment by amansheoran15** [comment]
I'm not able to run the code , it says to upgrade version to 17 , I use Java SDK 16. 
Also how to test code without main ? I'm confused

**Comment by vil02** [comment]
I guess you will add tests for your class like `VernamCipherTest.java`. You can type in the console (in the root of this project) something like

```shell
mvn test
```

or
```shell
mvn test -Dtest=VernamCipherTest
```
just to test your implementation.

If you have problems with creating a local environment, you can always use [gitpod](https://gitpod.io/#https://github.com/TheAlgorithms/Java) - this repo is setup to work there.

**Comment by Rohxn16** [comment]
I wanna work on this is one, is it available now?

**Comment by vil02** [comment]
> I wanna work on this is one, is it available now?

I think @amansheoran15 is working on it.
