### ISSUE TITLE
Kruskal's Algorithm 

### ISSUE THREAD

**Issue by warsiKamran** [TheAlgorithms/Java#4482]
### What would you like to Propose?

I am writing to express my interest in contributing to the Kruskal Algorithm Open Source Project hosted on GitHub. After thoroughly examining the project and understanding its objectives, I am excited to propose my contributions to help improve and enhance this valuable resource. 
The Kruskal Algorithm is a fundamental algorithm in the field of graph theory and is widely used for finding the Minimum Spanning Tree (MST) in a connected, undirected graph. A well-maintained and efficient Kruskal Algorithm implementation is crucial for various applications, such as network design, clustering, and optimization.

### Issue details

Extend the existing Kruskal Algorithm to handle weighted graphs with negative edge weights by implementing the Kruskal++ Algorithm. This new implementation will allow the algorithm to find the Minimum Spanning Tree even in scenarios where negative weights are present, providing greater versatility for users.

**Comment by garv-jain1** [comment]
can i work on this issue?

**Comment by soam1** [comment]
Hello there, I would like to write this extended Kruskal algorithm. I hope you would assign this issue to me.

**Comment by Ananya01Agrawal** [comment]
Hello , I would like to write this extended Kruskal algorithm and would explain in detail . I hope you would assign this issue to me.

**Comment by PRONOBITA** [comment]
@warsiKamran.I would like to contribute to this issue.I will explain it in very easy and detailed manner using comments and appropriate variables names.I will start from brute force to most efficient way.Looking ahead to work with you.
