### ISSUE TITLE
Greedy Algorithm Implementations and Explanations

### ISSUE THREAD

**Issue by SanketPatil7467** [TheAlgorithms/Java#4493]
### Addition of Greedy Algorithms to repository.
I propose the addition of a collection of Greedy Algorithms to the repository. **Greedy algorithms** are fundamental in solving various optimization problems by making locally optimal choices at each step, ultimately aiming for a global optimum.

There are many greedy algorithms such as
1. Activity Selection
2. Fraction Knapsack
3. Job Sequencing
4. Dijkstra's Algorithm
5. Merge Interval 
6. Greedy Coin Change

I would like to give a solution that provides an implementation of above greedy algorithms.

I would like to work on this issue . Please assign it to me.

### Algorithms and Approaches

1. Activity Selection:
> The Activity Selection greedy approach selects activities based on their finish times, maximizing the number of non-overlapping activities. It's important for efficient scheduling and resource allocation in various domains, optimizing the utilization of limited resources.

2. Fraction Knapsack:
> The Fractional Knapsack greedy approach prioritizes items based on their value-to-weight ratio, optimizing value while considering weight constraints. It's crucial for efficient resource allocation and decision-making

3. Job Sequencing:
> Job Sequencing greedy approach prioritizes jobs based on their deadlines and profits, optimizing profit within deadline constraints. It's crucial for efficient task scheduling and maximizing gains in job-oriented scenarios.

4. Dijkstra's Algorithm:
> Dijkstra's Algorithm, a greedy approach, finds the shortest path in weighted graphs. It's crucial for optimizing network routes, transportation, and resource allocation, ensuring efficient and timely traversal through interconnected systems.

5. Merge Interval:
> The Merge Interval greedy approach combines overlapping intervals efficiently, vital for scheduling, event management, and resource allocation. It optimizes interval consolidation, simplifying tasks and improving organizational efficiency.

6. Greedy Coin Change:
> The Greedy Coin Change approach selects the largest coin denomination to minimize the number of coins needed for a target amount. It's crucial for optimizing change-making processes, transactions, and vending machines

### Additional Information

These proposed algorithm implementations are highly valuable for efficiently solving a variety of competitive programming questions. By incorporating these well-established and effective algorithms, we aim to enhance the repository's utility and empower developers to tackle algorithmic challenges with optimized and well-structured solutions.

**Comment by Pratham86** [comment]
Hi there..
Is this issue still open??
I am interested in working..

**Comment by PRONOBITA** [comment]
@SanketPatil7467  I would like to contribute to this project.Please assign me this project.I will complete this project in just one day by using comments,appropriate variable names and in most efficient way.Greatly looking ahead to work with you.
