### ISSUE TITLE
[FEATURE REQUEST] Implementing a stack with 'bottom()' and 'min()' methods.

### ISSUE THREAD

**Issue by ajit1201** [TheAlgorithms/Java#4496]
### What would you like to Propose?

I would like to implement a stack using a linked list. This stack will have the following methods. 
please refer 

> src/datastructures/stack

1. Peek() --> Returns top element of stack
2. push() --> Insert an element in stack
3. pop() --> Remove an element from stack
4. min() --> Returns minimum element from stack
6. bottom() --> Return first element Stack stack
7. size() --> Return the size of stack

### Issue details

I would like to explain to you the implementation of bottom(), min() and size() methods.

bottom()
I will declare an attribute in class, which will be assigned when the size of the stack is zero and the first element is inserted. At any time that attribute will give a bottom value by the bottom() method.

min()
I will declare a min attribute in class, which will be updated whenever any element smaller than min is inserted. At any time that attribute will give a min value by the min() method.

size()
I will declare a count attribute in class, which will be incremented whenever any element is inserted. At any time that attribute will give a size value by the size() method.

### Additional Information

I would use concept of generic so the that the code can be used to implement stack of various data types.

Please assign this issue to me.
Thank you!!

**Comment by Rai-Sahil** [comment]
Hi can you assign this issue to me.

**Comment by ajit1201** [comment]
> Hi can you assign this issue to me.

No I am not the owner of this repository, so I can't.
If you want to contribute anything then please create issues for that feature.

**Comment by TanuSharma0802** [comment]
Hello Sir
Please assign this issue to me. I have good knowledge of java programming language and data structures and algorithms.

**Comment by BamaCharanChhandogi** [comment]
This organisation is based on an algorithmic problem.
Please do not add or create issues on other types of questions.
