### ISSUE TITLE
Travelling Salesman Problem using Dynamic Programming

### ISSUE THREAD

**Issue by juhiesayyed** [TheAlgorithms/Java#4497]
### What would you like to Propose?

- The source and destination vertex in the "Travelling Salesman Problem" are the same.
- Example Postmen take letters from the post office and deliver them to various addresses before returning them to the post office.
- For this algorithm, a complete directed graph is necessary.
- Purpose:- Create a path from the source vertex that passes through every vertex of the graph and returns to the source vertex in the shortest amount of time.

### Issue details

- There is no algorithm related to the travelling salesman problem in the java/DynamicProgramming folder.
- Considering how well-known this algorithm is, I reasoned that it must be present in this Alorithum repository.

**Comment by juhiesayyed** [comment]
#hactoberfest-2023

**Comment by Vineetttt** [comment]
hello @juhiesayyed , can i work on this ?

**Comment by PRONOBITA** [comment]
@juhiesayyed  Please assign me this project.I will complete this project in just one day by using comments and appropriate variable names and in most efficient way.Desperately Looking ahead to work with you

**Comment by Monachaudhary** [comment]
As an active participant in Hacktoberfest, I am eager to take on the assigned issue. I bring with me a commitment to optimizing solutions with the finest space and time complexities. Rest assured, your task is in capable hands. Please assign this issue to me.

**Comment by Shobhit0603** [comment]
sir can i solve this issue...please assign me this...i want to commit changes

**Comment by md-shamim-ahmad** [comment]
If anyone has plans to create a PR for ```Hacktoberfest 2023```, then there have  [awesome leetcode problem list](https://github.com/md-shamim-ahmad/LeetCode-Problem-Solution/issues/50)
You can create a pull request of your solution for specific problems in this list.
