### ISSUE TITLE
[FEATURE REQUEST] Golden Ration formula to find Nth Fibonacci number 

### ISSUE THREAD

**Issue by jstar2708** [TheAlgorithms/Java#4505]
### What would you like to Propose?

Golden ration formula

Problem statement : Find the nth Fibonacci number in O(1) time complexity.

Algorithm : 

We can simply use the formula given below to find Nth Fibonacci number.

1/√5 * (0.5 * (( √5 + 1) ^ n) - (0.5 * ( 1 - √5) ^ n))

### Issue details

So, the algorithm just uses formula for finding Nth Fibonacci number in O(1).

**Comment by TanuSharma0802** [comment]
Hello Sir
Please assign this issue to me. I have good knowledge of java programming language and data structures and algorithms.

**Comment by debnath003** [comment]
#4513 
Can somebody help me approving this PR? @debasishbsws

**Comment by Monachaudhary** [comment]
I bring with me a commitment to optimizing solutions with the finest space and time complexities. Rest assured, your task is in capable hands. Kindly assign this issue to me.

**Comment by debnath003** [comment]
@debasishbsws @BamaCharanChhandogi @yanglbme @vil02 Someone please check my PR #4513 and approve the PR for Hacktoberfest. It has been a long time but I didn't get the approval from any maintainer, please look into this matter! Thanks

**Comment by nikitha-m** [comment]
Hey, Im desperate to solve pls help and give it to me. Thanks

**Comment by vil02** [comment]
Closed by #4513.
