### ISSUE TITLE
[FEATURE REQUEST] <title>Coin Tower Problem Using Dynamic Programming

### ISSUE THREAD

**Issue by DineshK3012** [TheAlgorithms/Java#4506]
### What would you like to Propose?

I want to add Coin Tower Problem to the Dynamic Programming folder

### Issue details

Coin Tower Problem:

A and B are playing a new game today. They form a tower of N coins and make a move in alternate turns. B plays first. In one step, the player can remove either 1, X, or Y coins from the tower. The person to make the last move wins the game. Can you find out who wins the game?

**Comment by DineshK3012** [comment]
Added coin tower problem code : https://github.com/TheAlgorithms/Java/pull/4547

**Comment by SarthakChaudhary46** [comment]
@vil02 You mentioned having a few ideas for contribution. Please do let me know, brother—I'm all ears. Also, Do you no longer require a solution for this issue, or was my attempt not satisfactory?
