### ISSUE TITLE
[FEATURE REQUEST] <title>Loot Houses Problem (Dynamic Programming)

### ISSUE THREAD

**Issue by DineshK3012** [TheAlgorithms/Java#4508]
### What would you like to Propose?

I would like to add Loot Houses problem code to the Dynamic Programming folder

### Issue details

Loot Houses Problem Statement:

A thief wants to loot houses. He knows the amount of money in each house. He cannot loot two consecutive houses. Find the maximum amount of money he can loot?

**Comment by aipalak** [comment]
Please assign this to me

**Comment by SarthakChaudhary46** [comment]
Is this issue still open? Shall I work on it?
