### ISSUE TITLE
[FEATURE REQUEST] I would like to add House Robber-3 to the list of problems under dynamic programming

### ISSUE THREAD

**Issue by GouraV-Chatterjee** [TheAlgorithms/Java#4517]
### What would you like to Propose?

I would love to add House Robber-3 to the list of problems under DP. 

### Issue details

House Robber-3 is a type of DP problem which involves DP on trees.As no such problems are there under the DP section , adding such a problem would make the repo more generic and appealing.

Link to the question : https://leetcode.com/problems/house-robber-iii/description/

### Additional Information

It would be really great if you assign me this issue.

**Comment by kbadal19** [comment]
Hey, I've prior experience of working in java for 3 years. I've come across many such problems and House Robber is among the many that I've solved. Will you be kind enough to assign this problem to me. 
Thank you

**Comment by Kabirsharma2607** [comment]
@GouraV-Chatterjee I am contributing to Hacktoberfest kindly assign this issue to me

**Comment by Yatiraj-upadhyay** [comment]
please assign me this problem as i am proficient in Java, DSA and Algorithms.

**Comment by Samsand-5** [comment]
Hey I am a good problem solver I have solved this problem before and I can propose multiple solutions and I am a good Problem solver. You can definitely look my leetcode profile and please assign this task to me.
My profile below:-
https://leetcode.com/sam_sand/

**Comment by siriak** [comment]
We do not add Leetcode problems
