### ISSUE TITLE
[FEATURE REQUEST] <title> Painter's problem a Dynamic prrogramming Problem

### ISSUE THREAD

**Issue by zenith-78** [TheAlgorithms/Java#4530]
### What would you like to Propose?

I would like to add a classical Dynamic programming problem i.e. **Painter's Problem** which is based on the Important concept of **Partitions**  to the Dynamic programming repository.

### Problem Statement : 
Given there are N boards given as array of size n ,  and K painters. 
Each painter Takes exactly 1 unit of time to paint 1 unit of a board. Each element in array represents the size of the boards.  The task is to find the minimum amout of time to paint all  the boards with the constraint of painter can only paint contiguous sections of the boards. 
The submitted code would contain the methods required for calculating the time for painting the boards . The methods are also supported by java doc Strings which specifies the input and the return parameter for the  added methods.   

### Additional Information

please assign it under the HACKTOCTOBER label

**Comment by shashankrp** [comment]
I will like to work on this issue please assign this issue to me.
