### ISSUE TITLE
[FEATURE REQUEST] Binomial Heap Implementation

### ISSUE THREAD

**Issue by Prabhat-Kumar-42** [TheAlgorithms/Java#4552]
### What would you like to Propose?

# Proposal: Adding Binomial Heap Implementation for Heap

I was exploring the `datastructures/heaps` directory and noticed that there is no implementation of a Binomial Heap for Heaps.

So far, I have found the following Heap Implementations in the directory:
- Generic Heap
- Fibonacci Heap
- Leftist Heap

I propose adding the Binomial Heap Algorithm for Heaps to the `datastructures/heaps` directory.

## Details about Binomial Heap
You can find more information about Binomial Heap on the [Wikipedia page on Binomial Heap](https://en.wikipedia.org/wiki/Binomial_heap).

**Comment by Prabhat-Kumar-42** [comment]
Hello,
I have added a PR regarding this https://github.com/TheAlgorithms/Java/pull/4554
Please review it.
If there's anythting that needs to be added or changed, please do let me know. I will fix it asap.
Thank You !!

**Comment by sigma390** [comment]
@Prabhat-Kumar-42  is it already fixed ? tell fast

**Comment by Prabhat-Kumar-42** [comment]
@sigma390 I have already added a PR related to it. waiting for it to be reviewed.
