### ISSUE TITLE
[FEATURE REQUEST] Buy And Sell Stocks Based DP problems Missing

### ISSUE THREAD

**Issue by BharathSubu** [TheAlgorithms/Java#4569]
### What would you like to Propose?

I explored the DP Section ( thealgorithms/dynamicprogramming/ ) and wasn't  able to find Buy and Sell Stocks pattern based DP problems. Would be better if you we could add those problems to the repo
 
The problem involves buying and selling stocks with some constraints and achieving the maximum profit from it
Do Check out the problems

I would like to Contribute to it as my first hacktoberfest Contribution. So can you pls assign it to me , I have The code ready.

### Issue details

To know more about this you can search for leetcode Buy and sell stock problems

**Comment by parmar-abhinav** [comment]
Can I work on this issue

**Comment by Piyush12800** [comment]
I practice my DSA regularly on JAVA can i work on this issue .

**Comment by Anjali2312-Thombare** [comment]
Hey @BharathSubu I have solved many problems on stock buy and sell using DP . I will solve this issue in better way. Please assign me this issue .

**Comment by BharathSubu** [comment]
Hey I have made the PR can you check it out for any correction, @BamaCharanChhandogi

**Comment by 54AbhinavKumar** [comment]
Can you assign this issue to me?
