### ISSUE TITLE
[FEATURE REQUEST] Addition of Rank Of Matrix Algorithm

### ISSUE THREAD

**Issue by anupomkar** [TheAlgorithms/Java#4570]
### What would you like to Propose?

New Algorithm under
https://github.com/TheAlgorithms/Java/tree/master/src/main/java/com/thealgorithms/maths

File Name Proposed: MatrixRank.java

What?
An implementation of Rank of a Matrix.

### Issue details

More about rank of a matrix: https://en.wikipedia.org/wiki/Rank_(linear_algebra)

Algorithm complexity:
1. Time Complexity: O(M*N*rank)
2. Space Complexity: O(N)

### Additional Information

**Note: This issue is self assigned and PR is raised as a part of hacktoberfest**

**Comment by anupomkar** [comment]
PR Link: https://github.com/TheAlgorithms/Java/pull/4571

**Comment by mrunal12345-lab** [comment]
can i work on this

**Comment by anupomkar** [comment]
> can i work on this

As mentioned in Additional info, this is self assigned and PR is up.

**Comment by AbinMadathil** [comment]
Please do verify and merge my pull request..:)
