### ISSUE TITLE
[OTHER] Improve Readability of Algorithm Titles in DIRECTORY.md

### ISSUE THREAD

**Issue by SriMani-7** [TheAlgorithms/Java#4579]
### What would you like to share?

I noticed that in the `DIRECTORY.md` file of the GitHub repository, the algorithm titles are displayed at the end of multiple lines, making it difficult to read.
![Screenshot_2023-10-03-07-30-47-41](https://github.com/TheAlgorithms/Java/assets/84219628/8c8f1391-3062-4494-8a19-202edfe6650e)

To improve the readability of the file, I suggest collapsing the empty packages in a format similar to how IDEs display directory structures. This would enhance the user experience and make it easier for contributors to navigate the repository.

### Additional information

Please assign this to me.

**Comment by Sweetdevil144** [comment]
I don't find it hard to read. In fact, it seems to be perfectly designed for beginners to understand.
