### ISSUE TITLE
[FEATURE REQUEST] <Huffman coding greedy algorithm>

### ISSUE THREAD

**Issue by Sapna127** [TheAlgorithms/Java#4592]
### What would you like to Propose?

I would like to add implementation of huffman coding data compression algorithm under greedy algorithm category.

### Issue details

Addition of new algorithm.

**Comment by Sapna127** [comment]
Please assign me this issue under hacktoberfest!

**Comment by krupalitandel1** [comment]
please assign me this issue I would like to contribute to this project.

**Comment by Nishant-Khatri** [comment]
Please assign this problem to me I can add this algorithm

**Comment by Abdullahkhanspn** [comment]
Kindly please Merge 
[FEATURE] #4592 Huffman Coding Greedy Algorithm #4597
