### ISSUE TITLE
[FEATURE REQUEST] <Solved N Queens Problem>

### ISSUE THREAD

**Issue by KunjMaheshwari** [TheAlgorithms/Java#4595]
### What would you like to Propose?

Solve the Backtracking Problem - N Queens

### Issue details

Write the code of N Queens Problem.

**Comment by KunjMaheshwari** [comment]
Solve this issue.

**Comment by Rishab-Kumar-R** [comment]
Hey, can you assign this to me with some help, as I am new to open-source contributions.

**Comment by Anjali2312-Thombare** [comment]
hey @KunjMaheshwari  i have done this problem before. I will solve this issue in more better  way. please assign me this issue
