### ISSUE TITLE
[FEATURE REQUEST] <title>range-based queries algorithm

### ISSUE THREAD

**Issue by Sanidhya2101** [TheAlgorithms/Java#4599]
### What would you like to Propose?

Want to provide an important concept of range-based queries using Fenwick trees, segment trees, sparse table and heavy light decomposition.

### Issue details

Basic implementation of all the above basic methods for problems like min/max in a specific range, updating the element in the specific range, and adding the elements in a specific range.

**Comment by helixdynamics20** [comment]
Hi @Sanidhya2101, can you please assign this issue to me
