### ISSUE TITLE
[FEATURE REQUEST] Exchange Sort Algorithm

### ISSUE THREAD

**Issue by aniket3991** [TheAlgorithms/Java#4624]
### What would you like to Propose?

I would like to add implementation of Exchange sort algorithm under Sorting algorithm category.

Please find more details about this algorithm  https://en.wikipedia.org/wiki/Sorting_algorithm#Exchange_sort

### Issue details

Implementation of Exchange Sort is missing under sorting algorithm category.

### Additional Information

Please check #4623

**Comment by Kaushik2201** [comment]
I have made a PR #4670 can you please review it and merge it.

**Comment by 555vedant** [comment]
respected sir/madam can you please assign this issue to me i can make some fruitful Chages on it.

**Comment by 555vedant** [comment]
sorry for delay i was busy into my sem exams , i have  added ExchangeSort and its testcases

**Comment by 555vedant** [comment]
whats the next step

**Comment by 555vedant** [comment]
Sir ,I have added exchange sort but can't able to pr pls guide me..

**Comment by 555vedant** [comment]
you can close this issue i already merge PR for this issue

**Comment by aniket3991** [comment]
Thank you

**Comment by 555vedant** [comment]
Always welcome
