### ISSUE TITLE
[FEATURE REQUEST] <Longest Common Prefix>

### ISSUE THREAD

**Issue by Mochoye** [TheAlgorithms/Java#4630]
### What would you like to Propose?

Write a function to find the longest common prefix string amongst an array of strings.

If there is no common prefix, return an empty string "".

### Issue details

Longest Common Prefix

Write a function to find the longest common prefix string amongst an array of strings.

If there is no common prefix, return an empty string "".

Input: strs = ["flower","flow","flight"]
Output: "fl"

**Comment by Mochoye** [comment]
I request the maintainer(s) to label this with "hacktoberfest" label.

**Comment by raman-0O7** [comment]
Solved this issue 
fixes: #4637 
Please merge it to master branch

**Comment by anshul-132002** [comment]
@Mochoye  Assign me to solve this problem

**Comment by shiv12a10** [comment]
Hey, I will be very glad to solve this problem #4630 , Please grant me permission to solve this problem.
