### ISSUE TITLE
[FEATURE REQUEST] Array Right Rotation

### ISSUE THREAD

**Issue by rishav2803** [TheAlgorithms/Java#4638]
### What would you like to Propose?

I would to like add the implementation of Array Right Rotation under the "others" cateogry 

###  Problem statement :
**Given an array, rotate the array to the right by k steps, where k is non-negative**
Eg:
Input: [1,2,3,4,5,6,7] and k = 3
Output: [5,6,7,1,2,3,4]
Explanation:
rotate 1 steps to the right: [7,1,2,3,4,5,6]
rotate 2 steps to the right: [6,7,1,2,3,4,5]
rotate 3 steps to the right: [5,6,7,1,2,3,4]

**Comment by rishav2803** [comment]
I would really be happy if u could assign this issue to me

**Comment by mukul018** [comment]
I want to complete this.
Please assign it to me.

**Comment by Tanishaclippy** [comment]
Can you assign me this issue ??

**Comment by rakshapadiyar** [comment]
Please assign this to me

**Comment by vil02** [comment]
@rishav2803 I will assign @ppiippoo to this issue since I could not find your PR.

**Comment by rishav2803** [comment]
> @rishav2803 I will assign @ppiippoo to this issue since I could not find your PR.
Should I raise one?

**Comment by vil02** [comment]
@ppiippoo will you update your PR #4682? Or can @rishav2803 create a new one? Obviously we can only merge one.

**Comment by NagaSreeram** [comment]
I think I have the optimal solution for this issue. I'm new to this open source contribution, if this is not the optimal way of asking please do point me and tell me the right way to do so.

**Comment by BamaCharanChhandogi** [comment]
#4682

**Comment by SarthakChaudhary46** [comment]
The issue has been solved!!
