### ISSUE TITLE
[FEATURE REQUEST] <search in 2D matrix using BinarySearch>

### ISSUE THREAD

**Issue by saikrishna823** [TheAlgorithms/Java#4639]
### What would you like to Propose?

I explored the entire repository and wasn't able to find  search in 2D matrix using binary search. It would be better if you we could add that problem to the repo.

### Issue details

This problem involves in  using binarySearch to find the element in the 2D matrix.To know more about the problem you can checkout leetcode.

### Additional Information

I would like to Contribute to it as my first hacktoberfest Contribution. So can you pls assign it to me , I have The code ready

**Comment by Moha-dotcom** [comment]
I would like to contribute to this problem. Please assign it to me. Thanks

**Comment by Ananyaa03** [comment]
I would like to contribute to this problem. Please assign it to me. Thank you

**Comment by saikrishna823** [comment]
> I would like to contribute to this problem. Please assign it to me. Thanks

@Moha-dotcom you can start contributing to this issue.Did you send pull request?

**Comment by Sahil1694** [comment]
I would like to contribute to this problem. Please assign it to me.

**Comment by Saksham2874** [comment]
Can you please share a video of the issue

**Comment by neethanm** [comment]
can i work on this?

**Comment by AadiVerma** [comment]
I would like to Contribute to it as my first hacktoberfest Contribution. So can you pls assign it to me
