### ISSUE TITLE
Add methods in CoinChange Algorithm

### ISSUE THREAD

**Issue by bansalKeshav** [TheAlgorithms/Java#464]
As currently there is only one method in coin change algorithm which is the number of combinations of getting change for given amount.
I like to add one more method.
the minimum number of coins that make a given value.
@varunu28 can you check, If you are not working on that, I am happy to contribute.

**Comment by varunu28** [comment]
@bansalKeshav  Sure you can go ahead to add the method. Just make sure that the existing code style is preserved

**Comment by bansalKeshav** [comment]
okay, So I just create a pull request to the master branch or some another branch?
