### ISSUE TITLE
[FEATURE REQUEST] <Heap Sort Algorithm>

### ISSUE THREAD

**Issue by Roshnijeewani3457** [TheAlgorithms/Java#4640]
### What would you like to Propose?

I would like to add implementation of Heap sort algorithm under Sorting algorithm category.

### Issue details

Implementation of Heap Sort is missing under sorting algorithm category.

### Additional Information

I would like to Contribute to it as my first Hacktoberfest Contribution. 
So can you pls assign it to me.

**Comment by Yatiraj-upadhyay** [comment]
Hello sir,
I have the keen background in data structure and algorithm and currently i have solved more than 271 problems on different platforms.
I have knowledge in sorting, as heap sort is:
Heap sort is indeed a comparison-based sorting algorithm that utilizes the binary heap data structure. The key idea behind heap sort is to build a max-heap (in ascending order) or a min-heap (in descending order) from the given array and then repeatedly extract the maximum (or minimum) element from the heap, placing it in the sorted portion of the array. This process is repeated until the entire array is sorted.

Here's a step-by-step overview of the heap sort algorithm:

1. Build a heap: The first step is to build a binary heap from the input array. This involves arranging the elements in the array such that they satisfy the heap property (either max-heap or min-heap).

2. Heapify: Starting from the last non-leaf node of the heap and moving upwards, heapify each subtree. Heapify is a procedure that ensures that the heap property is maintained. In a max-heap, it ensures that the parent node is greater than or equal to its children, and in a min-heap, it ensures the parent node is less than or equal to its children.

3. Extract elements: Repeatedly remove the root (which is the maximum element in a max-heap or the minimum element in a min-heap) and place it at the end of the array. After each extraction, the size of the heap decreases by one.

4. Heapify again: After extracting an element, the remaining elements may no longer satisfy the heap property. To restore the heap property, perform heapify on the root node (which was the last element of the heap).

5. Repeat: Repeat steps 3 and 4 until all elements have been extracted and placed in the sorted order. The array will be sorted in ascending order if a max-heap is used and in descending order if a min-heap is used.

Heap sort has a time complexity of O(n log n) for both its average and worst-case scenarios, making it an efficient sorting algorithm. It is an in-place and stable sorting algorithm, meaning it doesn't require additional memory allocation for sorting, and it preserves the relative order of equal elements in the input array.

For a detailed reference and implementation of the heap sort algorithm, you can refer to authoritative textbooks on algorithms and data structures or online resources on sorting algorithms.


SO PLEASE, ASSIGN ME THIS ISSUE AS THIS WILL BE MY FIRST PR FOR HACKTOBER FEST IT WILL BE MY PLEASURE TO HELP YOU FOR THIS PROBLEM AND ALSO SHOWCASE MY SKILLS.
THANK YOU

**Comment by rohit162** [comment]
Can you assign me this issue please.

**Comment by hydraveer** [comment]
Please assign me this issue

**Comment by srish-03** [comment]
Hi I am interested Can You please assign this issue to me ?

**Comment by WilliamNian** [comment]
Hi I want to work on this issue, can you plz assign the issue to me?

**Comment by Chandan-Kumar-Mahato** [comment]
I would love to to this task will you assign this task to me please.

**Comment by ZoreAditya** [comment]
> ### What would you like to Propose?
> I would like to add implementation of Heap sort algorithm under Sorting algorithm category.
> 
> ### Issue details
> Implementation of Heap Sort is missing under sorting algorithm category.
> 
> ### Additional Information
> I would like to Contribute to it as my first Hacktoberfest Contribution. So can you pls assign it to me.
