### ISSUE TITLE
[FEATURE REQUEST] <Minimum Spanning Tree>

### ISSUE THREAD

**Issue by Roshnijeewani3457** [TheAlgorithms/Java#4641]
### What would you like to Propose?

I would like to add implementation of Minimum Spanning Tree under Sorting algorithm category.

### Issue details

Implementation of MST is missing under sorting algorithm category.

### Additional Information

I would like to Contribute to this repository.
So can you pls assign it to me.

**Comment by YashuRanparia** [comment]
Can I contribute to this ?
