### ISSUE TITLE
[FEATURE REQUEST] Find the N-th Tribonacci Number missing

### ISSUE THREAD

**Issue by okaydivyansh** [TheAlgorithms/Java#4646]
### What would you like to Propose?

I explored the Dynamic programming ( thealgorithms/dynamicprogramming/ ) and wasn't able to find the standard problem of finding the n-th tribonacci number in the series. Would be better if you we could add those the repo.

### Issue details

The problem involves dynamic programming to find nth tribonacci number and is a very standard problem.
I would like to Contribute to it as my first hacktoberfest Contribution. So can you pls assign it to me , I have The code ready.
problem link: https://leetcode.com/problems/n-th-tribonacci-number/description/

**Comment by okaydivyansh** [comment]
please label this with hackertoberfest

**Comment by hydraveer** [comment]
please assign this for me
