### ISSUE TITLE
Duplicate directories for Data Structures

### ISSUE THREAD

**Issue by varunu28** [TheAlgorithms/Java#466]
@christianbender There are duplicate directories for Data Structures in the repo. I see your commit on both the repos. Please verify and delete the duplicate directory. Also make sure that no existing algorithms are missed in the process

@AnupKumarPanwar @dynamitechetan  Please have a look

**Comment by christianbender** [comment]
@varunu28 Yeah, this directory already exists as I take the repository. I thought this have a ground. I fixed the problem. Now we have only one directory named ```DataStructures```.

**Comment by varunu28** [comment]
@christianbender Thanks
