### ISSUE TITLE
Feat :  Boyer–Moore majority vote algorithm

### ISSUE THREAD

**Issue by Manan-09** [TheAlgorithms/Java#4675]
### What would you like to Propose?

Boyer–Moore majority vote algorithm : [Wiki](https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore_majority_vote_algorithm)

Boyer–Moore majority vote algorithm is used to find majority of element in given collection of items. Majority elements mean , element that occurs more than or equal to N / 2 times in collection with size of N.

Example : 
Input : [3,4,1,4,2,4]
Output : 4

### Issue details

Implementation of Boyer–Moore majority vote algorithm is missing in current codebase, please point out if it's present.

**Comment by Waqiur** [comment]
I would like to contribute to this problem. Please assign it to me. Thanks

**Comment by its-100rabh** [comment]
I would like to contribute to this problem. Thanks

**Comment by HimanshuMahto** [comment]
Hey, please assign me this issue to work on.

**Comment by vil02** [comment]
This already exists: [`BoyerMoore`](https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/others/BoyerMoore.java).
