### ISSUE TITLE
[BUG] <Suggestion: Improve LinkedList Loop Detection Algorithm - Create, Detect, Remove>

### ISSUE THREAD

**Issue by AdityaRokade17** [TheAlgorithms/Java#4679]
### Description

I noticed that the current loop detection algorithm in the LinkedList class is not efficient for large lists. I would like to suggest an improvement to make it more optimized. Easiest Code for the ones who is new for a coding and very easy to understand.
also added one more function if loop is detect it will remove loop and return. 

### Steps to reproduce

1.Create a linked list with a loop.
2.Run the loop detection algorithm.
3.Gives Error

### Excepted behavior

I expected the loop detection algorithm to run efficiently and quickly identify the loop in the linked list and also need to have option to remove loop.

### Screenshots

![Screenshot (9)](https://github.com/TheAlgorithms/Java/assets/89978003/c0954636-0b5a-430b-8718-28197c10c5f4)

**Comment by AdityaRokade17** [comment]
I believe I have a solution for this issue. I'd like to work on it and contribute the fix. 
could you please assign this issue to me? I'd be happy to get started on it. 
![Screenshot (10)](https://github.com/TheAlgorithms/Java/assets/89978003/fc95629d-4fe7-4758-b80a-d97fd4e8c0b3)

**Comment by aspiringgarv** [comment]
Hey could you assign this to me will be happy to contribute

**Comment by VishuKalier2003** [comment]
Yes I would like to work on this one as well. I am a good Algo Expert with a good leetcode and hackerrank ranking.

**Comment by rohit162** [comment]
Can you assign me this issue.

**Comment by BLSowmya** [comment]
I would be glad if you assign me this issue ...i would like to work on this since i am good with algorithms and DS

**Comment by Sooraj-Mlahi** [comment]
can you assign this to me? if it is not solved I would be more happy to work on this

**Comment by geek101-cy** [comment]
I would like to work on this issue.

**Comment by siriak** [comment]
@geek101-cy please let me know what the problem is and how it can be solved
