### ISSUE TITLE
[BUG] <Issue in Herons Formula>

### ISSUE THREAD

**Issue by satyabarghav** [TheAlgorithms/Java#4685]
### Description
In the implementation of Herons Formula we have the signature of the function as Herons(int a, int b, int c) so when we call the function we are confined to only integer inputs and we will get the error when using sides of double or float data type

### Excepted behavior

So we need to change the signature of the function to even work with data types of even double or float.

I have attached the error we get while calling the function with parameters of double data type.

### Screenshots

![image](https://github.com/TheAlgorithms/Java/assets/36763910/aa5bff68-af4c-4036-8237-3773455445e4)

**Comment by Sourabhsahu33** [comment]
I want to interested to contribute can you assigned me.

**Comment by AshBakchod** [comment]
Hey i just got a solution for this issue in which a function need to work for various data types . Please Assign me this issue so that i can quickly solve this by Function Overloading.

**Comment by AshBakchod** [comment]
Hey @satyabarghav if this issue is still unsolved then please feel free to assign me this issue i have already solved it in my fork using function overloading please check

**Comment by BLSowmya** [comment]
Hey @satyabarghav if this issue is still unsolved then please feel free to assign me this issue

**Comment by HimanshuMahto** [comment]
hey @satyabarghav can you assign me this issue

**Comment by vil02** [comment]
Closed by #4686.
