### ISSUE TITLE
[FEATURE REQUEST] <JUMP Game Greedy problem>

### ISSUE THREAD

**Issue by Mochoye** [TheAlgorithms/Java#4692]
### What would you like to Propose?

You are given an integer array nums. You are initially positioned at the array's first index, and each element in the array represents your maximum jump length at that position.

Return true if you can reach the last index, or false otherwise.

### Issue details

You are given an integer array nums. You are initially positioned at the array's first index, and each element in the array represents your maximum jump length at that position.

Return true if you can reach the last index, or false otherwise.

Input: nums = [2,3,1,1,4]
Output: true
Explanation: Jump 1 step from index 0 to 1, then 3 steps to the last index.

### Additional Information

I want to contribute on this issue for Hacktoberfest

**Comment by Rohxn16** [comment]
HI, I can work on this problem can I be assigned with this issue?

**Comment by vil02** [comment]
It seems to be a leetcode like problem. Please note:
https://github.com/TheAlgorithms/Java/blob/9dde8a780832a29c508deb3382410e36f127fdf1/CONTRIBUTING.md?plain=1#L3
