### ISSUE TITLE
[FEATURE REQUEST] <SalaryPerTurn>

### ISSUE THREAD

**Issue by GreenyHat** [TheAlgorithms/Java#4697]
### What would you like to Propose?

The code is a simple setup designed to manage the salaries of employees split into two shifts: morning and evening. Let's dive in:

**Variables and Arrays:**

employeeAM and employeePM: These are integer arrays that keep tabs on the salaries of our morning and evening shift workers, respectively.
sc: That's our trusty Scanner object, always ready to scoop up user inputs from the console.
salary: Just a temporary spot to hold onto the salary figure while the user keys it in.

**Method loadData():**

This one prompts the user to key in the salaries for 4 of our morning shift crew and 4 from the evening squad.
For our early birds in the morning shift, salaries should be 1500 or less.
Evening folks, on the other hand, are in the more upscale bracket with salaries starting just above 1500.
If the salary doesn't quite match these criteria, it nudges the user to have another go.

**Method showData():**

Here, we parade all the registered salaries for both shifts, each one neatly numbered so you can't miss it.

**Method calculateSpent():**

Pulls out the calculator and displays the grand total of salaries for the morning and evening shifts.

**Method main:**

It whips up a SalaryPerTurn object, gets the salary figures in order, parades them for a quick look, and finally, rolls out the combined salary total for both shifts.

### Issue details

```
 public void loadData() {
        employeeAM = new int[4];
        employeePM = new int[4];
        sc = new Scanner(System.in);

        int indexAM = 0, indexPM = 0;

        // Manage of employeeAM
        while (indexAM < 4) {
            System.out.print("Enter the salary for morning shift " + (indexAM + 1) + ": ");
            salary = sc.nextDouble();
            if (salary <= 1500 && indexAM < 4) {
                employeeAM[indexAM] = (int) salary;
                indexAM++;
            } else {
                System.out.println(
                        "Is not possible, the salaries of the morning shift are below 1500. Enter another amount");
            }

        }

        // Manage of employeePM
        while (indexPM < 4) {
            System.out.print("Enter the salary for afternoon shift " + (indexPM + 1) + ": ");
            salary = sc.nextDouble();
            if (salary > 1500 && indexPM < 4) {
                employeePM[indexPM] = (int) salary;
                indexPM++;
            } else {
                System.out.println(
                        "Is not possible, the salaries of the afternoon shift are below 1500. Enter another amount");

            }
        }
    }
```

**Comment by ved-asole** [comment]
Hi @GreenyHat, I would like to assist you to resolve the above issue/add enhancement. Could you please confirm if we can work on it together?

**Comment by GreenyHat** [comment]
for syre @ved-asole, I am a noob with Java and programming in general, will be a pleasure!

**Comment by GreenyHat** [comment]
This would be the rest of the code: 

```
 public void showData() {

        System.out.println("Morning turn:");
        for (int i = 0; i < employeeAM.length; i++) {
            System.out.println("Salary " + (i + 1) + ": " + employeeAM[i]);
        }

        System.out.println("Afternoon turn:");
        for (int i = 0; i < employeePM.length; i++) {
            System.out.println("Salary " + (i + 1) + ": " + employeePM[i]);
        }
    }

    public void calculateSpent() {
        float aM = 0, pM = 0;

        for (int i = 0; i < employeeAM.length; i++) {
            aM += employeeAM[i];
        }
        for (int i = 0; i < employeePM.length; i++) {
            pM += employeePM[i];
        }
        System.out.print("The spent are: " + aM + " in the monrning turn, and " + pM + " in the afternoon turn");
    }

    public static void main(String[] args) {
        SalaryPerTurn sa = new SalaryPerTurn();
        sa.loadData();
        sa.showData();
        sa.calculateSpent();
    }
}

```

**Comment by sigma390** [comment]
@GreenyHat  Is this issue solved or not if not plz explicityly mentions whats issue

**Comment by GreenyHat** [comment]
@sigma390Yes, it is solved

**Comment by GreenyHat** [comment]
How can I request a pull request to be introduced with the rest of the basic Java algorithm? It is for my participation in the Hacktoberfest, I am a bit lost, I'm sorry, maybe this was not the communication route, although I understood that it was.

**Comment by pranavgowtham** [comment]
HI @GreenyHat Just had a suggestion over the code pasted above. Why do we need a redundant check  of indexAM < 4 and indexPM < 4 inside the while loop,which is already enforced in the looping condition.

**Comment by GreenyHat** [comment]
Hii @pranavgowtham My apologies, you are indeed correct, it is an unnecessary redundancy, if you see any other errors, do not hesitate to point them out, thank you.

```
package Project67;

import java.util.Scanner;

public class SalaryPerTurn {
    private int[] employeeAM, employeePM;
    private double salary;
    private Scanner sc;


    // PROPUESTA MEJORADA:

    public void loadData() {
        employeeAM = new int[4];
        employeePM = new int[4];
        sc = new Scanner(System.in);

        int indexAM = 0, indexPM = 0;

        // Manage of employeeAM
        while (indexAM < 4) {
            System.out.print("Enter the salary for morning shift " + (indexAM + 1) + ": ");
            salary = sc.nextDouble();
            if (salary <= 1500) {
                employeeAM[indexAM] = (int) salary;
                indexAM++;
            } else {
                System.out.println(
                        "Is not possible, the salaries of the morning shift are below 1500. Enter another amount");
            }

        }

        // Manage of employeePM
        while (indexPM < 4) {
            System.out.print("Enter the salary for afternoon shift " + (indexPM + 1) + ": ");
            salary = sc.nextDouble();
            if (salary > 1500) {
                employeePM[indexPM] = (int) salary;
                indexPM++;
            } else {
                System.out.println(
                        "Is not possible, the salaries of the afternoon shift are below 1500. Enter another amount");

            }
        }
    }

    public void showData() {

        System.out.println("Morning turn:");
        for (int i = 0; i < employeeAM.length; i++) {
            System.out.println("Salary " + (i + 1) + ": " + employeeAM[i]);
        }

        System.out.println("Afternoon turn:");
        for (int i = 0; i < employeePM.length; i++) {
            System.out.println("Salary " + (i + 1) + ": " + employeePM[i]);
        }
    }

    public void calculateSpent() {
        float aM = 0, pM = 0;

        for (int i = 0; i < employeeAM.length; i++) {
            aM += employeeAM[i];
        }
        for (int i = 0; i < employeePM.length; i++) {
            pM += employeePM[i];
        }
        System.out.print("The spent are: " + aM + " in the monrning turn, and " + pM + " in the afternoon turn");
    }

    public static void main(String[] args) {
        SalaryPerTurn sa = new SalaryPerTurn();
        sa.loadData();
        sa.showData();
        sa.calculateSpent();
    }
}

```

**Comment by pranavgowtham** [comment]
@GreenyHat  can i assist you in this and add my changes whatever i find as a PR?

**Comment by GreenyHat** [comment]
@pranavgowtham for sure!

**Comment by pranavgowtham** [comment]
> @pranavgowtham for sure!

Thanks! Can you share the repo/project link in that case.

**Comment by GreenyHat** [comment]
https://github.com/GreenyHat/MyJavaDevelopProgress/blob/dev/src/myjavadevelopprogress/Project67/ArraySum.java

@pranavgowtham

**Comment by GreenyHat** [comment]
In fact, that is a version without the changes that you suggested to me. Anything to improve my code is appreciated, I'm just starting out so any suggestions are a blessing 🙏

**Comment by pranavgowtham** [comment]
@GreenyHat  Sorry for the delay. Added a boundary check, code optimizations and raised a PR. Please see if it might be useful.
