### ISSUE TITLE
GCD.java placed in Others package doesn't work right

### ISSUE THREAD

**Issue by MarisaAfuera** [TheAlgorithms/Java#471]
Greatest divisor common algorithm coded in GDC.java doesn't work when the numbers into the array are arranged in ascending order. I mean, the function gcd(int num1, int num2) works right if the call is gdc(40,24) but doesn't work if the call is gdc(24,40).

**Comment by christianbender** [comment]
@MarisaAfuera Thanks for bug report.

**Comment by christianbender** [comment]
@MarisaAfuera 
It works for none of this cases: (24,40) or (40,24)
I get various outputs but none of it is correct. The correct answer is 8.

**Comment by christianbender** [comment]
@MarisaAfuera 
>  he function gcd(int num1, int num2) works right 

No. In this method is the bug. See my comments above.

**Comment by christianbender** [comment]
@MarisaAfuera I fixed it.

**Comment by MarisaAfuera** [comment]
Hi Christian,

I'm novice in github. I'm looking for contribute making some code. It
doen't matter new code or fixing old one. If I can help you in any way, I'm
willing.

*Sincerely*

Marisa Afuera

2018-07-25 17:08 GMT+02:00 Christian Bender <notifications@github.com>:

**Comment by MarisaAfuera** [comment]
Ok. I'll work in order to improve the code.

Marisa
