### ISSUE TITLE
[FEATURE REQUEST] <title>

### ISSUE THREAD

**Issue by 54AbhinavKumar** [TheAlgorithms/Java#4711]
### What would you like to Propose?

Adding a TRIES section

### Issue details

Please assign the task to me

**Comment by 54AbhinavKumar** [comment]
Please assign the issue to me

**Comment by sigma390** [comment]
whats TRIES SECTION??

**Comment by 54AbhinavKumar** [comment]
Algorithm related to tries data structures

**Comment by srish-03** [comment]
Please assign the issue to me

**Comment by Govind516** [comment]
I am a good candidate. Please assign this issue to me.

**Comment by siriak** [comment]
There's https://github.com/TheAlgorithms/Java/blob/7ece806cf5cae7c3531f2eb54c56cf33fed2e579/src/main/java/com/thealgorithms/datastructures/trees/TrieImp.java already, do we need something else?
