### ISSUE TITLE
[FEATURE REQUEST] <title>adding unique path 2 in dynamic programming section using memoization ,tabulation and space optimization

### ISSUE THREAD

**Issue by sandeep0009** [TheAlgorithms/Java#4719]
### What would you like to Propose?

Adding unique path 2 in dynamic programming section.

### Issue details

in unique path 2 robot have to reach final destination in m*n grid and in that path there is obstacle -1 or 1 such that he cant pass that path in the  grid.

**Comment by Vijay-948** [comment]
can you assign me I can do this

**Comment by Samsand-5** [comment]
Hey can you please assign this task to me I have a good Knowledge on Dynamic Programming and I have solved more than 100 problems based on Dynamic Programming on leetcode and this problem can be done using DP on grids.

**Comment by siriak** [comment]
We do not add Leetcode problems
