### ISSUE TITLE
Convert the repository into a Java project 

### ISSUE THREAD

**Issue by varunu28** [TheAlgorithms/Java#474]
@christianbender @AnupKumarPanwar @dynamitechetan 

This is something which something which we have discussed in the past and have been raised by multiple users of the repo. The repo can be converted to a complete Java project with correct package structure, JUnit tests and Java language standard checkers. I want that anyone who is adding a new algorithm should add respective tests and follow a set coding standard so that the repo can become more usable for users who can then clone it into a local IDE and work on it.

Similar to [Scala Repo](https://github.com/TheAlgorithms/Scala)

I propose that we create a development branch on which we can start making the changes and replace it with the master once it fulfills the above-mentioned requirement. I would like to take the initiative and start this task. 

Please share your feedback.

**Comment by burnz248** [comment]
Hey Anup. I would like to help with this as well. Let me know what you need help with

**Comment by MarisaAfuera** [comment]
Hi Anup. Great idea. I also can help if you need.

**Comment by rahul-vishwadhaar** [comment]
Hello Anup,

This seems to be great thing. Please let me know if I can contribute.

**Comment by ahmedsameha1** [comment]
I'm in.

**Comment by habibu** [comment]
Also, I am in and happy to contributes

**Comment by lq920320** [comment]
So great, happy to join and contributes.

**Comment by xiaomabuchicao** [comment]
我还以为不能说中文

**Comment by MayV** [comment]
I'd like to help and contribute.

**Comment by esarella** [comment]
Presently working on solving most problems. I'm more than willing to help and contribute.

**Comment by asdiamond** [comment]
I can definitely help and contribute to this.

**Comment by giannisal** [comment]
I'd love to contribute to make this repo a java project.

From what I've seen so far, the development branch is identical to the master in terms of structure and content. I'm used to working with maven in Java, however I saw that the scala repo is based on Travis CI. Would you like me to work on either of them, create the project and test for some of the existing classes?

**Comment by varunu28** [comment]
@giannisal @channel I initially created the development branch. I would move the code to that branch in a project structure by the weekend and would update the README for the test case format. After that we can start accepting contributions to the development branch for the tests
We are using ScalaTest spec in the Java repo

**Comment by varunu28** [comment]
I have updated the development branch and added a instructions to the README. We can start with the migration. 

@christianbender Please make sure every PR is adhering to the points mentioned in README on [Development branch](https://github.com/TheAlgorithms/Java/tree/Development)

**Comment by lq920320** [comment]
which build tool should be used, maven or gradle? @varunu28  I didn't see on the Development branch.

**Comment by asdiamond** [comment]
What about bazel?

**Comment by SatyaPrakashDwibedi** [comment]
Hi, all I have started working on sorting algorithms
@varunu28  Are we following java 1.8 here?

**Comment by varunu28** [comment]
@SatyaPrakashDwibedi  Yes. We are following Java 1.8.

**Comment by Leoat12** [comment]
I'm happy to contribute as well. :) 
Just to understand better, it is to transfer the already done algorithms from master to the new branch, in the appropriate package and then make test cases for them, right?

**Comment by varunu28** [comment]
@Leoat12 Exactly(While following the correct coding standards and practices) 
So just have a look at the README in development branch and if you see some code which is not according to the Java standard coding guidelines then feel free to refractor it.

**Comment by MarisaAfuera** [comment]
I would like some help to collaborate with you. When I read Steps to raise a PR, what do you mean with "by using the command git checkout Development". Where do I write this commad? In my local repo or in the github web?

**Comment by varunu28** [comment]
@MarisaAfuera You would have to fork the repo first and then when you ```cd``` into the repo on your local machine, you need to switch to development branch using ```git checkout Development```

**Comment by MarisaAfuera** [comment]
@Varun I'm going to try it from eclipse. Thank you.

**Comment by varunu28** [comment]
@MarisaAfuera I suppose eclipse also has a very good Git support(Not sure about exact setup)

If you face any issues on eclipse, I would advice you to run this command through a terminal

**Comment by MarisaAfuera** [comment]
@varun. Thanks. I have installed a plugin for git. I could change the
repository in my local environment to development. Now I look for something
to do.

**Comment by burnz248** [comment]
@varunu28 is there any progress on this issue? if not much, I will work on this tonight, and create a PR

**Comment by varunu28** [comment]
@burnz248 The Development branch is created and instructions for opening a PR have been updated in the README of the branch

**Comment by Leoat12** [comment]
After forking, cloning and checking out to the Development I noticed that the structure of the project is not conventional, at least as I far as I've seen. The structure we usually see is this:
+ src\main\java\com\example
+ src\test\java\com\example

With this we have the same packages for both source and tests: com.example 
I don't know about Eclipse because I will not using it right now, but IntelijIDEA complains a lot with the current structure.  I think we can agree that a package structure which appears the "src" folder like here "src.main.com.java.conversions" is not conventional. 
What do you think? Would it be better to make this change, it would be too much trouble for the rest of the collaborators?

**Comment by varunu28** [comment]
@asdiamond As of now we are not considering any build tool. We are focussing on building a basic java project with complete test coverage.

**Comment by MarisaAfuera** [comment]
@Varun @Leonardo @Aleksandr Althought there are a lot of ways to make
package structure, I think that we must to have an standard way for the
project.

I've seen that for PR "add Test for InsertionSort #494", the autor has
created the test package. Maybe because there aren't enough details in
readme file.

Maybe you can add in readme.md of the DEVELOPMENT branch:

- Follow the correct coding guidelines with proper description for the
methods. Refer DecimalToAnyBase.java
<https://github.com/TheAlgorithms/Java/blob/Development/src/main/com/java/conversions/DecimalToAnyBase.java>
for algorithm and DecimalToAnyBaseTest.java
<https://github.com/TheAlgorithms/Java/blob/Development/src/test/com/java/conversions/DecimalToAnyBaseTest.java>
for the test coding standards.The test class will be place in the same
package than tested class.

**Comment by varunu28** [comment]
@MarisaAfuera @Leoat12 I have corrected the project structure now.

**Comment by khalil2535** [comment]
I Suggest to make a new branch that for this issue and merge it when it's ready or change it to be master branch.
This idea is best thing can be happen to this repo , excited to see it happening soon.

**Comment by varunu28** [comment]
@khalil2535 Already created a Development branch and people have started contributing to it. Please refer Development branch for more details

**Comment by bhati-lokendra** [comment]
@varunu28 hello i am completely new to github . it will great if you would guide me i will love to contribute , currently i am learning java so i can help with all my efforts 
thanks

**Comment by varunu28** [comment]
Sure @bhati-lokendra . You can start by adding tests to Development branch. Please refer the README before making the changes. Do let me know if you face any issues

**Comment by NeverMendel** [comment]
What about adding Travis CI in the developement branch?

**Comment by varunu28** [comment]
@NeverMendel That would be really helpful for testing as the tests are going to increase with time on the development branch

**Comment by AnupKumarPanwar** [comment]
Do we really need this? As we are planning to go ahead with a [website](https://github.com/TheAlgorithms/website) also for the organization where students can learn algorithms and their implementation in various programming languages. So for the automated fetching or the code from repositories using Github APIs, I think keeping them in single file codes will be beneficial down the line.

**Comment by varunu28** [comment]
@AnupKumarPanwar It would be helpful if a beginner wants to pull the complete project on their local and want to change the code, tests would be beneficial. Also, someone trying to contribute to the repository, tests would be helpful in verifying their changes. The project structure and the test automation teaches the best Java practices along with the algorithms and keeps the repository in a systematic way. 

As far as the website is concerned, we can make some changes to the API script to fetch codes from this project structure also. Great initiative btw. I was not aware of it and would be happy to be a part of this.

**Comment by SatyaPrakashDwibedi** [comment]
Hi, Sorry I couldn't keep up but what I came to know that as we are now migrating to a complete java project structure so we don't just need algorithms but also with test cases right??
If Yes:
        I see that for conversion, search and sorting is done I can go ahead with Compression.
If No:
       Where did I miss??
Thanks

**Comment by ales-blaze** [comment]
Hi there, My name is Ales and i am new here and i want to be a contributor to this repo . So, how can i be that one , what are the procedures to follow?

**Comment by varunu28** [comment]
@SatyaPrakashDwibedi You can refer the master branch and add tests for algorithms for which the tests are not present in Development

@ales-blaze Please refer README in Development branch

**Comment by ales-blaze** [comment]
I had read that and i want to know answer of questions like, will you guys going to assign me which algo i have to implement? or may i choose it by my own?

**Comment by varunu28** [comment]
@ales-blaze You can pick up an algorithm present in the master branch for which test cases are yet not implemented and then refactor the code into the module as described on the Development branch along with tests.

**Comment by ales-blaze** [comment]
I am having issue with the development branch , i posted some issues there ,but no one reacted on it !

**Comment by varunu28** [comment]
@ales-blaze You would need to provide some more details about the issue you are facing while posting a PR

I would suggest you have a look at [GitHub PR](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

**Comment by a2937** [comment]
I want to contribute as well. Does it matter which algorithm and corresponding tests I choose?

**Comment by varunu28** [comment]
@a2937 You can go ahead by raising a PR. Just check that the algorithm you are choosing is not already present in the development branch.

**Comment by LukeBMorrow** [comment]
If you still need a hand, I'd love to help

**Comment by justStarNew** [comment]
hi,guys.can this project be imported into IDEA

**Comment by varunu28** [comment]
@LukeBMorrow You can get started by raising a PR. Please check README on Development branch

**Comment by varunu28** [comment]
@justStarNew Yes. It can be

**Comment by justStarNew** [comment]
@varunu28 I hate to say it, but when i import the project into IDEA,I got this problem.  
<img width="1280" alt="5523542951553" src="https://user-images.githubusercontent.com/18233711/54168496-bc404080-44a9-11e9-8a73-d5a995386779.png">
<br>I think it might be IDEA configuration problem,so i mark the src directory as source root. 
<img width="1280" alt="5523544203731" src="https://user-images.githubusercontent.com/18233711/54168538-07f2ea00-44aa-11e9-9fb2-ac0c56e4f4f3.png">
<br> and i got this above..
<img width="1280" alt="5523545223050" src="https://user-images.githubusercontent.com/18233711/54168572-2fe24d80-44aa-11e9-849b-ecad353efe34.png">
can you guys help me,thanks in advance.

**Comment by burnz248** [comment]
Unmark the src directory as source root, and mark the "java" directory as
source root.

(I.e. src/main/java)

**Comment by Danpatpang** [comment]
Hi, Great idea. I also can help if you need.

**Comment by varunu28** [comment]
@Danpatpang Thanks. Go ahead by raising a PR

**Comment by Danpatpang** [comment]
Hi, all I have started working on sorting algorithms
@varunu28 Can I implement DepthFirstSearch, BreadthFirstSearch and RadixSort?

**Comment by smitamoonka** [comment]
@varunu28 I can contribute as well, if needed!Thanks

**Comment by SmitaMoon** [comment]
@varunu28 Is this still on going task?

**Comment by varunu28** [comment]
@smitamoonka @SmitaMoon Yes. This is active. Refer to the README on the development branch and raise a PR against Development.

**Comment by AnupKumarPanwar** [comment]
Actually converting the repo into a Java project will not solve the purpose of this organization. We want to create this organization as an open source learning resource for data structures and algorithms which is easy to understand for beginners also and every program is capable of independent execution. This will also make it convenient to automatically fetch the code and execute it in case we go for building a website for learning the DSA.

**Comment by SirWindfield** [comment]
I've added a PR #815 that cleans up the code base to make working on it easier. After it gets merged I'll start with adding tests and all missing algorithms to the repo.

**Comment by jayyusi** [comment]
is this still going on ? If yes, I want in on it !! Which algorithms need JUnit tests ?

**Comment by SirWindfield** [comment]
Just take a look at the development branch. Everything in there is OK. Everything else needs a port plus Junit tests

**Comment by jayyusi** [comment]
> Just take a look at the development branch. Everything in there is OK. Everything else needs a port plus Junit tests

Here's a question before I dive into this.
[CombSort.java](https://github.com/TheAlgorithms/Java/blob/master/Sorts/CombSort.java) exists in the master branch, but doesn't exist in the [development ](https://github.com/TheAlgorithms/Java/tree/Development/src/main/java/com/sorts)branch. So based on what you said, it needs a test, can you confirm ? and what do you mean by port ?
Thanks

**Comment by SirWindfield** [comment]
If it doesn't exist in development you have to get the code from master and add it to development. After that, you need to write unit tests for it. The tests should cover up most of the behavior of each algorithm. Like exceptions that might be thrown, wrong input formats etc.

By port I meant taking the algorithm from master and adding it to development. They need some tweaking because you don't need the main method anymore. The stuff in main should be covered by the tests.
You also need to add package statements because the project structure changed to maven.

**Comment by jayyusi** [comment]
> If it doesn't exist in development you have to get the code from master and add it to development. After that, you need to write unit tests for it. The tests should cover up most of the behavior of each algorithm. Like exceptions that might be thrown, wrong input formats etc.
> 
> By port I meant taking the algorithm from master and adding it to development. They need some tweaking because you don't need the main method anymore. The stuff in main should be covered by the tests.
> You also need to add package statements because the project structure changed to maven.

Great, thank you, I will get to it soon, I'm gonna do CombSort.java first.

**Comment by jayyusi** [comment]
I've added PR #825, which has 2 new files:

1) CombSort.java ( copied from master as is, with minor changes to import statements and class interface implementation to accommodate project structure changes )
2) CombSortTest.java ( which has 4 tests within it, Integer, String, Double, Character )

**Comment by SirWindfield** [comment]
Ye like good.

**Comment by renjithgr** [comment]
Hi all,
I raised a pull request to change the build tool from Maven to Gradle. https://github.com/TheAlgorithms/Java/pull/902

Nowadays, Gradle is the most common build tool for new Java projects.

**Comment by burnz248** [comment]
Is this still something that needs to be addressed?

**Comment by Adhikaribharath** [comment]
Is this still on going task? If so I would like to contribute :)

**Comment by Detective-Khalifah** [comment]
Excellent Idea!
