### ISSUE TITLE
[BUG] :broken links in DIRECTORY.md

### ISSUE THREAD

**Issue by IndranjanaChatterjee** [TheAlgorithms/Java#4753]
### Description

There are a number of broken links in `DIRECTORY.md`. On clicking them we are redirected to an error page.

Possible Solution: Delete the broken and unnecessary links from `DIRECTORY.md`.

### Excepted behavior

Expected to get redirected to working files. 

### Screenshots

![bug](https://github.com/TheAlgorithms/Java/assets/112919974/978e5b3c-1a07-484d-a79f-68241a20db52)

**Comment by sgrverma23** [comment]
Please assign this task to me, I will be removing the broken link as part of the changes.
@IndranjanaChatterjee @yeongmo-j @debasishbsws @vil02

**Comment by debasishbsws** [comment]
DIRECTORY.md file updated automatically after a buffer of time. there is no need to do it manually.
