### ISSUE TITLE
[FEATURE REQUEST] Standard Error of the Mean

### ISSUE THREAD

**Issue by RubyflameWarrior** [TheAlgorithms/Java#4764]
### What would you like to Propose?

New Algorithm under
https://github.com/TheAlgorithms/Java/tree/master/src/main/java/com/thealgorithms/maths

File Name Proposed: StandardMeanError.java

What?
A function to calculate the standard error of the mean of a provided data set.

### Issue details

Issue details
The standard error of the mean is used to evaluate the standard deviation of a sampling distribution.

Note: This issue is self-assigned and PR is raised as a part of Hacktoberfest

**Comment by RubyflameWarrior** [comment]
#4765

**Comment by Intruder9211** [comment]
To calculate the standard error of the mean (SEM) in Java, we can use the following steps:

Calculate the sample mean.
Calculate the sample variance.
Divide the sample variance by the sample size.
Take the square root of the result. #4764
[StandardError.txt](https://github.com/TheAlgorithms/Java/files/13066862/StandardError.txt)
