### ISSUE TITLE
Modified ClosestPair.java to be compliant with style sun rules for java code

### ISSUE THREAD

**Issue by MarisaAfuera** [TheAlgorithms/Java#477]
I've modified ClosestPair.java following checkstyle sun rules for java. I attach the new file. Like .java files aren't supported I've changed file extension .java by .txt

I can't make a Pull Request because I need permision to create a new branch. I learned to make a Pull Request in GithubSchool, and there I can make a Pull Request because a bot adds me as collaborator. But I'm not a collaborator ina TheAlgorithms/Java repository. If possible I would like to be collaborator here.

[ClosestPair.txt](https://github.com/TheAlgorithms/Java/files/2240887/ClosestPair.txt)

**Comment by varunu28** [comment]
@MarisaAfuera Just fork the repo by clicking the fork on top right corner. Then add the changes to forked repo and create a PR from forked repo to Master

**Comment by MarisaAfuera** [comment]
Hi Varun,

I've created a fork and made a pull request. Now the pull request is in my
fork but not in master. Did I make all right? Do I have to make anything
more?

Thanks in advance

Marisa

2018-07-30 18:05 GMT+02:00 Varun Upadhyay <notifications@github.com>:

**Comment by varunu28** [comment]
@MarisaAfuera There is no pull request from your fork to main repo. Make sure while opening the pull request you choose the correct from and to repos. 

Follow the link below:

[Pull Request](https://help.github.com/articles/creating-a-pull-request/)

**Comment by MarisaAfuera** [comment]
@Varun now I've made the pull resquest. It's a littles mess, because there
are two commits but only one new file ClosestFile.java. I hope to make
better next time.

Marisa

2018-07-31 20:16 GMT+02:00 Varun Upadhyay <notifications@github.com>:
