### ISSUE TITLE
[FEATURE REQUEST] To Add Multiple Dimensions in Distance Formula

### ISSUE THREAD

**Issue by shivansh-bhatnagar18** [TheAlgorithms/Java#4784]
### What would you like to Propose?

To Add Multi-Dimensional Distance Formulas 

### Issue details

The Distance Formula under the maths section can only work for two-dimensional points but to make this function more generic, I propose to make functions for multidimensional location points and calculate distance between them

**Comment by swaggybaba** [comment]
Distance between two points
[ x1 , x2 ] in 1-D is sqrt( ( x1 - x2 )^2 ) => | x1 -x2 |
[ ( x1 , y1 ) , ( x2 , y2 ) ] in 2-D is sqrt( ( x1 - x2 )^2 + (y1-y2)^2  )
[ ( x1 , y1  , z1 ) , ( x2 , y2 , z2 ) ] in 3-D is sqrt( ( x1 - x2 )^2 + (y1-y2)^2 +( y1 -y2 )^2 )

Similarly, for the multidimensional points the formula can be extended.
[multidimensional distance formula derivation.pdf](https://github.com/TheAlgorithms/Java/files/12901780/multidimensional.distance.formula.derivation.pdf)

**Comment by shivansh-bhatnagar18** [comment]
Dear Authors,
Please check and merge the pull request that I have made #4790

**Comment by Sooraj-Mlahi** [comment]
if this is not assigned to anyone please Assign it to me

**Comment by wannabetolkien** [comment]
I would like to get this task assigned to me. I am a new programmer and this will be a good issue to solve.
