### ISSUE TITLE
[FEATURE REQUEST] Add Cosine Similarity between vectors.

### ISSUE THREAD

**Issue by kmtGryffindor20** [TheAlgorithms/Java#4786]
### What would you like to Propose?

To Add implementation of Cosine Similarity computation between vectors.

### Issue details

Cosine Similarity is an important part of computing similarities between vectors usually in the data analysis area.
I propose to create an implementation of the computation of Cosine Similarity in the repository.

**Comment by kmtGryffindor20** [comment]
#4787

**Comment by srish-03** [comment]
Hi I am Interested Can You please assign me this
