### ISSUE TITLE
[FEATURE REQUEST] <Implementation of Stack using Queues>

### ISSUE THREAD

**Issue by IndranjanaChatterjee** [TheAlgorithms/Java#4789]
### What would you like to Propose?

Hello,
I would like to add the algorithm of implementation of Stack using Queues in java.

## Stack using Queues Algorithm

1. **Initialization:**
   - Create two empty queues, let's call them `queue1` and `queue2`.

2. **Push Operation:**
   - To push an element into the stack, enqueue the element to `queue1`.
   - Now pop all the elements from `queue2` until it becomes empty.
   - Swap the two queues.
   - For the next push operation `queue1` becomes `queue2` and vice versa.
   

3. **Pop Operation:**
   - pop the topmost element from `queue2`.

4. **Top Operation:**
   - Peek and return the last element from `queue2`.

### Additional Information

I would like to add this Algorithm

**Comment by renurao1306** [comment]
Hi, I am interested in implementing this. Could you provide information on which file would you want this to be in?

**Comment by arjun-rishi-2004** [comment]
Hi , I am interested in implementing Could you please assign this to me

**Comment by nayanbirla** [comment]
Hi, I am interested in implementing this. Could you please assign this

**Comment by srish-03** [comment]
Hi, I am interested in implementing this. Could you please assign this to me.
here's the sample of my work in the field : [https://linktr.ee/srishti_madaan__](LINKTREE)

**Comment by Venkateshsanwal** [comment]
Hi, I am interested in implementing the above issue can you please assign it to me i'll upload the pr immediately

**Comment by PankajKumarAgrawal1729** [comment]
Hi @IndranjanaChatterjee ,
I raised the PR for this Please check and merge it.

**Comment by sricharan200** [comment]
Hey @IndranjanaChatterjee 
I am interested in working on this issue, as this is part of my course assignment.
Can you please assign me this issue?

**Comment by siriak** [comment]
Let's wait for #4794

**Comment by zt202312** [comment]
what's
