### ISSUE TITLE
[FEATURE REQUEST] Add Dhondt electoral system algorithm

### ISSUE THREAD

**Issue by geektortoise** [TheAlgorithms/Java#4802]
### What would you like to Propose?

There is plenty of different electoral systems.

Their behavior have been defined without letting a way for misunderstanding.
So they are naturally algorithmic.

I would like to propose the new category "vote" or "electoral_system" containing these algorithm.

I will start with the one in application in my country : the Dhondt method

### Issue details

See https://en.wikipedia.org/wiki/Electoral_system for more information

**Comment by Asim-Sidd02** [comment]
I want to work on this issue
