### ISSUE TITLE
[FEATURE REQUEST] Add algorithms of some numerical integration techniques

### ISSUE THREAD

**Issue by kuv2707** [TheAlgorithms/Java#4805]
### What would you like to Propose?

I propose to add the algorithm for the Trapezoidal rule and Simpson's one-third rule of numerical integration.

I would also add the appropriate tests for them.

### Issue details

[Trapezoidal rule](https://en.wikipedia.org/wiki/Trapezoidal_rule)
[Simpson's rule](https://en.wikipedia.org/wiki/Simpson%27s_rule)

**Comment by pawaspy** [comment]
Assign me this i can implement this using java
