### ISSUE TITLE
Want to Add AI algorithms with Java 

### ISSUE THREAD

**Issue by Adidem23** [TheAlgorithms/Java#4859]
### What would you like to Propose?

I want to add some algorithms of core AI written In Java like 
  - A* algorithm
  - Minimax Algorithm
  - Constraint Satisfication Problem
  - Greedy Algorithm

### Issue details

I want to add some algorithms of core AI written In Java like 
  - A* algorithm
  - Minimax Algorithm
  - Constraint Satisfication Problem
  - Greedy Algorithm

**Comment by pragya0129** [comment]
1. For the A* algorithm, you can create a Java class that implements the A* search algorithm. Make sure to follow the coding standards and practices of the project you're contributing to.
2. For the Minimax algorithm, this is typically used in game-playing AI. You can create or integrate it into a game AI engine within the project.
3. Constraint Satisfaction Problem (CSP) algorithms can be implemented to solve specific problems. Create a Java class for CSP and make it general enough to handle various types of problems.
4. Greedy algorithms can also be implemented as needed within the project. Create Java classes for specific use cases where a greedy approach is applicable.
