### ISSUE TITLE
[FEATURE REQUEST] <Feat: Enhance the pow methods in the Math library>

### ISSUE THREAD

**Issue by yuluo-yx** [TheAlgorithms/Java#4893]
### What would you like to Propose?

I want to enhance the pow method in math, which currently only supports integer types, not double type data.

### Issue details

Input  number: x = 2.00000, n = 10
output: 1024.00000

Input  number: x = 2.10000, n = 3
output：9.26100

### Additional Information

No respose.

**Comment by Sooraj-Mlahi** [comment]
Can you assign this issue to me

**Comment by Karansenpai** [comment]
I have made a pr request please review

**Comment by Samankhalid01** [comment]
can I resolve this issue? if nobody is contributing on it rn
