### ISSUE TITLE
[FEATURE REQUEST] <Calculate the square root of x using the bisection method>

### ISSUE THREAD

**Issue by yuluo-yx** [TheAlgorithms/Java#4896]
### What would you like to Propose?

Calculate the square root of x using the bisection method

### Issue details

Example 1:
- Input: x = 4
- Output: 2

Example 2:
- Input: x = 8
- Output: 2
- Explanation: The arithmetic square root of 8 is 2.82842..., since the return type is an integer, the decimal part will be rounded off.

**Comment by chauhansumitdev** [comment]
Can I get this assigned to me?
