### ISSUE TITLE
Code Style is incorrect

### ISSUE THREAD

**Issue by DocJava** [TheAlgorithms/Java#49]
Java:
code is written to look like its C# (sure that SEEMS ok, but if the point of this code to introduce is to people then we'll just have more people writing code that does not look right) 

Scala
The Scala looks like the Java that looks like C# . Also, Scala is functional (or at least it can be) your code is essentially modified Java, yes it works, but it needs to be correct no?

Python
Only looked a tiny bit, but there is never a reason to return None at the end of a file,this happens already. If that was done for newb purposes then I suggest doing it in a comment instead? 

Other languages and Conclusion:
Using Intellij has helped many people when it comes to conforming to style standards. You may be thinking "Well that is just how I write it" Cool, neat, but if this is for other people, or even for recruiters to gawk at in amazement, would it not be better to have good examples online? 

(all that said, i like this project, its pretty cool to have stuff like this out here, I have a similar idea but RossetaCode kinda beat me to it )

**Comment by theycallmemac** [comment]
I agree with this, maybe if the three behind TheAlgorithms agree that each language should conform to a set standard, PEP8 for Python for example. I'll help if needed.

**Comment by jfsanin** [comment]
I guess writing "correct code" for every language is quite time consuming, as I understand this repository is just to learn about algorithms not a guide to write specific code in a specific language.

I agree that specific code help a lot of people to get better coding skills ("for example writing Scala in a functional way") but it is not the intention of this repository, however, the community could help to write better examples and make this repository more language-specific.
