### ISSUE TITLE
Do you need a visualization for the Skyline Problem?

### ISSUE THREAD

**Issue by gkhays** [TheAlgorithms/Java#492]
I like the repository! I found it browsing through the trending projects.

I was inspired by the `SkylineProblem` to do a visualization to illustrate how it works; see https://github.com/gkhays/skyline-problem. If there is any interest, I am willing to adapt it to project guidelines and submit a pull request.

![demo](https://user-images.githubusercontent.com/773981/44694325-6be42280-aa32-11e8-8d80-090ceae4b2a4.png)

In any case great work!

**Comment by varunu28** [comment]
@gkhays It is a typical interview problem and not an algorithm. We want to keep the implementations of well-known algorithms and not the implementations of problems on online judges
