### ISSUE TITLE
[FEATURE REQUEST] <Implementation of SHA  algorithm>

### ISSUE THREAD

**Issue by suxiaocha123** [TheAlgorithms/Java#4947]
### What would you like to Propose?

Implementation of SHA  algorithm.  

The full name of SHA is safe hashing algorithm, which is an algorithm that calculates a fixed length string (also known as message digest) corresponding to a digital message.

### Issue details

Implement SHA-256 algorithm.

Example ：
    Input:    BlockChain
    Output:  3a6fed5fc11392b3ee9f81caf017b48640d7458766a8eb0382899a605b41f2b9

**Comment by VikashSaharan1** [comment]
unsubscribed

**Comment by AbhinavKRN** [comment]
Assign this issue to me i can resolve this :)

**Comment by SarojArchana** [comment]
Can you Assign this issue to me I would love to  work on this.
