### ISSUE TITLE
[OTHER] Make `BoyerMoore.findmajor` return `java.util.Optional<Integer>`

### ISSUE THREAD

**Issue by vil02** [TheAlgorithms/Java#4949]
### What would you like to share?

Current implementation of [`BoyerMoore.findmajor`](https://github.com/TheAlgorithms/Java/blob/945e7b56bb186c3be908e02720e932b5ce834e01/src/main/java/com/thealgorithms/others/BoyerMoore.java#L13) returns `-1` in case when there is no _majority element_. This is confusing, since the input array could contain `-1`. I suggest to change this method to return [`java.util.Optional<Integer>`](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html).

### Additional information

Solving this is a goof opportunity to clean up the existing code, I would suggest to introduce new private methods like `findCandidate`, `calculateOccurrences` and `isMajority`.

**Comment by prathameshpowar1910** [comment]
Could you assign this issue to me?

**Comment by vil02** [comment]
@prathameshpowar1910 when you will create a PR closing this, please _mention_ me.

**Comment by prathameshpowar1910** [comment]
@vil02 i have opened a PR #4951 but the build is failing could you look into it?

**Comment by prathameshpowar1910** [comment]
@vil02 There is some issue with the linting could you solve that?

**Comment by vil02** [comment]
Solved by #4951.
