### ISSUE TITLE
[FEATURE REQUEST] <Solve the N-Queens problem using recursion>

### ISSUE THREAD

**Issue by akshithagunupati** [TheAlgorithms/Java#4968]
### What would you like to Propose?

I propose a solution to the N-Queens problem. This challenging puzzle involves placing N queens on an N×N chessboard in such a way that no two queens threaten each other. My approach leverages the power of recursion, a fundamental programming technique, to efficiently navigate the complex decision space and find a valid placement for each queen. By outlining the recursive algorithms and strategies employed, my proposal aims to provide a clear and insightful solution to this classic problem in computer science.

### Issue details

The issue at hand involves the N-Queens problem, a classic chessboard puzzle where the objective is to place N queens on an N×N board without any two queens threatening each other. The algorithmic details encompass the intricacies of employing recursion as a primary strategy to navigate the puzzle's decision space efficiently. The proposed solution involves outlining the recursive techniques and algorithms designed to find a valid queen placement on the chessboard. This paragraph encapsulates the essence of the N-Queens problem and highlights the recursive approach taken to address this challenging puzzle.

**Comment by siriak** [comment]
It's already implemented [here](https://github.com/TheAlgorithms/Java/blob/e759544c333de9b98ff51458e1d71c69006f976b/src/main/java/com/thealgorithms/backtracking/NQueens.java#L35)
