### ISSUE TITLE
[OTHER] Simplify MinimizingLateness.java.

### ISSUE THREAD

**Issue by inishantjain** [TheAlgorithms/Java#5000]
### What would you like to share?

Under the minimizing lateness package / category [https://github.com/TheAlgorithms/Java/tree/master/src/main/java/com/thealgorithms/minimizinglateness](https://github.com/TheAlgorithms/Java/tree/master/src/main/java/com/thealgorithms/minimizinglateness) 

The current code MinimizingLateness.java utilizes the FileReader to read from a file named "lateness_data.txt". However, since this code serves as a demonstration, we can enhance clarity by directly inserting the data into the Java file. Additionally, running the code on the website's code playground is restricted, making inline data a more practical choice.

I've opened a pull request #4999 with the modifications.

**Comment by SarthakChaudhary46** [comment]
Is it still open? 
Shall I work on it?
