### ISSUE TITLE
[FEATURE REQUEST] <Check Consonants>

### ISSUE THREAD

**Issue by mpousmali** [TheAlgorithms/Java#5002]
### What would you like to Propose?

Hello,
I would like to implement the check consonants algorithm!

### Description:
Check consonants algorithm is an algorithm which will check if a given string contains consonants. 

### Additional Information

Returns true if the string contains consonants, false otherwise. 
_For example:_
Given the "aaa" string the algorithm will return false.
Given the "str" string the algorithm will return true.

**Comment by siriak** [comment]
It's not the kind of algorithm that we include here
