### ISSUE TITLE
[FEATURE REQUEST] <Vowels Count>

### ISSUE THREAD

**Issue by mpousmali** [TheAlgorithms/Java#5003]
### What would you like to Propose?

I would like to implement an algorithm that counts vowels of a string. 

### Issue details

The algorithm will count and return the number of vowels in a string. 

### Additional Information

_Example:_
Given the string "string", algorithm will return 1.
Given the string "str" algorithm will return 0.

**Comment by siriak** [comment]
It's not the kind of algorithm that we include here
