### ISSUE TITLE
Better descriptive comments could be added.

### ISSUE THREAD

**Issue by SarthakChaudhary46** [TheAlgorithms/Java#5035]
### What would you like to Propose?

Better descriptive comments could be added, as seen in the rest of the stack codes present in the folder!

### Issue details

- Every code present in the same folder precisely describes the issue it addresses and outlines the steps it takes to resolve that issue.
- But "CalculateMaxOfMin" just gives a very brief outline of the problem.
- Location : src/main/java/com/thealgorithms/stacks/CalculateMaxOfMin.java

**Comment by mvouzikis** [comment]
Hallo, i would like to contribute to the project and this issue seems managable and interesting, can i fork the repo and have a look on the mentioned issue to try and fix it?

**Comment by SarthakChaudhary46** [comment]
Sure!

**Comment by SarthakChaudhary46** [comment]
> Hallo, i would like to contribute to the project and this issue seems managable and interesting, can i fork the repo and have a look on the mentioned issue to try and fix it?

Still working on it?
