### ISSUE TITLE
test Integration

### ISSUE THREAD

**Issue by khalil2535** [TheAlgorithms/Java#504]
I suggest to use one of the test Integrations that github provides in the market place for <a href="https://github.com/TheAlgorithms/Java/tree/Development">Development</a> branch, that can show test results for any pulled request instantly.

**Comment by varunu28** [comment]
@khalil2535 We would be adding an integration in future. We would have to figure out after a discussion which would be the right integration model for the repo and that is on the agenda including creating a complete build pipeline. 

As of now our focus is to add complete test coverage for all algorithms and shift the Development to master branch
