### ISSUE TITLE
"Temperature Conversion" could be further added in the list of conversion algorithms.

### ISSUE THREAD

**Issue by SarthakChaudhary46** [TheAlgorithms/Java#5042]
### What would you like to Propose?

- New Code for temperature conversion could be added to Conversion algos.
- Location : src/main/java/com/thealgorithms/conversions.
- A single file could be added that converts temperatures between different scales such as Celsius, Fahrenheit, and Kelvin.

### Issue details

The algorithms that people write for temperature conversion may vary in approach or perspective. However, a generalized algorithm could be developed to assist those who struggle to devise their own approach or to aid them in better understanding the concept.

**Comment by markmyersCS** [comment]
I can do this
