### ISSUE TITLE
[BUG] There is a issue with clang file for latest clang versions

### ISSUE THREAD

**Issue by TharunTech** [TheAlgorithms/Java#5049]
### Description

i was formating the files using clang and it shows 
`error: unknown key 'InsertNewlineAtEOF' 
InsertNewlineAtEOF: true
^~~~~~~~~~~~~~~~~~ `

### Steps to reproduce

Install and Run
clang-format -i -style=file ./withUrFileName.java

### Excepted behavior

must format the java document without any error prompt

**Comment by vil02** [comment]
Which version of `clang-format` are you using? `InsertNewlineAtEOF` was introduced in `clang-format-16`.

**Comment by TharunTech** [comment]
Ok, thanks for the clarification!!
