### ISSUE TITLE
[FEATURE REQUEST] Sleep Sort Algorithm

### ISSUE THREAD

**Issue by pankaj-bind** [TheAlgorithms/Java#5137]
### What would you like to Propose?

Sleep sort is a unique sorting algorithm that utilizes sleep functions to achieve sorting. The basic idea behind the algorithm is to assign each element in the list to a separate thread. Each thread then sleeps for an amount of time proportional to the value of the element it is assigned. Once all threads have finished sleeping, the elements are sorted in ascending order based on the time they took to sleep.

### Issue details

Algorithm Description: Provide a clear and concise explanation of the Sleep Sort algorithm.
Implementation: Implement the Sleep Sort algorithm in the programming language of your choice.
Testing: Develop test cases to ensure the correctness of the implementation.
Documentation: Document the code and algorithm to facilitate understanding for future developers.

### Additional Information

Sleep sort is not suitable for practical use due to its inefficiency and unpredictability. It's mainly used for educational and entertainment purposes.

**Comment by pankaj-bind** [comment]
assign me

**Comment by SAIVARDHAN15** [comment]
hey, @pankaj-bind if you are not working on it, can it be assigned to me?

**Comment by pankaj-bind** [comment]
> hey, @pankaj-bind if you are not working on it, can it be assigned to me?

it is not yet assigned

**Comment by VarshaUN** [comment]
Hi @pankaj-bind , I hope this message finds you well. I wanted to check in and see if the issue you mentioned is still open. If it is, please feel free to assign it to me, and I'll be happy to assist. Thank you, Varsha

**Comment by aishuarya** [comment]
Hi @yanglbme 
I have raised[ a PR](https://github.com/TheAlgorithms/Java/pull/5285) for this ,could you check
