### ISSUE TITLE
Add Degrees to Radians to Conversions

### ISSUE THREAD

**Issue by nitroxplunge** [TheAlgorithms/Java#520]
I think it would be useful to add Degrees to Radians and vice versa to the Conversions section. It's commonly used and I think it fits there.

**Comment by varunu28** [comment]
That is a basic mathematical conversion and I don't think that comes under any domain of algorithms. I think you are talking about below conversion, please correct me if you have any other algorithm in mind

```
radians = degrees * (pi/180)
degrees = radians * (180/pi)
```
