### ISSUE TITLE
求算法的中文名

### ISSUE THREAD

**Issue by yoonb-amor** [TheAlgorithms/Java#5323]
### What would you like to share?

好项目，但是中文不好看不懂呀

**Comment by siriak** [comment]
你想翻译DIRECTORY.md成中文，是吗？我们不会改变中文的内容，所以我们只用英文。

**Comment by yoonb-amor** [comment]
可以用gpt翻译一下，哈哈
![image](https://github.com/user-attachments/assets/8bc8eea1-73d4-467f-bb73-13148cc223d0)

**Comment by yoonb-amor** [comment]
Good project, thank you to the author. If the Chinese is not good, you can use GPT to translate it
