### ISSUE TITLE
[FEATURE REQUEST] <title>Add new algorithm under Graph algorithms Edmonds 

### ISSUE THREAD

**Issue by dinesh15** [TheAlgorithms/Java#5447]
### What would you like to Propose?

I would like to propose the addition of the Edmonds' Algorithm to the repository. Edmonds' algorithm, also known as the Maximum Weight Matching algorithm for general graphs, is highly useful in graph theory for solving problems involving matching in graphs. I have implemented this algorithm in a scalable and optimized way, which I believe will enhance the algorithmic coverage of the repository and provide value for users working on graph-based problems.

### Issue details

The repository currently lacks an implementation of Edmonds' Algorithm. My implementation includes:

Finding maximum weight matching in a general (possibly non-bipartite) graph.
Handling weighted and unweighted graphs.
Efficiency improvements over a naïve approach by reducing the time complexity.

**Comment by siriak** [comment]
Sounds great, feel free to add it!

**Comment by dinesh15** [comment]
Sure Will Do

**Comment by wxm2004** [comment]
Thank you for your proposal! Edmonds' Algorithm would indeed be a great addition to the repository and would expand the algorithmic coverage significantly. 
 I can help review your implementation to ensure it meets the repository’s code standards and performance requirements. If needed, I can assist with writing or improving the documentation to help other developers understand and use the algorithm effectively.
I look forward to collaborating with you and contributing to this issue.

**Comment by dinesh15** [comment]
Sure @wxm2004 let me know what time works for you for a quick call?

**Comment by donutz03** [comment]
I can work on this if that's ok. :)

**Comment by dinesh15** [comment]
I was still working on it.

**Comment by donutz03** [comment]
Sure, how can I help?

**Comment by Brijeshthummar02** [comment]
Guys i've already pulled a request so wait for the review.
