### ISSUE TITLE
Compiling error in SinglyLinkedList.java

### ISSUE THREAD

**Issue by sachincool** [TheAlgorithms/Java#546]
In https://github.com/TheAlgorithms/Java/blob/77259b73b18a1eede7cf0e3fe75aeb580e9faf24/DataStructures/Lists/SinglyLinkedList.java#L48

The user is calling for empty constructor but there's none provided. 
Results in 

```java
ss.java:48: error: constructor Node in class Node cannot be applied to given types;
        Node newNode = new Node();
                       ^
  required: int
  found: no arguments
  reason: actual and formal argument lists differ in length
ss.java:49: error: cannot find symbol
        newNode.data = data;
               ^
  symbol:   variable data
  location: variable newNode of type Node
```
we don't really need an empty constructor simple solution would be to use the parameterzed constructor already built.

**Comment by ulvimardaliyev** [comment]
@yanglbme this should be closed, too

**Comment by yanglbme** [comment]
@ulvimardaliyev ok, thanks 😄
