### ISSUE TITLE
[FEATURE REQUEST] Implement Edmonds Blossom Algorithm for Maximum Matching in General Graphs

### ISSUE THREAD

**Issue by TarunVishwakarma1** [TheAlgorithms/Java#5470]
### What would you like to Propose?

Hey I saw a Feature Request for Edmond Algorithm and wanted to add another Algorithm - Edmonds Blossom Algorithm, under the data structure/graphs

The Edmonds Blossom Algorithm extends traditional matching algorithms to handle odd-length cycles by "contracting" blossoms, reducing them to single vertices, and applying matching logic recursively. Once the blossom is removed, the algorithm can continue finding the maximum matching in the graph.

The algorithm has applications in:

Graph Theory problems, including finding matchings in bipartite and non-bipartite graphs.
Network Flow problems.
Optimization problems, such as in scheduling and pairing tasks.

### Issue details

<NO DETAIL>

**Comment by Zanuah** [comment]
I would like to implement this.  What is the process of getting assigned to this issue, or should I implement and create a PR?

**Comment by Zanuah** [comment]
Got it

**Comment by siriak** [comment]
Please make your PR active once it's ready to be reviewed

**Comment by TarunVishwakarma1** [comment]
PR active
