### ISSUE TITLE
 [FEATURE REQUEST] Add a Recursion Package

### ISSUE THREAD

**Issue by shivammm21** [TheAlgorithms/Java#5504]
### What would you like to Propose?

I would like to propose the addition of a Recursion package to the repository. While there are existing packages for Dynamic Programming, there is currently no dedicated package for Recursion, which is fundamental for solving problems like generating subsets, permutations, and power sets. Recursion is crucial for building a strong foundation in algorithm design and problem-solving, especially as it underpins many dynamic programming approaches.

This addition would not only enhance the algorithm collection but also help learners and developers better understand recursive problem-solving strategies before moving on to more complex topics like dynamic programming.

### Issue details

I would like to propose adding a new Recursion package in the repository. While the repository currently contains a Dynamic Programming package, there is no dedicated package for Recursion, which is essential for solving fundamental problems. Recursion is the backbone for algorithms that generate subsets, permutations, and power sets, among others. These problems cannot be efficiently solved without a good understanding of recursion. Recursion also lays the foundation for understanding and solving Dynamic Programming problems, which build upon recursive solutions.

**Comment by TarunVishwakarma1** [comment]
Are you working on this ?

**Comment by c99SRS** [comment]
@shivammm21 assign this to me, i will do the needful

**Comment by shivammm21** [comment]
> Are you working on this ?

Yep, I have been working on that.

**Comment by TarunVishwakarma1** [comment]
> > Are you working on this ?
> 
> Yep, I have been working on that.

Okay 😃

**Comment by raxvab** [comment]
Hi @shivammm21  could you assign this issue to me as this is my first time contributing It'll be great to kickstart with such issue.

**Comment by shivammm21** [comment]
> Hi @shivammm21  could you assign this issue to me as this is my first time contributing It'll be great to kickstart with such issue.
> 

Actually, I have already created pr for this issue...

**Comment by Tuhinm2002** [comment]
> > Hi @shivammm21  could you assign this issue to me as this is my first time contributing It'll be great to kickstart with such issue.
> 
> Actually, I have already created pr for this issue...

It is not an assignment. It is a feature request originally created by me. So close any conflicting pull requests and read contribution.md first before contributing,

**Comment by Esmail2019** [comment]
Can I work on this issue?
