### ISSUE TITLE
[FEATURE REQUEST] Add Maximum Sum of Non-Adjacent Elements Algorithm

### ISSUE THREAD

**Issue by Guhapriya01** [TheAlgorithms/Java#5510]
### What would you like to Propose?

I would like to propose adding an implementation of the **Maximum Sum of Non-Adjacent Elements** algorithm to the **dynamic programming** section of the repository.

### Issue details

**Problem Statement:**
Given an array of integers, write a function to find the maximum sum of non-adjacent elements. The elements can be chosen such that no two chosen elements are adjacent in the array.

**For example:**
Input: [3, 2, 5, 10, 7]
Output: 15 (The maximum sum is obtained by selecting 3, 7, and 5)

**Approach:**
1. Use dynamic programming to maintain a running maximum sum.
2. For each element, decide to either include it in the sum (and skip the previous element) or exclude it (and keep the sum up to the previous element).

**Comment by siriak** [comment]
Sure, go ahead and add it

**Comment by Gautamali** [comment]
Would like to contribute to these issue asign me :)

**Comment by Guhapriya01** [comment]
Thank you! I'll start working on it.

**Comment by Nandinig24** [comment]
Please assign the task to me as a hacktoberfest contributor

**Comment by lfcbird** [comment]
Is task still open? if yes please assign the task to me as a hacktoberfest contributor

**Comment by KSVeerendernath** [comment]
Hi @Guhapriya01  ,
I hope you're doing well!

This is Veer, and I’m currently pursuing my master's degree. As part of one of my course assignments, I need to select a GitHub repository and contribute to it in some capacity. I came across your repository and would love to work on this particular issue.

It would be greatly appreciated if you could assign the issue to me and allow me to contribute. Please feel free to reach out if you have any questions or need further information from my side.

Thanks,
Veer

**Comment by siriak** [comment]
Added in #5544
