### ISSUE TITLE
[FEATURE REQUEST] <title> Add Elliptic Curve Cryptography (ECC) Algorithm

### ISSUE THREAD

**Issue by SaiSrujanReddyP** [TheAlgorithms/Java#5525]
### What would you like to Propose?

I would like to propose adding an implementation of the Elliptic Curve Cryptography (ECC) algorithm to the ciphers section of the repository. Elliptic Curve Cryptography (ECC) is a widely-used public-key encryption technique that provides strong security with smaller key sizes compared to RSA. It is essential in modern cryptographic protocols, including SSL/TLS, blockchain (Bitcoin, Ethereum), and digital signatures (ECDSA). The implementation will include point addition, scalar multiplication, key generation, encryption, decryption, and ECDSA.

### Issue details

The repository currently lacks an implementation of Elliptic Curve Cryptography (ECC). My implementation includes:

Elliptic Curve Operations: Point addition and scalar multiplication, which are essential for ECC's cryptographic functions.
Key Generation: Generating public and private keys using elliptic curve cryptographic methods.
Encryption and Decryption: Encrypting data using a recipient's public key and decrypting it with the corresponding private key.
Elliptic Curve Digital Signature Algorithm (ECDSA): Implementing the signing and verification of digital signatures, a practical use of ECC in real-world applications.

### Additional Information

ECC provides strong security with smaller key sizes compared to traditional algorithms like RSA, making it ideal for resource-constrained devices and modern cryptographic protocols.

**Comment by ShreeHarish** [comment]
I would like to work on this

**Comment by SaiSrujanReddyP** [comment]
@ShreeHarish Great.. But I already have the code ready with me I am just waiting for approval to work on it.

**Comment by ShreeHarish** [comment]
My bad, I searched for pull requests regarding this issue number and couldnt find any. Hence I started working on it.

**Comment by SaiSrujanReddyP** [comment]
No worries, there a lot of other issues you can work on. I hope you find yours , good luck.

**Comment by siriak** [comment]
Sounds great, let's add it!

**Comment by SaiSrujanReddyP** [comment]
@siriak Can you assign this to me?

**Comment by SaiSrujanReddyP** [comment]
Please add hacktoberfest and hacktoberfest-accepted labels to this issue now and PR after I am done with merging it.
