### ISSUE TITLE
Binary Search Algorithm in Java

### ISSUE THREAD

**Issue by Sameeratweb** [TheAlgorithms/Java#5529]
### What would you like to Propose?

An Java Program performing Binary Search Operation

### Issue details

Adding An program that performs Binary search using Java

**Comment by purnimasharma06** [comment]
Hi, I'd like to contribute by adding a Java program that performs a binary search operation. Could you please assign this task to me?

Thank you!

**Comment by AnushkJain2201** [comment]
Hey!! I will contribute by adding this algorithm. Please assign me this issue.

Thank You!!

**Comment by YoosufAathil** [comment]
Hi !!!, I would like to work on this, could you please assign me on this.

Thank You in Advance

**Comment by tejaswi0910** [comment]
Hey @Sameeratweb 
I think it is already implemented [here](https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/searches/BinarySearch.java)

**Comment by shubh-dev1** [comment]
hey, is the repo still open for the hacktoberfest contribution
