### ISSUE TITLE
[FEATURE REQUEST] Adding the Lowest Set Bit Implementation

### ISSUE THREAD

**Issue by prayas7102** [TheAlgorithms/Java#5566]
### What would you like to Propose?

**Overview**
The goal of this proposal is to implement a LowestSetBit class that provides efficient methods for manipulating and analyzing the lowest set bit in a given integer. This class will be useful for various applications in competitive programming, algorithm design, and software development where bit manipulation is required.

**Objectives**
Isolation of the Lowest Set Bit: Create a method to isolate the lowest set bit of a number using bitwise operations.
Providing Information: Return the number after clearing lowest set bit.

**Key Features**
Efficiency: The operations will be performed using bitwise manipulation, ensuring O(1) time complexity for each operation.
Edge Case Handling: The class will handle edge cases such as zero and negative numbers appropriately.
User-Friendly API: Provide simple methods with clear documentation for ease of use.

This method will return a number after clearing the lowest set bit.

### Issue details

**Implementation Details**

isolateLowestSetBit(int n): This method will return the value of the lowest set bit in the integer n.
Implementation: return n & -n; (using two's complement to isolate the lowest set bit).

**Testing**
To ensure the functionality and reliability of the LowestSetBit class, a comprehensive test suite will be created. The tests will cover:

- Regular positive integers.
- Edge cases like zero and one.
- Powers of two.
- Numbers with all bits set.
- Negative integers.

### Additional Information
Required PR for this issue https://github.com/TheAlgorithms/Java/pull/5567

**Comment by AnamuddinAhmad** [comment]
I want to work for this problem/Issue please assing me for this work.

**Comment by ishanki19-pixel** [comment]
I have made a PR for the above issue: #5574
Please review it!
If you feel it worthy then please label it as hacktoberfest accepted

Thank you

**Comment by Nandinig24** [comment]
Please assign the task to me as a hacktoberfest contributor

**Comment by siriak** [comment]
Done in #5567
