### ISSUE TITLE
[FEATURE REQUEST] new dp algo `UniqueSubsequenceCount`

### ISSUE THREAD

**Issue by Tuhinm2002** [TheAlgorithms/Java#5587]
### What would you like to Propose?

This algo counts the number of unique subsequence or subsets can be produced from a string.

* Test cases

```
public class UniqueSubsequencesCountTest {

    @Test
    void subseqCountTestOne() {
        String s = "abc";

        assertEquals(7, UniqueSubsequencesCount.subseqCount(s));
    }

    @Test
    void subseqCountTestTwo() {
        String s = "abcdashgdhas";

        assertEquals(3592, UniqueSubsequencesCount.subseqCount(s));
    }

    @Test
    void subseqCountTestThree() {
        String s = "aaaaa";

        assertEquals(5, UniqueSubsequencesCount.subseqCount(s));
    }
}

```

### Issue details

This algorithm is missing but is an important approach in dynamic programming

**Comment by RahulMohanK** [comment]
@Tuhinm2002 I would like to add solution to this problem. Could you please assign it to me ?

**Comment by Tuhinm2002** [comment]
> @Tuhinm2002 I would like to add solution to this problem. Could you please assign it to me ?

That's not an assignment that is a feature request created by me. There is already a PR  for this

**Comment by Tuhinm2002** [comment]
@siriak hey i created a new pr for a new algo in dp check out here https://github.com/TheAlgorithms/Java/pull/5586

**Comment by Aastha-ojha-20** [comment]
please assign this to me
