### ISSUE TITLE
Other/Dijkshtra.java has some problems. I would like to recommend it's removal.

### ISSUE THREAD

**Issue by rmakynen** [TheAlgorithms/Java#560]
Other/Dijkshtra.java has some problems:
- Hard-coded magic numbers (1000000l)
- initialization of a very large 2-dimensional array when it is not needed when using another implementation. - No description was given on the input format the algorithm was expecting.
- Poor commenting.
- Name of the algorithm is wrong. Should be "Dijkstra"

I have created a new pull request #559 that has new code for the algorithm. It has none of the above mentioned problems from what I can tell.

If the previously mentioned pull gets accepted, then I would recommend that the old version "Dijkshtra.java" should be removed.

**Comment by prashantdoshi28** [comment]
Hey @vishnoitanuj , I have requested some changes, go through my review for those.
