### ISSUE TITLE
[FEATURE REQUEST] Adding Kadane's Algorithm

### ISSUE THREAD

**Issue by Rupa-Rd** [TheAlgorithms/Java#5601]
### What would you like to Propose?

I would like to propose a Java solution to kadane's algorithm. 

### Issue details

In the Algorithm website (https://the-algorithms.com/algorithm/kadane-algo?lang=javascript), there is no solution approach in Java.
So, I would like to include a solution in Java.

**Comment by Nandinig24** [comment]
Please assign the task to me I would surely help!

**Comment by Pranjul2002** [comment]
i would like to complete this task, please assign it to me, I will surely do my best.

**Comment by Shreyaww** [comment]
Can you please assign this issue to me as this would be my first contribution in hacktoberfest

**Comment by Rupa-Rd** [comment]
Kadane's algorithm for Java is already existing. I apologize for my negligence.
