### ISSUE TITLE
Transposition cipher

### ISSUE THREAD

**Issue by SimranLahrani842** [TheAlgorithms/Java#5622]
### What would you like to Propose?

Would like to add transposition cipher in cipher folder. 

### Issue details

The Transposition Cipher Technique is an encryption method used to encrypt a message or information. This encryption method is done by playing with the position of letters of the plain text.

**Comment by govindraj111** [comment]
Hi Team, could you assign me this?
I would love to contribute.

**Comment by gourab9817** [comment]
I have a better approach to solve this could you please assign it to me
