### ISSUE TITLE
[FEATURE REQUEST] Add New Bit Manipulation Algorithms

### ISSUE THREAD

**Issue by sanvviratthore** [TheAlgorithms/Java#5628]
### What would you like to Propose?

I would like to contribute additional bit manipulation algorithms to the repository. Below are some algorithms I plan to implement:

1. Find the Number Appearing Odd Times
2. Swap Adjacent Bits of a Number
3. Bitwise XOR of All Elements in an Array

### Issue details

Algorithm 1:
Find the Number Appearing Odd Times
In an array where all numbers appear even times except one, we find the number that appears an odd number of times using bit manipulation (XOR).

Algorithm 2:
Swap Adjacent Bits of a Number
Swap every pair of adjacent bits of a given number.

Algorithm 3:
Bitwise XOR of All Elements in an Array
Compute the XOR of all elements in an array.

### Additional Information

I will ensure the implementation follows the existing coding standards and will include unit tests for each algorithm.

**Comment by Aastha-ojha-20** [comment]
please assign this to me

**Comment by DarkMatter-999** [comment]
Hey @sanvviratthore , 
I think the algorithms 1 and 3 are the same / can be solved using same code. 
Can you explain each of the algorithm further if there is a difference?

**Comment by jiwansh** [comment]
Can you please assign it to me?

**Comment by 07-Atharv** [comment]
Can you assign this issue to me?

**Comment by MQ-06** [comment]
Hey, @sanvviratthore   

I’d like to propose adding more algorithms, such as:

Count Set Bits in an Integer: Efficiently count the 1s in a binary representation.
Reverse Bits of a Number: Reverse the order of bits in a binary number.
Looking forward to contributing and discussing further! 😊
