### ISSUE TITLE
[FEATURE REQUEST]  Add a Regular Expression Matching Problem in a Recursion 

### ISSUE THREAD

**Issue by Shreya-1305** [TheAlgorithms/Java#5637]
### What would you like to Propose?

A solution whiich will be easy to understand by all the users 

### Issue details

Here is the Problem description 

Given an input string s and a pattern p, implement regular expression matching with support for '.' and '*' where:

'.' Matches any single character.​​​​
'*' Matches zero or more of the preceding element.
The matching should cover the entire input string (not partial).

**Comment by Taranpreet10451** [comment]
@siriak I would also like to work on this issue.

**Comment by Bucke200** [comment]
Hey @siriak i am interested in this issue can u assign me this issue.

**Comment by siriak** [comment]
It's already implemented here https://github.com/TheAlgorithms/Java/blob/e38611e9db0fdf318ac8513709f75077c55f25e3/src/main/java/com/thealgorithms/dynamicprogramming/RegexMatching.java#L14
