### ISSUE TITLE
Adding date-related algorithms

### ISSUE THREAD

**Issue by codingBoy5418** [TheAlgorithms/Java#5653]
### What would you like to Propose?

Add date-related algorithms

### Issue details

Provide date-related algorithms：

- Conversion algorithm between Date objects and Date strings.

- Conversion between Date objects and timestamps.

- Conversion between Date strings and timestamps.

- Algorithm to obtain the maximum value among multiple dates.

- Algorithm to obtain the minimum value among multiple dates.

- Algorithm to add or subtract years, months, days, hours, minutes, and seconds from a Date.

- Algorithm to calculate the difference in years, months, days, hours, minutes, and seconds between two Dates.

**Comment by govindraj111** [comment]
Hi Team, could you assign me this?
I would love to contribute.

**Comment by siriak** [comment]
These are not algorithms we are looking for, they don't apply any specific techniques
