### ISSUE TITLE
[FEATURE REQUEST] <title>Adding Hare and Tortoise Algorithm 

### ISSUE THREAD

**Issue by Bhumika-00** [TheAlgorithms/Java#5693]
### What would you like to Propose?

I would like to contribute Hare and Tortoise Algorithm as it is one of the most important concept when it comes to linked list 

### Issue details

I will add the algorithm in the linked list part

**Comment by ANkurNagila** [comment]
Hello Bhumika 

I am working on the issue and will be adding the Algorithm in the Linked List Section.

**Comment by ba-00001** [comment]
I am working in the issue

**Comment by Bhumika-00** [comment]
Can you please assign me this issue
