### ISSUE TITLE
[BUG] Negative or Zero IDF Scores in BM25 Due to Missing Smoothing Constant

### ISSUE THREAD

**Issue by prayas7102** [TheAlgorithms/Java#5697]
### Description

In the PR summited by me in #5615 I mistakenly did not include the smoothing constant (+1) in Inverse Document Frequency (IDF) calculation (line no. 218 in BM2InvertedIndex.java). When the smoothing constant (+1) is omitted from the IDF formula in the BM25 algorithm, it can lead to negative or zero IDF scores for common terms. This occurs because, without the +1, the value inside the logarithm can fall below 1 for terms that appear frequently in the document corpus. Negative or zero IDF scores can distort document relevance ranking, causing common terms to either contribute negatively or have no impact on the final score, resulting in inaccurate search results. Adding the +1 ensures all terms, even frequent ones, contribute positively, maintaining balanced relevance scoring.

### Steps to reproduce

1. Go To: BM2InvertedIndexTest.java
2. Run function `testSearchRanking()`
3. Test cases passes with movie: It's a Wonderful Life (docId: 6) ranked first according to the relevance score. But in accordance with the search algorithm the movie Shawshak Redemption (docId: 1) should come first.
4. Apparently the test cases were written wrong too.
4. The same apply to other movies in the search list.

### Excepted behavior

The movie Shawshak Redemption (docId: 1) should come first instead of the movie It's a Wonderful Life (docId: 6)

### Screenshots

Current Behaviour:
![image](https://github.com/user-attachments/assets/50d67cb4-0b82-4e76-b9b7-939fcf59a580)

Expected Behaviour:
![image](https://github.com/user-attachments/assets/84323527-563f-4f9f-8a01-329a38d311dc)

### Additional context

Required PR : #5696

**Comment by shamsulalam1114** [comment]
1.in line 218:
double idf = Math.log((totalDocuments - docFrequency) / docFrequency);
2. next,to prevent the IDF values:
double idf = Math.log((totalDocuments - docFrequency + 1) / (docFrequency + 1));

**Comment by SAIVARDHAN15** [comment]
I would like to solve this issue

**Comment by prayas7102** [comment]
> 1.in line 218: to prevent the IDF values: double idf = Math.log((totalDocuments - docFrequency + 1) / (docFrequency + 1));

The issue is already resolved and merged so closing it.
