### ISSUE TITLE
[FEATURE REQUEST] <title>Adaptive mergesort 

### ISSUE THREAD

**Issue by anant-jain01** [TheAlgorithms/Java#5711]
### What would you like to Propose?

i would like to add adaptive mergesort algorithm to the repo.
Please assign me the issue under the hacktoberfest tag

### Issue details

adaptive mergesort is an adaptive version of mergesort, as it :-
1)Efficiency with Partially Sorted Data: Performs better on nearly sorted arrays.
2)Reduced Time Complexity: O(n).
3)Fewer Merges: Reduces the number of merge operations needed.

**Comment by jiwansh** [comment]
I want to work on this issue! please assign it to me;
