### ISSUE TITLE
[FEATURE REQUEST] Add Ubiquitous Binary Search

### ISSUE THREAD

**Issue by anijit18** [TheAlgorithms/Java#5851]
### What would you like to Propose?

The “Ubiquitous Search Algorithm” would typically refer to a straightforward search method where we converge the search space till 'l' and 'r' points single element. If the middle location falls in the first pulse, the condition (A[m] < A[r]) doesn’t satisfy, we converge our search space to A[m+1 … r]. If the middle location falls in the second pulse, the condition (A[m] < A[r]) satisfied, we converge our search space to A[1 … m]. At every iteration we check for search space size, if it is 1, we are done. 
 
-> Worst-case performance Θ(N) 
-> Best-case performance O(1) 
-> Average-case performance Θ(log(N))

### Issue details

We are handling the corner cases in the present in the Binary Search in more effecient way in Ubiquitous Binary Search.

**Comment by subham-behera** [comment]
@anijit18 I would like to work on the following issue.

**Comment by raghavy11** [comment]
i'm interested in doing it! can you assign this to me

**Comment by SREERAM-KT** [comment]
@anijit18 I would like to work on this task, please help in assigning it to me

**Comment by sachininfy51** [comment]
Hi @anijit18 ,

I would like to propose my interest in contributing to the implementation of the "Ubiquitous Search Algorithm" as described in the issue details. I believe this algorithm could improve the handling of corner cases in the current binary search implementation.

I have experience with search algorithms and optimization techniques, and I am eager to explore the convergence of the search space as outlined. I can help ensure that we achieve the desired performance metrics:

- Worst-case performance: Θ(N)
- Best-case performance: O(1)
- Average-case performance: Θ(log(N))

If possible, could you please assign this issue to me? I look forward to collaborating with the team on this enhancement!

Thank you!
