### ISSUE TITLE
[FEATURE REQUEST] Add Meta Binary Search

### ISSUE THREAD

**Issue by anijit18** [TheAlgorithms/Java#5852]
### What would you like to Propose?

Meta Binary Search, also known as One-Sided Binary Search, is a variation of the binary search algorithm that is used to search an ordered list or array of elements. This algorithm is designed to reduce the number of comparisons needed to search the list for a given element.

The basic idea behind Meta Binary Search is to start with an initial interval of size n that includes the entire array. The algorithm then computes a middle element, as in binary search, and compares it to the target element. If the target element is found, the search terminates. If the middle element is greater than the target element, the algorithm sets the new interval to the left half of the previous interval, and if the middle element is less than the target element, the new interval is set to the right half of the previous interval. However, unlike binary search, Meta Binary Search does not perform a comparison for each iteration of the loop.

### Issue details

Meta Binary Search is an advanced Binary search where we are excluding ourself from comparing each element of the array.

### Additional Information

I would like to work on this issue. Kindly assign it to me under Hacktoberfest-2024.

**Comment by Dishant-dyavarchetti** [comment]
I would like to work on this issue...Will it be okay if i contribute the whole code on the repo??

**Comment by Abhijais4896** [comment]
I would love to work on this issue, Kindly assign it to me under hacktoberfest-2024 open source program.

**Comment by KSVeerendernath** [comment]
Hi @anijit18,
I hope you're doing well!

This is Veer, and I’m currently pursuing my master's degree. As part of one of my course assignments, I need to select a GitHub repository and contribute to it in some capacity. I came across your repository and would love to work on this particular issue.

It would be greatly appreciated if you could assign the issue to me and allow me to contribute. Please feel free to reach out if you have any questions or need further information from my side.

Thanks,
Veer
