### ISSUE TITLE
adding stock span optimized solution using java 

### ISSUE THREAD

**Issue by Avnee29** [TheAlgorithms/Java#5988]
### What would you like to Propose?

i want to add optimized java soln for  online stock span problem kindly assign me this @arindam89 @BurkHufnagel @qckzr @vbrazo @pschik 

### Issue details

Design an algorithm that collects daily price quotes for some stock and returns the span of that stock's price for the current day.

The span of the stock's price in one day is the maximum number of consecutive days (starting from that day and going backward) for which the stock price was less than or equal to the price of that day.

**Comment by siriak** [comment]
We don't add Leetcode problems
