### ISSUE TITLE
[FEATURE REQUEST] <StronglyConnectedComponentOptimizedTest.java>

### ISSUE THREAD

**Issue by hewageuhcu** [TheAlgorithms/Java#5990]
### What would you like to Propose?

This java file can't run because it ends with an unresolved compilation problem. I forked the master branch and tried to compile each code and here I found that one. 

### Issue details

![Screenshot 2024-10-25 204534](https://github.com/user-attachments/assets/00095d44-aea6-404a-9cf9-62e8c07af274)
Here is the output I got when tried to execute that.

![image](https://github.com/user-attachments/assets/a1f6e2e5-2e65-4421-85d0-94c40a08600b)
Here is the output from terminal.

### Additional Information

However, I hope by adding the correct package, this problem could be solved.

**Comment by siriak** [comment]
I'm not sure why you are having this issue, but we have build in our CI pipeline and it works just fine

**Comment by kashyapanjali** [comment]
hii @TheAlgorithm, Can you assign me for this issue.

**Comment by siriak** [comment]
Please also explain in your PR what the issue is and why it doesn't reproduce in PR checks
