### ISSUE TITLE
Add Sliding Window Algorithm Implementations

### ISSUE THREAD

**Issue by Chiefpatwal** [TheAlgorithms/Java#6000]
### What would you like to Propose?

I would like to propose adding a dedicated file, SlidingWindow.java, to this repository. This file will contain sliding window algorithms commonly used in competitive programming and interviews. These algorithms include solutions that demonstrate both fixed-length and variable-length sliding window techniques.

### Issue details

Currently, the repository lacks sliding window algorithms, a core technique in solving many subarray or substring-related problems efficiently. This proposal aims to address that gap by adding a dedicated file for sliding window algorithms, complete with explanations and test cases.

### Additional Information

The following well-known problems will be implemented:

    Maximum Sum Subarray of Size KK: This problem is commonly found in coding interviews and challenges.
    Longest Substring Without Repeating Characters: A classic problem on platforms like LeetCode, demonstrating the utility of sliding window techniques.
    Smallest Subarray with Sum Greater Than SS: This problem is frequently encountered in competitive programming scenarios.
 Can also add similar problems.

**Comment by charu1110** [comment]
@Chiefpatwal can i work on this issue ?

**Comment by Chiefpatwal** [comment]
@charu1110 sure you can, i have already created sliding window directory and have added two general problems for the same you can add others.

**Comment by m-saurabh01** [comment]
Can I add more problems in sliding window section?

**Comment by Chiefpatwal** [comment]
@m-saurabh01 sure

**Comment by Chiefpatwal** [comment]
Added common patterns of sliding window.
