### ISSUE TITLE
Efficient trek

### ISSUE THREAD

**Issue by gourab9817** [TheAlgorithms/Java#6008]
### What would you like to share?

Problem Description.

A hiker is planning a multi-day trek through the mountains. There are n trails, each with a certain length, given as a list, of trails, that need to be hiked in the order in the list. The hiker wants to achieve a new world record by completing the trek in a record number of days. Each day, the hiker will cover at least one trail and must minimize the sum of the lengths of the longest trail hiked each day. Find this minimum sum.
Example
There are n = 6 trails with lengths trails = [10, 5, 9, 3, 8, 15], and record = 2.
One optimal solution is for the hiker to cover the first trail on the first day, and the remaining trails on the second day. On the first day, the longest trail is 10, and on the second day, it is max(5, 9, 3, 8, 15) =
15. The sum of the lengths of the longest trails is 10 + 15 = 25. Return 25.
Function Description
Complete the function-efficient Trek in the editor below.
efficient Trek has the following parameters:
int trails: an array of integers denoting the order and length of the trails. int record: the number of days to cover all the trails.
Returns
int: the minimum sum of the longest trails on each day
Constraints
﻿﻿1≤ n≤ 300
﻿﻿1 ≤ record ≤ n ≤ 300
﻿﻿1 ≤ trails[i] ≤ 105
﻿﻿
﻿﻿Sample Input For Custom Testing

STDIN
Function

5 → trails[] size n = 5
150 →trails = [150, 200, 400, 350, 250]
200
400
350
250
3 →record = 3

Sample Output
750

**Comment by gourab9817** [comment]
Please assign me to this to achieve my contribution target.

**Comment by siriak** [comment]
We don't add algorithms which are purely problems from coding competitions. They have to be a well-known algorithm and have a real-world use

**Comment by gourab9817** [comment]
Problem Breakdown
Objective: The hiker must complete all trails in a certain number of days (record). The trails have different lengths, and the goal is to minimize the sum of the longest trail hiked each day.
Constraints: The hiker must cover at least one trail per day. The challenge is to find a way to distribute the trails across record days to minimize the maximum trail length each day.
Solution Approach
The solution provided follows a greedy approach:

Initial Setup: The code accepts the trail lengths and the number of days (a record) as inputs.

Looping Through First (record - 1) Trails:

The code assumes that for the first record - 1 days, the hiker covers only one trail each day.
It loops through the first record - 1 trails, adding their lengths directly to sum. This is because covering only one trail on these days will make the longest trail of each day the length of the single trail hiked on that day.
Finding Maximum for the Remaining Trails:

After covering the first record - 1 trail, the code collects all remaining trails for the last day.
It calculates the maximum trail length from this remaining group, as this maximum will be the longest trail for that day.
The maximum trail length of the last day is then added to the sum.
Final Sum Calculation:

By following the above steps, the code achieves the minimum possible sum of the longest trails covered each day.

Example Walkthrough
Using the example trails = [150, 200, 400, 350, 250] with record = 3:

First record - 1 Days (2 Days):

The hiker takes the first two trails on two separate days:
Day 1: Trail length = 150
Day 2: Trail length = 200
Current sum = 150 + 200 = 350
Remaining Trails for the Last Day:

The remaining trails are [400, 350, 250].
The longest trail in this group is 400, so for the last day, the longest trail is 400.
Adding this to sum, we get 350 + 400 = 750.
Result: The function returns 750 as the minimum sum of the longest trails on each day.

Complexity Analysis
Time Complexity: 
𝑂(𝑛)
O(n), where 
𝑛
n is the number of trails. This is because the solution iterates over the list of trails twice: once for the first record - 1 trails and once to find the maximum of the remaining trails.
Space Complexity: 
𝑂(1)
O(1) (constant space), as the solution only uses a fixed amount of extra space regardless of input size.
