### ISSUE TITLE
Fractional Knapsack problem

### ISSUE THREAD

**Issue by iamkaniska** [TheAlgorithms/Java#6080]
### What would you like to share?

The Fractional Knapsack problem is an example where a greedy algorithm is particularly well-suited and effective. Assign mefor this issue.

**Comment by siriak** [comment]
It's already present here https://github.com/TheAlgorithms/Java/blob/df0c997e4bce827246ee9d93ec3b1fe3c55a4332/src/main/java/com/thealgorithms/greedyalgorithms/FractionalKnapsack.java#L17
