### ISSUE TITLE
Double Ended queue D.S is not implemented

### ISSUE THREAD

**Issue by ales-blaze** [TheAlgorithms/Java#638]
And i would like to implement it , Any suggestions?

**Comment by haruntuncay** [comment]
Hello, if this is still needed, I would like to contribute and implement it.
Also, by double ended queue, do you mean a deque ?
Please let me know if I can be assigned to this.
Thanks.

**Comment by pgupta1795** [comment]
Hi,Please let me know if this issue can be assigned and implemented?

**Comment by Nuthi-Sriram** [comment]
I would like to work on this

**Comment by Nuthi-Sriram** [comment]
I have submitted a pull request for deque hope you like the code

**Comment by iamlatin** [comment]
FEDERALGRANTS.COM  nada activo

**Comment by iamlatin** [comment]
api

**Comment by prashantdoshi28** [comment]
Hey @Nuthi-Sriram , I have reviewed your PR, please go through my findings in my review. Let's make sure that this issue can be closed in few days.
