### ISSUE TITLE
Java/DataStructures/Trees/BinaryTree.java has error with put method

### ISSUE THREAD

**Issue by Keenan-Ker51** [TheAlgorithms/Java#644]
The binary tree class seems to have an error on line 93, when trying to put more than one int into the tree it throws null pointer exception. I think the reason for this is that it calls the find function, using the value that you would want to add to the tree, so of course the find method will only return a null value, unless you happen to be adding the same value twice.

**Comment by varunu28** [comment]
I think this can be solved by adding a null check for the parent before proceeding to the comparison. 
@Keenan-Ker51  Can you help with a PR?

**Comment by ales-blaze** [comment]
I am interested in doing so, wait for your allowance!

**Comment by varunu28** [comment]
@ales-blaze 
You don't need to wait. You can go ahead and open a PR

**Comment by ales-blaze** [comment]
Wait, isn't there any way through which a particular person gets the authority to perform a particular task,
To avoid work collisions.

**Comment by varunu28** [comment]
@ales-blaze You can just comment in the issue that you are working on it. This would avoid any conflicts.

**Comment by marcgood96** [comment]
Should this issue be closed? It seems like themanchangechina fixed it.

**Comment by varunu28** [comment]
Yes. Closing it
