### ISSUE TITLE
Generalize using generics.

### ISSUE THREAD

**Issue by KylerSmith** [TheAlgorithms/Java#65]
# Enhancement
## Description
Many of the algorithms, namely sorting, searching and the data structures, are using primitive types for the implementation of the algorithms. This could be generalized to any comparable type  using generics.

**Comment by varunu28** [comment]
Thanks for pointing that out @KylerSmith . @AnupKumarPanwar I would like to work on this issue. Can you please assign it to me

**Comment by varunu28** [comment]
Here is the linear search with generics #80 
Would start working on others and would add more search and sort methods in future

**Comment by 0oo0** [comment]
Thanks.

**Comment by varunu28** [comment]
Added generic binary search #82 
Done with the searches. Would be adding generic sorts in future. 
Once both search and sorts are done let us make sure that any further addition of algorithms is in its generic form

**Comment by varunu28** [comment]
Started with creating generic version for sorts
Bubble Sort #83

**Comment by dynamitechetan** [comment]
Can we close this issue?

**Comment by shubhamtewari** [comment]
hey guys, should i alppy generics to the DataStructures?

**Comment by varunu28** [comment]
@shubhamtewari  Can you please point out which data structures, in particular, you want to apply generics?

**Comment by shubhamtewari** [comment]
I can start with stacks, then lists, graphs, queues, and heaps.
Essentially I want to apply generics to all the data structures in the
DataStructures directory.
But stated above are where I'd like to start.

**Comment by varunu28** [comment]
Sure. Go ahead.
You can open a PR once you are done with the changes. Go for refactoring the code rather than starting with a blank slate
