### ISSUE TITLE
Java convention violated

### ISSUE THREAD

**Issue by aravinth2094** [TheAlgorithms/Java#667]
https://github.com/TheAlgorithms/Java/blob/b9aacd4dcef07d457f80a9320309cdcc8c2cca92/DataStructures/Stacks/Stacks.java#L205

Although having multiple classes inside one file works, it is often against the convention to do so. It would be better to have two separate files named after their purposes, which would make a lot more sense and enhance readability.

**Comment by chhavi1028** [comment]
Hi,What you want is to make two different files , one with Array and other with ArrayList?

**Comment by hayderhassan** [comment]
Hi, this is my first attempt at an open source contribution. I've just made two new files StackArray.java and StackArrayList.java. I've moved the relevant code from Stacks.java into the new corresponding files. 
I've opened a pull request @aravinth2094 if you could please have a look at it?
