### ISSUE TITLE
unused imports

### ISSUE THREAD

**Issue by lprone** [TheAlgorithms/Java#699]
https://github.com/TheAlgorithms/Java/blob/46a384b4baee1ef63342915e9fbac3fac64bff14/Conversions/HexaDecimalToBinary.java#L1

All this imports can be removed

**Comment by sac2087** [comment]
https://github.com/TheAlgorithms/Java/blob/46a384b4baee1ef63342915e9fbac3fac64bff14/Others/RootPrecision.java#L1

only need this import: 
`
import java.util.Scanner;
`
