### ISSUE TITLE
wrong heaps package

### ISSUE THREAD

**Issue by lprone** [TheAlgorithms/Java#700]
https://github.com/TheAlgorithms/Java/blob/46a384b4baee1ef63342915e9fbac3fac64bff14/DataStructures/Heaps/EmptyHeapException.java#L4

Change it to: 
`
package DataStructures.Heaps
`

**Comment by sac2087** [comment]
https://github.com/TheAlgorithms/Java/blob/46a384b4baee1ef63342915e9fbac3fac64bff14/DataStructures/Heaps/EmptyHeapException.java#L4

**Comment by sac2087** [comment]
https://github.com/TheAlgorithms/Java/blob/46a384b4baee1ef63342915e9fbac3fac64bff14/DataStructures/Heaps/Heap.java#L1

**Comment by sac2087** [comment]
Same for that classes:
HeapElement
MaxHeap
MinHeap
MinPriorityQueue
