### ISSUE TITLE
Fibonacci sequence should start with [0, 1] and not [1, 1]

### ISSUE THREAD

**Issue by HeikoAlexanderWeber** [TheAlgorithms/Java#708]
# Summary
The Fibonacci sequence is defined by following statement:
_F(n) = F(n-1) + F(n-2) with F(0) = 0 and F(1) = 1_. For reference, please see [The online encyclopedia of integer sequences](https://oeis.org/A000045) as primary reference, leading to other references with more detailed description.
(Older) books sometimes omit the preceding _0_, but this representation is deprecated.

### fibMemo
When calling the function [Fibonacci.fibMemo](https://github.com/TheAlgorithms/Java/blob/e4a9d38ee39767711784f1d5c21029ce2341846f/Dynamic%20Programming/Fibonacci.java#L30), the result of _F(0)_ = _1_. This is incorrect since _F(0) = 0_. Furthermore this leads to the following sequence for the first few integers: _[1, 1, 1, 2, 3, 5, ...]_ for _input=[0, 1, 2, 3, 4, 5, ...]_.
### fibBotUp
When calling the function [Fibonacci.fibBotUp](https://github.com/TheAlgorithms/Java/blob/e4a9d38ee39767711784f1d5c21029ce2341846f/Dynamic%20Programming/Fibonacci.java#L53), the program throws an exception when trying to get the value for _F(0)_ from the map. Therefore _F(0)_ is not supported by this implementation.

## Task
Fix both implementation(s) to
a) Return correct values for _F(x)_
b) Do not throw exceptions
Acceptance criteria is met when both functions return _[0, 1, 1, 2, 3, 5]_ for _input=[0, 1, 2, 3, 4, 5]_.

**Comment by ales-blaze** [comment]
i will work on it!

**Comment by HeikoAlexanderWeber** [comment]
@ales-blaze I have already fixed the bug because I was really bored. See the attached PR.

**Comment by wangyuan2019** [comment]
I will try it
