### ISSUE TITLE
Binary Search fails on edge cases

### ISSUE THREAD

**Issue by varunu28** [TheAlgorithms/Java#728]
The current binary search fails on bug and was pushed to the master untested. The initial implementation done by me took care of the edge cases in the base exit condition.

@nikitap492 The code was changed by you where the base condition is changed. Was your PR reviewed by someone and did you added the edge case tests?

**Comment by 007aniketkumar** [comment]
varunu28, is the above issue fixed? If not can you provide a few more details?

**Comment by varunu28** [comment]
@007aniketkumar I don't think the issue has been resolved yet. You can test it once and I think it will fail in some borderline cases.
I am not active the Java repo right now but working on the Kotlin side of the project right now. 
@yanglbme can guide you on this.

**Comment by grantrzchan** [comment]
Hi @varunu28 , has this issue been fixed? Perhaps I can work on it?

**Comment by himalayanDrifter** [comment]
Hi @varunu28 ,if the issue is still not fixed then I think I am able to solve the issue. Can i?
