### ISSUE TITLE
File master/DataStructures/Lists/SinglyLinkedList.java line 146 may cause NullPointerException

### ISSUE THREAD

**Issue by Seandba** [TheAlgorithms/Java#771]
In the main method line 146,if you change  myList.deleteNth(1) to  myList.deleteNth(3),3 is the count of list[7 -> 5 -> 11],you will ses (Exception in thread "main" java.lang.NullPointerException),because the postion in the deleteNth() method should from zero to (the count of list minus 1).

**Comment by abhijay94** [comment]
@Seandba Pushed the fix for this issue. This is good to be closed now.
https://github.com/TheAlgorithms/Java/pull/772
