### ISSUE TITLE
bug: MaxHeap.toggleUp should determine if there is a parent node.

### ISSUE THREAD

**Issue by MrHeer** [TheAlgorithms/Java#775]
https://github.com/TheAlgorithms/Java/blob/990b88f72fb14155c4075b1f384808e5b1d80857/DataStructures/Heaps/MaxHeap.java#L49-L56

should determine if there is a parent node while looping. Like this:
```java
while ((int) Math.floor(elementIndex / 2) > 0 && getElementKey((int) Math.floor(elementIndex / 2)) < key) {
    ......
}
```

**Comment by 1170500820** [comment]
I am working on this issue.
