### ISSUE TITLE
Looks like BFS and DFS is missing 

### ISSUE THREAD

**Issue by darshantumkur** [TheAlgorithms/Java#784]
https://github.com/TheAlgorithms/Java/blob/master/DataStructures/Graphs/DFS.java

**Comment by Sasi-007** [comment]
The code doesn't exist their. Can i Take this issue.

**Comment by swatiprajapati08** [comment]
BFS and DFS in JAVA #1019

**Comment by anilabha** [comment]
I just send a marge request on Graph Algorithms 
1.Bellman ford algorithm
2.BFS
3.DFS
4.Prims algorithm
5.Dijkstra algorithm
