### ISSUE TITLE
We want to add some contents :

### ISSUE THREAD

**Issue by L170300101** [TheAlgorithms/Java#788]
Hi guys, We've got an assignment to contribute OSS in this semester. we think we can add some algorithms to improve on  this OSS!
We might add 'Kruscal MST', 'Huffman Tree', and 'Fibonacci Heap', 'Van Emde Boas Tree', 'B Tree' also considered.
Those things are what we learned last semester as taking Introduction to Algorithms class
We're gonna try Kruscal MST', 'Huffman Tree' those two things first, If you guys don't mind.
Hope we get a chance to augment, and have a nice day! Thanks!

**Comment by quackduck** [comment]
Okay! Fork this repo,  commit your changes and make a pull request
