### ISSUE TITLE
Algorithms and Optimization

### ISSUE THREAD

**Issue by Balls-and-Dick-69** [TheAlgorithms/Java#810]
How exactly am I supposed to know which of these I am supposed to learn

**Comment by lakshay761** [comment]
Start from basic sorting and searching then move onto some more challenging data structures and then harder topics like Dynamic Programming.
Read theory about topics before diving straight into the code otherwise, it can be very difficult.

**Comment by leafgecko** [comment]
@Balls-and-Dick-69 I hope this guides would help you.
If you are new to coding, I suggest following the curriculum here [https://courses.csail.mit.edu/6.006/fall11/notes.shtml](url)
A good way to start is the sorting algos: Insertion, Merge, Heap, Trees (Binary/AVL)
Understanding Big-Oh, Theta, Omega time complexities.
Hashing, Graphs
Dijkstra pathing
Dynamic Programming

If you cover those already, a good next step is Designing and Analysis of Algorithms
[http://stellar.mit.edu/S/course/6/sp15/6.046J/index.html](url)

These are really useful for me as the also provide problem sets and solutions, and if you are more of an audio learner, they do put up their work on [https://www.youtube.com/watch?v=HtSuA80QTyo&list=PLUl4u3cNGP61Oq3tWYp6V_F-5jb5L2iHb&index=1](url)

 I hope this is insightful for you.

Side question, may I ask what the hacktoberfest label is for @AnupKumarPanwar

**Comment by xcidia22** [comment]
@Balls-and-Dick-69 though this is kind off the topic, but if you also want to try practicing problem solving for data-algorithms please do check: https://www.hackerrank.com/
It's a website in where challenges are created and can be compiled in different languages it is extremely beneficial to most starters in programming and I myself still rely on those challenges to help develop your logical thinking and problem solving skills.

**Comment by fclk1212** [comment]
i  wantto fix to the issue

**Comment by AppleteeYT** [comment]
שלום חברי
