### ISSUE TITLE
algorithms in the others folder are too open ended

### ISSUE THREAD

**Issue by furahadamien** [TheAlgorithms/Java#816]
I was going through most of the algorithms in the [others](https://github.com/TheAlgorithms/Java/tree/master/Others) folder, and to me, they appear to be too open-ended and as a result, they fail to tackle most of the edge cases. Most of them are addressing the problem but they are not looking at all sorts of inputs. For example, the [countWords](https://github.com/TheAlgorithms/Java/blob/master/Others/CountWords.java) algorithm doesn't look at instances where we have a sequence of non-alphanumeric characters. Should you consider "#####" a word for example? The other problem is that most of the algorithms do not actually explain what they are doing in the first place.

**Comment by yanglbme** [comment]
@furahadamien thanks for your feedback. Could you create a pull request to fix them? PR is welcome in [TheAlgorithms/Java](https://github.com/TheAlgorithms/Java) repository.
