### ISSUE TITLE
Leaflet (Hi guys, I am new to coding and I was watching this youtube video about building maps in leaflet and the map is not showing on when I execute. Can someone please help me debug this?)

### ISSUE THREAD

**Issue by Lucasknight** [TheAlgorithms/Java#858]
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8" />
		<meta name="viewpoint" content="width=device-width, initial-scale=1 />
		<title>
		   My map
		</title>
		
		<link rel="stylesheet" href="lib/leaflet/leaflet.css" />
		<script scr="lib/leaflet/leaflet.js"></script>
		<script scr="data/countries.geojson"></script>
		<style type="text/css">
			#map {height : 400px; }
			</style>
			
		</head>
<body>
<h1>My map</h1>
<div id="map"></div>
<script>
	var map = L.map('map').setView([43.8476: 18.35.64]: 13);
	var countriesLayer = L.geojson(countries).addTo(map);
	</script>
	
	

</body>
</html>

**Comment by Lucasknight** [comment]
![code](https://user-images.githubusercontent.com/38246935/65343745-4be74a00-dbc5-11e9-89cc-96812e68d481.JPG)

**Comment by alissonrenan95** [comment]
Hello,
you should have an access token or key for use map api. https://www.mapbox.com/ sign up and generate an access token.

<html>
<head>
<style type="text/css">
#map {height : 100%; } 
</style>
<link rel="stylesheet" 

href="lib/leaflet/leaflet.css">
<script src="lib/leaflet/leaflet.js"></script>
</head>
My map

<body>
<div id="map"></div>
<script> 
var map = L.map('map').setView([43.8476, 18.3564], 

13);
L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/

{z}/{x}/{y}.png?access_token={accessToken}', {
	maxZoom: 18,
	id: 'mapbox.streets',
	accessToken: 'your access token here'
}).addTo(map);
</script>
</body>
</html>

**Comment by alissonrenan95** [comment]
Hello,
you should have an access token or key for use map api. https://www.mapbox.com/ sign up and generate an access token.

`<html>
<head>
<style type="text/css">
#map {height : 100%; } 
</style>
<link rel="stylesheet" 

href="lib/leaflet/leaflet.css">
<script src="lib/leaflet/leaflet.js"></script>
</head>
My map

<body>
<div id="map"></div>
<script> 
var map = L.map('map').setView([43.8476, 18.3564], 

13);
L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/

{z}/{x}/{y}.png?access_token={accessToken}', {
	maxZoom: 18,
	id: 'mapbox.streets',
	accessToken: 'your access token here'
}).addTo(map);
</script>
</body>
</html>


`

**Comment by alissonrenan95** [comment]
Hello,
you should have an access token or key for use map api. https://www.mapbox.com/ sign up and generate an access token. 
[test.zip](https://github.com/TheAlgorithms/Java/files/3654290/test.zip)
