### ISSUE TITLE
I have a question  in Java/Sorts/MergeSort.java 

### ISSUE THREAD

**Issue by dumonody** [TheAlgorithms/Java#88]
```
70.  while (i <= middle) {
71.             this.array[k] = this.tempMergArr[i];
72.             k++;
73.             i++;
74. }
```
Can I change this snippet to 
```
while(j <= higherIndex){
           this.array[k] = this.tempMergArr[j];
           k++;
           j++;
}
```

**Comment by varunu28** [comment]
@dumonody  I have made a PR for a generic version of MergeSort. Once it is merged we both can discuss on this. I have done a lot of changes so the previous code will be completely overwritten

**Comment by dumonody** [comment]
@varunu28 Sorry,my description is not correct. I want to ask, why out of the excess must be "i", not "j".

**Comment by Jeh212** [comment]
@dumonody   to use the variable "j" as a counter, you will Need to declare the variable as an integer.
