### ISSUE TITLE
Element.equals() is overridden but Element.hashCode() is not 

### ISSUE THREAD

**Issue by mishraanmol** [TheAlgorithms/Java#91]
Shouldn't the results of hashCode() be consistent with the notion of value equality as implemented by .equals()?

Disclaimer: I don't really consider myself a Java programmer. I'm analyzing the Java code in the process of producing a Python port of Structurizer.

@AndrewJey

**Comment by varunu28** [comment]
@dynamitechetan  I suppose we can close this issue too as it is not related to the code present in the repository
