### ISSUE TITLE
Bisection search

### ISSUE THREAD

**Issue by somaditya** [TheAlgorithms/Java#956]
Math section could also include bisection search to approximate square root.

**Comment by lorderikstark** [comment]
@somaditya By  bisection search do you mean Binary Search ??

**Comment by Sasi-007** [comment]
Can i take this issue

**Comment by SarcasticNastik** [comment]
I would like to take up this issue.

**Comment by somaditya** [comment]
> @somaditya By bisection search do you mean Binary Search ??

no, it's for finding square root/cube root

**Comment by somaditya** [comment]
> @somaditya By bisection search do you mean Binary Search ??

oops, my bad. turns out they are the same thing.
