### ISSUE TITLE
Add more algorithms

### ISSUE THREAD

**Issue by AnupKumarPanwar** [TheAlgorithms/Java#96]
This repo has less contributions. Please add more algorithms. 

See the structure and README of this repo for reference
https://github.com/TheAlgorithms/Python

**Comment by dhinske** [comment]
would you be interested in some Set-implementations or maybe Bag? didnt see it in your repo :)

**Comment by dpunosevac** [comment]
I would like to contribute it. I see that you have no shell sort algorithm for Java. I would take that one first. Than later I would continue with few mores, if that is ok.

**Comment by mpokryva** [comment]
Would you be interested in a level-order tree traversal?

**Comment by dpunosevac** [comment]
@mpokryva Sure man. I am up for anything. :)

**Comment by dynamitechetan** [comment]
Thanks. @mpokryva

**Comment by mpokryva** [comment]
Ok, I will take that then.

**Comment by dpunosevac** [comment]
@mpokryva I mistakenly thought you were talking to me. And not asking for yourself. Anyway, you can grab that one, and I hope that @dynamitechetan needs shellsort, so I do that one.

**Comment by mpokryva** [comment]
Ok, sounds good! Sorry for the misunderstanding :)

**Comment by varunu28** [comment]
@dynamitechetan  @AnupKumarPanwar  Would be continue to add more algorithms to this as a part of hacktoberfest
PRs would be maily in Data Structures and other domain

**Comment by rei2hu** [comment]
Please look over pull requests before merging because I noticed the most recent one won't even compile properly and I'm assuming that a lot of people will make PRs soon because of Hacktoberfest (myself included). For example, in PR #101 there are many errors.

Can't compile because there is no type for `len_a` and `len_b`
Can't compile because `calculate_distance` is a non-static method
One of the loops will go on forever because it's declared as `for(int j = 0; i < len_b; j++)` and `i` is not getting updated within the loop.

**Comment by varunu28** [comment]
@rei2hu @dynamitechetan @AnupKumarPanwar 
Also the PRs should be monitored correctly to check for coding style and if an addition to the repo is actually an algorithm or just a solution of an interview question. The long term goal should be to make this repo as a one stop solution for Java algorithms rather than a repository with bunch of random interview problems.

**Comment by AnupKumarPanwar** [comment]
@dynamitechetan @varunu28 @rei2hu 
I think we should create a repo that contains simple English explanation of the algorithms with example and a link to their implementation in different programming languages.

**Comment by praveenkannan** [comment]
@AnupKumarPanwar I am relatively late here so I though I directly ask you. Whats next in your priority list. i ll address it. I love writing algorithms.

**Comment by AnupKumarPanwar** [comment]
@praveenkannan I would like you to contribute on
https://github.com/TheAlgorithms/Algorithms-Explainations

**Comment by praveenkannan** [comment]
@AnupKumarPanwar assign that to me. I am starting to work on it now.

**Comment by Alastifer** [comment]
@AnupKumarPanwar can I write dijkstra algo on Java?

**Comment by fredz0003** [comment]
Wouldn't it be easier to keep track of the algorithms that are missing? Some sort of list on the repo maybe. 

_Sent from my Samsung SM-G955U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fredz0003** [comment]
Wouldn't it be easier to keep track of the algorithms that are missing? Some sort of list on the repo maybe.  

_Sent from my Samsung SM-G955U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MichGedd** [comment]
Would I be able to write A* Algorithm?  I have a version made in Processing

**Comment by lvncnt** [comment]
#124 add KMP algorithm; improve binary search

**Comment by fredz0003** [comment]
I've looked at the python repo, and I will be doing a bunch of the cypher algorithms.

**Comment by shikhart98** [comment]
Are you interested to add compression algorithm?

**Comment by dhinske** [comment]
#147 Added Bag-Datastructure

**Comment by tifa64** [comment]
@AnupKumarPanwar I just started and I added the description of Shell sort in the README, can you assign me to a task ?

**Comment by bhalla98** [comment]
@AnupKumarPanwar are you looking for data structure implementation as well?

**Comment by PAPERPANKS** [comment]
I will update the `readme.md` file with the latest codes.
In reference to @AnupKumarPanwar issue #96 about updating structure of README file.

**Comment by PAPERPANKS** [comment]
#154 added more content in README

**Comment by AK-007** [comment]
Can I add LCS problem to dynamic programming?

**Comment by fredz0003** [comment]
Are you guys interested in adding math algorithms? I can add linear interpolation and extrapolation. If so I'll add a Math folder/Package. 

_Sent from my Samsung SM-G955U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Stuk4** [comment]
Can i add the Euclidean algorithm ?

**Comment by vn17** [comment]
Would you be interested in a Java 8 implementation of an Image processing algorithm - Histogram Equalization Algorithm?

**Comment by avsingh999** [comment]
would you interested in segment tree find the minimum in a range

**Comment by AKS1996** [comment]
can try for nested_brackets.py and password_gen.py equivalents, as in pull request #218

**Comment by manimanasamylavarapu** [comment]
Hi I am getting this error
remote: Permission to TheAlgorithms/Java.git denied to manimanasamylavarapu.

**Comment by varunu28** [comment]
@manimanasamylavarapu I suppose you were trying to edit the main repo

**Comment by manimanasamylavarapu** [comment]
@varunu28 you are right!! I then forked and proceeded .Thanks :)

**Comment by chugh22** [comment]
added Tarjan's Algorithm for finding articulation point in a graph #245

**Comment by AKS1996** [comment]
separated main and generatePassword functions #218

**Comment by PAPERPANKS** [comment]
@AnupKumarPanwar reopen this issue i have added a new example

**Comment by YJDave** [comment]
@AnupKumarPanwar Add algorithm for Bucket Sort. Let me know if any changes are required :)

**Comment by italo-batista** [comment]
I have just opened a [pull request](https://github.com/TheAlgorithms/Java/pull/293) in which I add the Floyd Warshall graph algorithm to find shortest paths between every pair of vertices. If you please review me.. (:

**Comment by italo-batista** [comment]
I also opened a [pull request](https://github.com/TheAlgorithms/Java/pull/294) to add the sorting algorithm QuickSortMedianOfThree. :grin:

**Comment by zhexuany** [comment]
add a algo for coin change https://github.com/TheAlgorithms/Java/pulls

**Comment by italo-batista** [comment]
[Pull Request](https://github.com/TheAlgorithms/Java/pull/300) to add Bellman-Ford graph algorithm to find shortest path from one vertex to all. :smiley:

**Comment by Febaug** [comment]
Hey, a friend of mine and I would write the Hopcroft-Karp algorithm with the amount of maximal cardinal matchings as output and - if we're able to implement it - extend it later to give out the exact matchings.

**Comment by Phil-Schmidt** [comment]
Hi there, user Febaug has tipped me off about this project and I'd like to contribute as well. I've seen that you have a subdirectory for crypto algorithms, but you're still missing an implementation of the Advanced Encryption Standard. I'd love to build that for you unless you see a problem with that.

**Comment by YooSeonjae** [comment]
Add a circular queue or ring wait, a data structure that uses a single fixed-size buffer just like an end-to-end connection
#322

**Comment by YooSeonjae** [comment]
One of the greedy algorithms, Scheduling to Minimize Lateness
#309

**Comment by anthonycampbell** [comment]
Could I add a skiplist implementation?

**Comment by RishiPrakash** [comment]
I have added [pullRequest](https://github.com/TheAlgorithms/Java/pull/433)   , please review and merge.
