### ISSUE TITLE
README for design patterns

### ISSUE THREAD

**Issue by ani03sha** [TheAlgorithms/Java#965]
There should be a README file for each type of design pattern which should include the following points-
- Description of the design pattern
- Common use cases of that design pattern
- Explanation of the code

**Comment by asha15** [comment]
Shall i work on this?

**Comment by ani03sha** [comment]
@AnupKumarPanwar @christianbender @dynamitechetan can we go forward with this issue?

**Comment by mdr20091** [comment]
mn
