### ISSUE TITLE
Missing Tower of Hanoi and other  naturally recursive questions in D.P.

### ISSUE THREAD

**Issue by ghost** [TheAlgorithms/Java#971]

**Comment by lorderikstark** [comment]
Naturally recursive problems like Tower of Hanoi ,etc. should be provided both an recursive and Dynamic Programming approach.

**Comment by Sasi-007** [comment]
Can i take this issue and solve it

**Comment by prashantkumar-cmd** [comment]
may i fix the bugs in this issue
