### ISSUE TITLE
SingleLinkedlist.insertNth will get a infinite loop when insert a node at the end of list

### ISSUE THREAD

**Issue by lujianmei** [TheAlgorithms/Java#973]
As titled.

`  public static void main(String args[]) {
        SinglyLinkedList myList = new SinglyLinkedList();

        assert myList.isEmpty();

        myList.insertHead(5);
        myList.insertHead(7);
        myList.insertHead(10);

        myList.display(); // 10 -> 7 -> 5

        myList.deleteHead();

        myList.display(); // 7 -> 5

        myList.insertNth(11, 0);

        myList.display(); // 7 -> 5 -> 11

        myList.insertNth(13, 2);

        myList.display(); // 7 -> 5 -> 11 -> 13

        myList.deleteNth(1);

        myList.display(); // 7-> 11

    }`

**Comment by shellhub** [comment]
Bug fixed, try again

**Comment by bw-space** [comment]
Can you explain clearly, where are we getting an infinite loop?

**Comment by Abubakar548** [comment]
not getting inifite loop when inserting at end using  "SingleLinkedlist.insertNth"

**Comment by shahabrar7746** [comment]
i would like to work on this issue. It looks like perfect start  for a beginner to code
